create table eba_demo_dg_dept
(    deptno number(4,0) 
     generated by default on null as identity 
     (start with 50 increment by 10 maxvalue 9000 nocache nocycle)
     constraint eba_demo_dg_dept_pk 
     primary key,
     dname varchar2(50 byte), 
     loc varchar2(50 byte) );

create table eba_demo_dg_emp
(    empno number(4,0) 
     generated by default on null as identity 
     (start with 8000 increment by 10 maxvalue 90000 nocache nocycle)
     constraint eba_demo_dg_emp_pk 
     primary key,
     ename varchar2(50 byte), 
     job varchar2(50 byte), 
     mgr number(4,0), 
     hiredate date, 
     sal number(7,2), 
     comm number(7,2), 
     deptno number(4,0) );

alter table eba_demo_dg_emp add constraint eba_demo_dg_mgr_fk
foreign key (mgr) references eba_demo_dg_emp (empno);

alter table eba_demo_dg_emp add constraint eba_demo_dg_dept_fk
foreign key (deptno) references eba_demo_dg_dept (deptno);

create index eba_demo_dg_emp_mgr_i on eba_demo_dg_emp (mgr);

create index eba_demo_dg_emp_dept_i on eba_demo_dg_emp (deptno);

create view emp_dept_v as
select e.empno,
       e.ename,
       e.job,
       (select m.ename 
          from eba_demo_dg_emp m 
         where e.mgr = m.empno) mgr,
       e.hiredate,
       e.sal,
       e.comm,
       d.deptno,
       d.dname,
       d.loc
from eba_demo_dg_emp e,
     eba_demo_dg_dept d
where e.deptno = d.deptno (+);

declare
    type t_dept is table of eba_demo_dg_dept%rowtype index by binary_integer;
    l_dept t_dept;
    procedure d (  
        p_deptno in number,
        p_dname  in varchar2,
        p_loc    in varchar2 ) 
    is
    begin
        l_dept(l_dept.count + 1).deptno := p_deptno;
        l_dept(l_dept.count).dname      := p_dname;
        l_dept(l_dept.count).loc        := p_loc;
    end d;
begin
    d (10,'ACCOUNTING','NEW YORK');
    d (20,'RESEARCH','DALLAS');
    d (30,'SALES','CHICAGO');
    d (40,'OPERATIONS','BOSTON');
    forall i in indices of l_dept
        insert into eba_demo_dg_dept values l_dept(i);
end;
/

declare
    type t_emp is table of eba_demo_dg_emp%rowtype index by binary_integer;
    l_emp t_emp;
    procedure e (  
        p_empno    in number,
        p_ename    in varchar2,
        p_job      in varchar2,
        p_mgr      in varchar2,
        p_hiredate in date,
        p_sal      in number,
        p_comm     in number,
        p_deptno   in number
    ) is
    begin
    l_emp(l_emp.count + 1).empno := p_empno;
    l_emp(l_emp.count).ename      := p_ename;
    l_emp(l_emp.count).job        := p_job;
    l_emp(l_emp.count).mgr        := p_mgr;
    l_emp(l_emp.count).hiredate   := p_hiredate;
    l_emp(l_emp.count).sal        := p_sal;
    l_emp(l_emp.count).comm       := p_comm;
    l_emp(l_emp.count).deptno     := p_deptno;
    end e;
begin
    e (7839,'KING','PRESIDENT',null,to_date('17-11-81','DD-MM-RR'),5000,null,10);
    e (7698,'BLAKE','MANAGER',7839,to_date('01-05-81','DD-MM-RR'),2850,null,30);
    e (7782,'CLARK','MANAGER',7839,to_date('09-06-81','DD-MM-RR'),2450,null,10);
    e (7566,'JONES','MANAGER',7839,to_date('02-04-81','DD-MM-RR'),2975,null,20);
    e (7788,'SCOTT','ANALYST',7566,to_date('09-12-82','DD-MM-RR'),3000,null,20);
    e (7902,'FORD','ANALYST',7566,to_date('03-12-81','DD-MM-RR'),3000,null,20);
    e (7369,'SMITH','CLERK',7902,to_date('17-12-80','DD-MM-RR'),800,null,20);
    e (7499,'ALLEN','SALESMAN',7698,to_date('20-02-81','DD-MM-RR'),1600,300,30);
    e (7521,'WARD','SALESMAN',7698,to_date('22-02-81','DD-MM-RR'),1250,500,30);
    e (7654,'MARTIN','SALESMAN',7698,to_date('28-09-81','DD-MM-RR'),1250,1400,30);
    e (7844,'TURNER','SALESMAN',7698,to_date('08-09-81','DD-MM-RR'),1500,0,30);
    e (7876,'ADAMS','CLERK',7788,to_date('12-01-83','DD-MM-RR'),1100,null,20);
    e (7900,'JAMES','CLERK',7698,to_date('03-12-81','DD-MM-RR'),950,null,30);
    e (7934,'MILLER','CLERK',7782,to_date('23-01-82','DD-MM-RR'),1300,null,10);
    forall i in indices of l_emp
        insert into eba_demo_dg_emp values l_emp(i);
end;