begin

sp_globals.g_audit_this := FALSE;

insert all
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8001,1,'Customer Behavior Analytics',1,'N',2,7,sp_util.fix_demo_dates(sysdate-92),100,1,'L','A','Delivered customer behavior dashboards and conversion analysis.','insightiq,analytics,customer-behavior',6,sp_util.fix_demo_dates(sysdate-200),'SCOTT.TIGER@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'SCOTT.TIGER@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8002,3,'Personalized Recommendations Engine',3,'N',1,7,sp_util.fix_demo_dates(sysdate-90),100,1,'XL','A','Delivered recommendation models and an API for personalized experiences.','insightiq,ai,recommendations',30,sp_util.fix_demo_dates(sysdate-200),'ELENA.VARGAS@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'ELENA.VARGAS@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8003,3,'Demand Forecasting Models',5,'N',2,7,sp_util.fix_demo_dates(sysdate-94),100,1,'XL','A','Delivered demand forecasts for operations planning and customer demand signals.','insightiq,ai,forecasting',30,sp_util.fix_demo_dates(sysdate-200),'NAOMI.CHEN@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'NAOMI.CHEN@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8004,1,'Customer Journey Insights',7,'N',2,7,sp_util.fix_demo_dates(sysdate-93),100,1,'L','A','Delivered end-to-end customer journey reporting and drop-off analysis.','insightiq,journey,customer-systems',1,sp_util.fix_demo_dates(sysdate-200),'CALEB.FOSTER@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'CALEB.FOSTER@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8005,3,'Support Intelligence Classifier',9,'N',2,7,sp_util.fix_demo_dates(sysdate-91),100,1,'L','A','Delivered AI classification for support requests and routing insights.','insightiq,ai,support',30,sp_util.fix_demo_dates(sysdate-200),'ANDRE.COLLINS@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'ANDRE.COLLINS@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8006,1,'Data Quality Monitoring',11,'N',1,7,sp_util.fix_demo_dates(sysdate-90),100,1,'L','A','Delivered source-data quality checks, alerts, and remediation dashboards.','insightiq,analytics,data-quality',6,sp_util.fix_demo_dates(sysdate-200),'VICTOR.RAMIREZ@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'VICTOR.RAMIREZ@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8007,1,'InsightIQ Executive Dashboards',13,'N',3,7,sp_util.fix_demo_dates(sysdate-95),100,1,'M','A','Delivered executive KPI dashboards with drill-through reporting.','insightiq,analytics,dashboards',6,sp_util.fix_demo_dates(sysdate-200),'ISAAC.TURNER@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'ISAAC.TURNER@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8008,3,'Customer Segmentation Models',15,'N',2,7,sp_util.fix_demo_dates(sysdate-92),100,1,'L','A','Delivered behavioral customer segments for insight and targeting use cases.','insightiq,ai,segmentation',30,sp_util.fix_demo_dates(sysdate-200),'DOMINIC.REYES@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'DOMINIC.REYES@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8009,1,'Experimentation Analytics',17,'N',3,7,sp_util.fix_demo_dates(sysdate-94),100,1,'M','A','Delivered experiment measurement and statistical-result reporting.','insightiq,analytics,experimentation',6,sp_util.fix_demo_dates(sysdate-200),'ETHAN.CALDWELL@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'ETHAN.CALDWELL@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8010,1,'InsightIQ Data Access Controls',19,'N',1,7,sp_util.fix_demo_dates(sysdate-90),100,1,'L','A','Delivered role-based access controls and audit reporting for analytics data.','insightiq,security,data-access',4,sp_util.fix_demo_dates(sysdate-200),'LUCAS.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-90),'LUCAS.BENNETT@ACME.COM')
select 1 from dual;

insert all
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8101,8001,1,3,'Leads delivery and stakeholder reporting.','project-management',sp_util.fix_demo_dates(sysdate-198),'SCOTT.TIGER@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'SCOTT.TIGER@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8102,8001,2,1,'Builds behavior dashboards.','analytics,development',sp_util.fix_demo_dates(sysdate-198),'SCOTT.TIGER@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'SCOTT.TIGER@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8103,8002,3,3,'Leads recommendation delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'ELENA.VARGAS@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ELENA.VARGAS@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8104,8002,4,1,'Builds recommendation API.','ai,development',sp_util.fix_demo_dates(sysdate-198),'ELENA.VARGAS@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ELENA.VARGAS@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8105,8003,5,3,'Leads forecasting delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'NAOMI.CHEN@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'NAOMI.CHEN@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8106,8003,6,7,'Validates forecast assumptions.','research,ai',sp_util.fix_demo_dates(sysdate-198),'NAOMI.CHEN@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'NAOMI.CHEN@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8107,8004,7,3,'Leads journey insight delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'CALEB.FOSTER@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'CALEB.FOSTER@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8108,8004,8,8,'Designs journey visualizations.','ux,analytics',sp_util.fix_demo_dates(sysdate-198),'CALEB.FOSTER@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'CALEB.FOSTER@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8109,8005,9,3,'Leads support intelligence delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'ANDRE.COLLINS@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ANDRE.COLLINS@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8110,8005,10,1,'Builds classification workflow.','ai,development',sp_util.fix_demo_dates(sysdate-198),'ANDRE.COLLINS@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ANDRE.COLLINS@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8111,8006,11,3,'Leads data-quality delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'VICTOR.RAMIREZ@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'VICTOR.RAMIREZ@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8112,8006,12,5,'Validates quality controls.','qa,data-quality',sp_util.fix_demo_dates(sysdate-198),'VICTOR.RAMIREZ@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'VICTOR.RAMIREZ@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8113,8007,13,3,'Leads dashboard delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'ISAAC.TURNER@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ISAAC.TURNER@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8114,8007,14,8,'Designs executive dashboard views.','ux,analytics',sp_util.fix_demo_dates(sysdate-198),'ISAAC.TURNER@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ISAAC.TURNER@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8115,8008,15,3,'Leads segmentation delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'DOMINIC.REYES@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'DOMINIC.REYES@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8116,8008,16,7,'Evaluates segment quality.','research,ai',sp_util.fix_demo_dates(sysdate-198),'DOMINIC.REYES@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'DOMINIC.REYES@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8117,8009,17,3,'Leads experimentation delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'ETHAN.CALDWELL@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ETHAN.CALDWELL@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8118,8009,18,1,'Builds experiment reporting.','analytics,development',sp_util.fix_demo_dates(sysdate-198),'ETHAN.CALDWELL@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'ETHAN.CALDWELL@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8119,8010,19,3,'Leads access-control delivery.','project-management',sp_util.fix_demo_dates(sysdate-198),'LUCAS.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'LUCAS.BENNETT@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8120,8010,20,2,'Reviews data-security architecture.','architecture,security',sp_util.fix_demo_dates(sysdate-198),'LUCAS.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-198),'LUCAS.BENNETT@ACME.COM')
select 1 from dual;

insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9201,8001,1,'Behavior dashboards were limited to approved aggregated metrics for 1.0.','Behavior dashboards were limited to approved aggregated metrics for 1.0.','Behavior dashboards were limited to approved aggregated metrics for 1.0.','N',sp_util.fix_demo_dates(sysdate-170),'SCOTT.TIGER@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'SCOTT.TIGER@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9202,8002,3,'The recommendation API contract was approved after latency testing.','The recommendation API contract was approved after latency testing.','The recommendation API contract was approved after latency testing.','N',sp_util.fix_demo_dates(sysdate-170),'ELENA.VARGAS@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'ELENA.VARGAS@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9203,8003,5,'Operations approved the forecast horizon and confidence bands.','Operations approved the forecast horizon and confidence bands.','Operations approved the forecast horizon and confidence bands.','N',sp_util.fix_demo_dates(sysdate-170),'NAOMI.CHEN@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'NAOMI.CHEN@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9204,8004,7,'Journey reporting uses the agreed customer-event taxonomy.','Journey reporting uses the agreed customer-event taxonomy.','Journey reporting uses the agreed customer-event taxonomy.','N',sp_util.fix_demo_dates(sysdate-170),'CALEB.FOSTER@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'CALEB.FOSTER@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9205,8005,9,'Support leadership approved the classifier escalation threshold.','Support leadership approved the classifier escalation threshold.','Support leadership approved the classifier escalation threshold.','N',sp_util.fix_demo_dates(sysdate-170),'ANDRE.COLLINS@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'ANDRE.COLLINS@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9206,8006,11,'Data-quality alerts now identify the source owner and remediation path.','Data-quality alerts now identify the source owner and remediation path.','Data-quality alerts now identify the source owner and remediation path.','N',sp_util.fix_demo_dates(sysdate-170),'VICTOR.RAMIREZ@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'VICTOR.RAMIREZ@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9207,8007,13,'Executive KPI definitions were agreed before dashboard publication.','Executive KPI definitions were agreed before dashboard publication.','Executive KPI definitions were agreed before dashboard publication.','N',sp_util.fix_demo_dates(sysdate-170),'ISAAC.TURNER@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'ISAAC.TURNER@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9208,8008,15,'Segmentation models passed the agreed stability and bias checks.','Segmentation models passed the agreed stability and bias checks.','Segmentation models passed the agreed stability and bias checks.','N',sp_util.fix_demo_dates(sysdate-170),'DOMINIC.REYES@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'DOMINIC.REYES@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9209,8009,17,'Experiment results now include the required statistical-confidence summary.','Experiment results now include the required statistical-confidence summary.','Experiment results now include the required statistical-confidence summary.','N',sp_util.fix_demo_dates(sysdate-170),'ETHAN.CALDWELL@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'ETHAN.CALDWELL@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9210,8010,19,'Security approved the analytics-data access model and audit events.','Security approved the analytics-data access model and audit events.','Security approved the analytics-data access model and audit events.','N',sp_util.fix_demo_dates(sysdate-170),'LUCAS.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-170),'LUCAS.BENNETT@ACME.COM');


-- Three milestones and one completed review per project.
insert into sp_tasks
 (id,project_id,task,task_type_id,task_sub_type_id,owner_id,start_date,target_complete,status_id,status_last_changed_on,description,tags,display_sequence,impact,created,created_by,updated,updated_by)
select 9000 + (p.project_id - 8000) * 10 + t.seq, p.project_id, t.task,
       t.task_type_id, null, p.owner_id,
       sp_util.fix_demo_dates(sysdate + t.start_offset),
       sp_util.fix_demo_dates(sysdate + t.complete_offset), t.status_id,
       sp_util.fix_demo_dates(sysdate + t.complete_offset), t.description,
       t.tags, t.seq * 10, t.impact,sp_util.fix_demo_dates(sysdate-200),case p.owner_id when 1 then 'SCOTT.TIGER@ACME.COM' when 3 then 'ELENA.VARGAS@ACME.COM' when 5 then 'NAOMI.CHEN@ACME.COM' when 7 then 'CALEB.FOSTER@ACME.COM' when 9 then 'ANDRE.COLLINS@ACME.COM' when 11 then 'VICTOR.RAMIREZ@ACME.COM' when 13 then 'ISAAC.TURNER@ACME.COM' when 15 then 'DOMINIC.REYES@ACME.COM' when 17 then 'ETHAN.CALDWELL@ACME.COM' when 19 then 'LUCAS.BENNETT@ACME.COM' end,sp_util.fix_demo_dates(sysdate+t.complete_offset),case p.owner_id when 1 then 'SCOTT.TIGER@ACME.COM' when 3 then 'ELENA.VARGAS@ACME.COM' when 5 then 'NAOMI.CHEN@ACME.COM' when 7 then 'CALEB.FOSTER@ACME.COM' when 9 then 'ANDRE.COLLINS@ACME.COM' when 11 then 'VICTOR.RAMIREZ@ACME.COM' when 13 then 'ISAAC.TURNER@ACME.COM' when 15 then 'DOMINIC.REYES@ACME.COM' when 17 then 'ETHAN.CALDWELL@ACME.COM' when 19 then 'LUCAS.BENNETT@ACME.COM' end
from (
  select 8001 project_id, 1 owner_id from dual union all select 8002,3 from dual union all
  select 8003,5 from dual union all select 8004,7 from dual union all
  select 8005,9 from dual union all select 8006,11 from dual union all
  select 8007,13 from dual union all select 8008,15 from dual union all
  select 8009,17 from dual union all select 8010,19 from dual
) p
cross join (
  select 1 seq, 'Spec Complete' task, 21 task_type_id, -195 start_offset, -185 complete_offset, 14 status_id, 'Specification approved.' description, 'milestone,spec' tags, cast(null as varchar2(30)) impact from dual union all
  select 2, 'Code Complete', 23, -140, -120, 14, 'Implementation complete.', 'milestone,code', cast(null as varchar2(30)) from dual union all
  select 3, 'Merged', 24, -110, -105, 14, 'Merged to the release branch.', 'milestone,merge', cast(null as varchar2(30)) from dual union all
  select 4, 'Peer Review', 4, -165, -158, 8, 'Peer review completed.', 'review,peer', 'Medium' from dual
) t;

sp_globals.g_audit_this := TRUE;

exception
    when others then
        sp_globals.g_audit_this := TRUE;
end;