begin

sp_globals.g_audit_this := FALSE;

insert all
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6001, 2, 'Mobile Companion App Shell and Navigation', 1, 'Y', 2, 2, sp_util.fix_demo_dates(sysdate + 12), 80, 1, 'L', 'A', 'Delivers the mobile application shell, navigation patterns, and home experience.', 'mobile-companion,navigation,ui', 31, sp_util.fix_demo_dates(sysdate - 60), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'SCOTT.TIGER@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6002, 2, 'Mobile Companion Identity and Profile', 3, 'Y', 1, 2, sp_util.fix_demo_dates(sysdate + 13), 80, 1, 'XL', 'A', 'Delivers secure mobile sign-in, multifactor enrollment, and profile management.', 'mobile-companion,identity,profile', 35, sp_util.fix_demo_dates(sysdate - 60), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'ELENA.VARGAS@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6003, 2, 'Mobile Service Request Intake', 5, 'Y', 2, 2, sp_util.fix_demo_dates(sysdate + 10), 70, 1, 'L', 'A', 'Delivers guided mobile service-request intake with attachment capture and request tracking.', 'mobile-companion,service-requests,workflow', 32, sp_util.fix_demo_dates(sysdate - 60), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 3), 'NAOMI.CHEN@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6004, 2, 'Mobile Document Capture and Upload', 7, 'Y', 3, 2, sp_util.fix_demo_dates(sysdate + 9), 60, 1, 'M', 'A', 'Delivers camera-based document capture, upload validation, and resumable transfers.', 'mobile-companion,documents,upload', 33, sp_util.fix_demo_dates(sysdate - 60), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'CALEB.FOSTER@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6005, 2, 'Mobile Notifications and Preferences', 9, 'Y', 3, 2, sp_util.fix_demo_dates(sysdate + 8), 60, 1, 'M', 'A', 'Delivers push-notification preferences, deep links, and mobile notification delivery.', 'mobile-companion,notifications,preferences', 31, sp_util.fix_demo_dates(sysdate - 60), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'ANDRE.COLLINS@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6006, 2, 'Mobile Offline Mode and Synchronization', 11, 'Y', 1, 2, sp_util.fix_demo_dates(sysdate + 13), 80, 2, 'XL', 'A', 'Delivers offline access to key customer data and conflict-aware background synchronization.', 'mobile-companion,offline,sync', 33, sp_util.fix_demo_dates(sysdate - 60), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 5), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6007, 2, 'Mobile Billing and Payments', 13, 'Y', 1, 2, sp_util.fix_demo_dates(sysdate + 14), 70, 2, 'XL', 'A', 'Delivers invoice viewing, payment initiation, and secure payment confirmations on mobile.', 'mobile-companion,billing,payments', 36, sp_util.fix_demo_dates(sysdate - 60), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 6), 'ISAAC.TURNER@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6008, 3, 'Mobile AI Support Assistant', 15, 'Y', 2, 2, sp_util.fix_demo_dates(sysdate + 12), 70, 1, 'L', 'A', 'Delivers a knowledge-grounded AI assistant with mobile-first escalation to customer support.', 'mobile-companion,ai,support', 30, sp_util.fix_demo_dates(sysdate - 60), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 3), 'DOMINIC.REYES@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6009, 2, 'Mobile Accessibility Foundation', 17, 'Y', 2, 2, sp_util.fix_demo_dates(sysdate + 7), 90, 1, 'L', 'A', 'Delivers accessible components, screen-reader support, and keyboard-equivalent interactions.', 'mobile-companion,accessibility', 37, sp_util.fix_demo_dates(sysdate - 60), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'ETHAN.CALDWELL@ACME.COM')
  into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by)
    values (6010, 2, 'Mobile Performance and Quality Automation', 19, 'Y', 2, 2, sp_util.fix_demo_dates(sysdate + 15), 60, 2, 'L', 'A', 'Delivers automated device testing, performance telemetry, and mobile release-quality gates.', 'mobile-companion,performance,quality-automation', 38, sp_util.fix_demo_dates(sysdate - 60), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 5), 'LUCAS.BENNETT@ACME.COM')
select 1 from dual;

insert all
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6101, 6001, 1, 3, 'Owns app-shell delivery and stakeholder coordination.', 'project-management', sp_util.fix_demo_dates(sysdate - 60), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'SCOTT.TIGER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6102, 6001, 2, 1, 'Builds navigation and mobile home experience.', 'mobile,frontend', sp_util.fix_demo_dates(sysdate - 60), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'SCOTT.TIGER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6103, 6001, 8, 8, 'Designs mobile navigation patterns.', 'ux,design', sp_util.fix_demo_dates(sysdate - 60), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'SCOTT.TIGER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6104, 6002, 3, 3, 'Owns identity and profile delivery.', 'project-management', sp_util.fix_demo_dates(sysdate - 60), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ELENA.VARGAS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6105, 6002, 4, 1, 'Builds mobile sign-in and profile functions.', 'identity,mobile', sp_util.fix_demo_dates(sysdate - 60), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ELENA.VARGAS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6106, 6002, 6, 2, 'Reviews mobile authentication architecture.', 'architecture,security', sp_util.fix_demo_dates(sysdate - 60), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ELENA.VARGAS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6107, 6003, 5, 3, 'Owns service-request intake delivery.', 'project-management', sp_util.fix_demo_dates(sysdate - 60), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'NAOMI.CHEN@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6108, 6003, 6, 1, 'Builds request workflow and attachment capture.', 'workflow,mobile', sp_util.fix_demo_dates(sysdate - 60), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'NAOMI.CHEN@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6109, 6003, 10, 5, 'Validates request and attachment scenarios.', 'qa,functional-testing', sp_util.fix_demo_dates(sysdate - 60), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'NAOMI.CHEN@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6110, 6004, 7, 3, 'Owns document capture delivery.', 'project-management', sp_util.fix_demo_dates(sysdate - 60), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'CALEB.FOSTER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6111, 6004, 8, 1, 'Builds camera capture and upload processing.', 'mobile,upload', sp_util.fix_demo_dates(sysdate - 60), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'CALEB.FOSTER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6112, 6004, 12, 5, 'Validates upload reliability and recovery.', 'qa,upload', sp_util.fix_demo_dates(sysdate - 60), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'CALEB.FOSTER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6113, 6005, 9, 3, 'Owns notification delivery.', 'project-management', sp_util.fix_demo_dates(sysdate - 60), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ANDRE.COLLINS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6114, 6005, 10, 1, 'Builds push notifications and deep links.', 'notifications,mobile', sp_util.fix_demo_dates(sysdate - 60), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ANDRE.COLLINS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6115, 6005, 14, 8, 'Designs notification preference screens.', 'ux,design', sp_util.fix_demo_dates(sysdate - 60), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ANDRE.COLLINS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6116, 6006, 11, 3, 'Owns offline synchronization delivery.', 'project-management', sp_util.fix_demo_dates(sysdate - 60), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6117, 6006, 12, 1, 'Builds local data storage and synchronization.', 'offline,sync', sp_util.fix_demo_dates(sysdate - 60), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6118, 6006, 16, 5, 'Validates offline and conflict scenarios.', 'qa,sync', sp_util.fix_demo_dates(sysdate - 60), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6119, 6007, 13, 3, 'Owns mobile payment delivery.', 'project-management', sp_util.fix_demo_dates(sysdate - 60), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ISAAC.TURNER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6120, 6007, 14, 1, 'Builds mobile billing and payment integration.', 'payments,mobile', sp_util.fix_demo_dates(sysdate - 60), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ISAAC.TURNER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6121, 6007, 16, 2, 'Reviews payment security architecture.', 'architecture,security', sp_util.fix_demo_dates(sysdate - 60), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ISAAC.TURNER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6122, 6008, 15, 3, 'Owns mobile AI assistant delivery.', 'project-management,ai', sp_util.fix_demo_dates(sysdate - 60), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'DOMINIC.REYES@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6123, 6008, 16, 1, 'Builds mobile assistant and support handoff.', 'ai,mobile', sp_util.fix_demo_dates(sysdate - 60), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'DOMINIC.REYES@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6124, 6008, 18, 7, 'Evaluates assistant knowledge coverage.', 'research,ai', sp_util.fix_demo_dates(sysdate - 60), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'DOMINIC.REYES@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6125, 6009, 17, 3, 'Owns accessibility foundation delivery.', 'project-management,accessibility', sp_util.fix_demo_dates(sysdate - 60), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ETHAN.CALDWELL@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6126, 6009, 18, 1, 'Builds accessible mobile components.', 'mobile,accessibility', sp_util.fix_demo_dates(sysdate - 60), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ETHAN.CALDWELL@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6127, 6009, 20, 5, 'Validates screen-reader and interaction coverage.', 'qa,accessibility', sp_util.fix_demo_dates(sysdate - 60), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'ETHAN.CALDWELL@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6128, 6010, 19, 3, 'Owns performance and quality delivery.', 'project-management,quality', sp_util.fix_demo_dates(sysdate - 60), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'LUCAS.BENNETT@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6129, 6010, 20, 1, 'Builds automated testing and telemetry.', 'automation,performance', sp_util.fix_demo_dates(sysdate - 60), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'LUCAS.BENNETT@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (6130, 6010, 21, 5, 'Validates device coverage and quality gates.', 'qa,automation', sp_util.fix_demo_dates(sysdate - 60), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 60), 'LUCAS.BENNETT@ACME.COM')
select 1 from dual;

-- Comments are inserted oldest to newest so the comment-number trigger assigns numbers chronologically.
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6201, 6001, 1, 'Navigation patterns were consolidated into a shared shell to keep iOS and Android behavior aligned.', 'Navigation patterns were consolidated into a shared shell to keep iOS and Android behavior aligned.', 'Navigation patterns were consolidated into a shared shell to keep iOS and Android behavior aligned.', 'N', sp_util.fix_demo_dates(sysdate - 45), upper('scott.tiger@acme.com'), sp_util.fix_demo_dates(sysdate - 45), upper('scott.tiger@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6202, 6001, 2, 'Product approved the simplified home experience for the 1.0 release.', 'Product approved the simplified home experience for the 1.0 release.', 'Product approved the simplified home experience for the 1.0 release.', 'N', sp_util.fix_demo_dates(sysdate - 43), upper('marcus.hale@acme.com'), sp_util.fix_demo_dates(sysdate - 43), upper('marcus.hale@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6203, 6002, 3, 'MFA enrollment will be progressive so existing customers are not blocked at first sign-in.', 'MFA enrollment will be progressive so existing customers are not blocked at first sign-in.', 'MFA enrollment will be progressive so existing customers are not blocked at first sign-in.', 'N', sp_util.fix_demo_dates(sysdate - 40), upper('elena.vargas@acme.com'), sp_util.fix_demo_dates(sysdate - 40), upper('elena.vargas@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6204, 6002, 4, 'Security accepted the mobile session timeout and account-recovery approach.', 'Security accepted the mobile session timeout and account-recovery approach.', 'Security accepted the mobile session timeout and account-recovery approach.', 'N', sp_util.fix_demo_dates(sysdate - 38), upper('tyler.brooks@acme.com'), sp_util.fix_demo_dates(sysdate - 38), upper('tyler.brooks@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6205, 6003, 5, 'Guided intake was selected over a free-form request screen to improve routing quality.', 'Guided intake was selected over a free-form request screen to improve routing quality.', 'Guided intake was selected over a free-form request screen to improve routing quality.', 'N', sp_util.fix_demo_dates(sysdate - 35), upper('naomi.chen@acme.com'), sp_util.fix_demo_dates(sysdate - 35), upper('naomi.chen@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6206, 6003, 6, 'Operations approved the required request fields and mobile attachment limits.', 'Operations approved the required request fields and mobile attachment limits.', 'Operations approved the required request fields and mobile attachment limits.', 'N', sp_util.fix_demo_dates(sysdate - 33), upper('jordan.avery@acme.com'), sp_util.fix_demo_dates(sysdate - 33), upper('jordan.avery@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6207, 6004, 7, 'The upload flow now resumes interrupted transfers when the device reconnects.', 'The upload flow now resumes interrupted transfers when the device reconnects.', 'The upload flow now resumes interrupted transfers when the device reconnects.', 'N', sp_util.fix_demo_dates(sysdate - 30), upper('caleb.foster@acme.com'), sp_util.fix_demo_dates(sysdate - 30), upper('caleb.foster@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6208, 6004, 8, 'The team agreed to limit document capture to PDF and image formats for 1.0.', 'The team agreed to limit document capture to PDF and image formats for 1.0.', 'The team agreed to limit document capture to PDF and image formats for 1.0.', 'N', sp_util.fix_demo_dates(sysdate - 28), upper('lila.montgomery@acme.com'), sp_util.fix_demo_dates(sysdate - 28), upper('lila.montgomery@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6209, 6005, 9, 'Notification preferences were moved into one screen to avoid conflicting channel settings.', 'Notification preferences were moved into one screen to avoid conflicting channel settings.', 'Notification preferences were moved into one screen to avoid conflicting channel settings.', 'N', sp_util.fix_demo_dates(sysdate - 25), upper('andre.collins@acme.com'), sp_util.fix_demo_dates(sysdate - 25), upper('andre.collins@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6210, 6005, 10, 'Product approved deep links for request updates and billing alerts.', 'Product approved deep links for request updates and billing alerts.', 'Product approved deep links for request updates and billing alerts.', 'N', sp_util.fix_demo_dates(sysdate - 23), upper('sophie.bennett@acme.com'), sp_util.fix_demo_dates(sysdate - 23), upper('sophie.bennett@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6211, 6006, 11, 'The synchronization engine now records conflicts for customer review rather than overwriting data.', 'The synchronization engine now records conflicts for customer review rather than overwriting data.', 'The synchronization engine now records conflicts for customer review rather than overwriting data.', 'N', sp_util.fix_demo_dates(sysdate - 20), upper('victor.ramirez@acme.com'), sp_util.fix_demo_dates(sysdate - 20), upper('victor.ramirez@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6212, 6006, 12, 'The team deferred offline document downloads to a later release to protect device storage.', 'The team deferred offline document downloads to a later release to protect device storage.', 'The team deferred offline document downloads to a later release to protect device storage.', 'N', sp_util.fix_demo_dates(sysdate - 18), upper('hannah.doyle@acme.com'), sp_util.fix_demo_dates(sysdate - 18), upper('hannah.doyle@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6213, 6007, 13, 'Mobile payment initiation uses the existing processor to keep PCI scope unchanged.', 'Mobile payment initiation uses the existing processor to keep PCI scope unchanged.', 'Mobile payment initiation uses the existing processor to keep PCI scope unchanged.', 'N', sp_util.fix_demo_dates(sysdate - 15), upper('isaac.turner@acme.com'), sp_util.fix_demo_dates(sysdate - 15), upper('isaac.turner@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6214, 6007, 14, 'Finance approved the payment confirmation and reconciliation design.', 'Finance approved the payment confirmation and reconciliation design.', 'Finance approved the payment confirmation and reconciliation design.', 'N', sp_util.fix_demo_dates(sysdate - 13), upper('chloe.whitaker@acme.com'), sp_util.fix_demo_dates(sysdate - 13), upper('chloe.whitaker@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6215, 6008, 15, 'The assistant will use approved support articles and hand off low-confidence answers.', 'The assistant will use approved support articles and hand off low-confidence answers.', 'The assistant will use approved support articles and hand off low-confidence answers.', 'N', sp_util.fix_demo_dates(sysdate - 10), upper('dominic.reyes@acme.com'), sp_util.fix_demo_dates(sysdate - 10), upper('dominic.reyes@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6216, 6008, 16, 'Support leadership approved the escalation wording and customer handoff queue.', 'Support leadership approved the escalation wording and customer handoff queue.', 'Support leadership approved the escalation wording and customer handoff queue.', 'N', sp_util.fix_demo_dates(sysdate - 8), upper('maya.patel@acme.com'), sp_util.fix_demo_dates(sysdate - 8), upper('maya.patel@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6217, 6009, 17, 'Screen-reader labels and focus order are now part of the shared component acceptance criteria.', 'Screen-reader labels and focus order are now part of the shared component acceptance criteria.', 'Screen-reader labels and focus order are now part of the shared component acceptance criteria.', 'N', sp_util.fix_demo_dates(sysdate - 5), upper('ethan.caldwell@acme.com'), sp_util.fix_demo_dates(sysdate - 5), upper('ethan.caldwell@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6218, 6009, 18, 'Accessibility review confirmed the planned controls meet the mobile AA baseline.', 'Accessibility review confirmed the planned controls meet the mobile AA baseline.', 'Accessibility review confirmed the planned controls meet the mobile AA baseline.', 'N', sp_util.fix_demo_dates(sysdate - 3), upper('vanessa.cruz@acme.com'), sp_util.fix_demo_dates(sysdate - 3), upper('vanessa.cruz@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6219, 6010, 19, 'Automated device tests now run for the supported operating-system versions.', 'Automated device tests now run for the supported operating-system versions.', 'Automated device tests now run for the supported operating-system versions.', 'N', sp_util.fix_demo_dates(sysdate - 2), upper('lucas.bennett@acme.com'), sp_util.fix_demo_dates(sysdate - 2), upper('lucas.bennett@acme.com'));
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by)
  values (6220, 6010, 20, 'The release-quality gate will require performance results before code freeze.', 'The release-quality gate will require performance results before code freeze.', 'The release-quality gate will require performance results before code freeze.', 'N', sp_util.fix_demo_dates(sysdate - 1), upper('aiden.clarke@acme.com'), sp_util.fix_demo_dates(sysdate - 1), upper('aiden.clarke@acme.com'));

-- Three milestones and two reviews per project. All task dates use the demo-date helper.
insert all
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7001, 6001, 'Spec Complete', 21, null, 2, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Mobile navigation specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'MARCUS.HALE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7002, 6001, 'Demonstrable', 22, null, 2, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'App shell demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'MARCUS.HALE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7003, 6001, 'Code Complete', 23, null, 1, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 7), 11, sp_util.fix_demo_dates(sysdate - 2), 'Navigation implementation in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'SCOTT.TIGER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7004, 6001, 'Functional Spec Review', 2, null, 8, sp_util.fix_demo_dates(sysdate - 56), sp_util.fix_demo_dates(sysdate - 50), 8, sp_util.fix_demo_dates(sysdate - 50), 'Functional specification approved.', 'review,functional-spec', 15, 'Medium', sp_util.fix_demo_dates(sysdate - 58), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 50), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7005, 6001, 'User Experience Review', 10, null, 8, sp_util.fix_demo_dates(sysdate - 4), sp_util.fix_demo_dates(sysdate + 5), 4, sp_util.fix_demo_dates(sysdate - 4), 'User experience review in progress.', 'review,ux', 35, 'Medium', sp_util.fix_demo_dates(sysdate - 7), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7011, 6002, 'Spec Complete', 21, null, 4, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Mobile identity specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'TYLER.BROOKS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7012, 6002, 'Demonstrable', 22, null, 4, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Sign-in and profile flow demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'TYLER.BROOKS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7013, 6002, 'Code Complete', 23, null, 3, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 8), 11, sp_util.fix_demo_dates(sysdate - 1), 'MFA and profile work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'ELENA.VARGAS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7014, 6002, 'Security Review', 5, null, 6, sp_util.fix_demo_dates(sysdate - 10), sp_util.fix_demo_dates(sysdate + 4), 4, sp_util.fix_demo_dates(sysdate - 2), 'Mobile authentication security review in progress.', 'review,security', 35, 'High', sp_util.fix_demo_dates(sysdate - 12), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7015, 6002, 'Implementation Review', 11, null, 4, sp_util.fix_demo_dates(sysdate + 5), sp_util.fix_demo_dates(sysdate + 12), 2, sp_util.fix_demo_dates(sysdate - 3), 'Implementation review scheduled before code freeze.', 'review,implementation', 40, 'High', sp_util.fix_demo_dates(sysdate - 10), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 3), 'TYLER.BROOKS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7021, 6003, 'Spec Complete', 21, null, 6, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Request intake specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7022, 6003, 'Demonstrable', 22, null, 6, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Guided request flow demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7023, 6003, 'Code Complete', 23, null, 5, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 6), 11, sp_util.fix_demo_dates(sysdate - 2), 'Request workflow work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'NAOMI.CHEN@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7024, 6003, 'Functional Spec Review', 2, null, 10, sp_util.fix_demo_dates(sysdate - 56), sp_util.fix_demo_dates(sysdate - 50), 8, sp_util.fix_demo_dates(sysdate - 50), 'Functional specification approved.', 'review,functional-spec', 15, 'High', sp_util.fix_demo_dates(sysdate - 58), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 50), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7025, 6003, 'Functional Testing Review', 9, null, 10, sp_util.fix_demo_dates(sysdate - 3), sp_util.fix_demo_dates(sysdate + 7), 4, sp_util.fix_demo_dates(sysdate - 3), 'Functional testing review in progress.', 'review,functional-testing', 35, 'High', sp_util.fix_demo_dates(sysdate - 6), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 3), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7031, 6004, 'Spec Complete', 21, null, 8, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Capture and upload specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7032, 6004, 'Demonstrable', 22, null, 8, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Document capture demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7033, 6004, 'Code Complete', 23, null, 7, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 5), 11, sp_util.fix_demo_dates(sysdate - 1), 'Upload recovery work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'CALEB.FOSTER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7034, 6004, 'Peer Review', 4, null, 12, sp_util.fix_demo_dates(sysdate - 8), sp_util.fix_demo_dates(sysdate + 3), 4, sp_util.fix_demo_dates(sysdate - 2), 'Upload handling peer review in progress.', 'review,peer', 35, 'Medium', sp_util.fix_demo_dates(sysdate - 10), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7035, 6004, 'Functional Testing Review', 9, null, 12, sp_util.fix_demo_dates(sysdate + 2), sp_util.fix_demo_dates(sysdate + 9), 2, sp_util.fix_demo_dates(sysdate - 4), 'Upload reliability testing scheduled.', 'review,functional-testing', 40, 'Medium', sp_util.fix_demo_dates(sysdate - 7), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7041, 6005, 'Spec Complete', 21, null, 10, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Notifications specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7042, 6005, 'Demonstrable', 22, null, 10, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Notification preferences demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7043, 6005, 'Code Complete', 23, null, 9, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 5), 11, sp_util.fix_demo_dates(sysdate - 1), 'Push notification work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'ANDRE.COLLINS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7044, 6005, 'Product Management Review', 7, null, 14, sp_util.fix_demo_dates(sysdate - 56), sp_util.fix_demo_dates(sysdate - 50), 8, sp_util.fix_demo_dates(sysdate - 50), 'Notification scope approved.', 'review,product-management', 15, 'Medium', sp_util.fix_demo_dates(sysdate - 58), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 50), 'CHLOE.WHITAKER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7045, 6005, 'Implementation Review', 11, null, 10, sp_util.fix_demo_dates(sysdate + 2), sp_util.fix_demo_dates(sysdate + 9), 2, sp_util.fix_demo_dates(sysdate - 4), 'Deep link implementation review scheduled.', 'review,implementation', 40, 'Medium', sp_util.fix_demo_dates(sysdate - 7), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7051, 6006, 'Spec Complete', 21, null, 12, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Offline synchronization specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7052, 6006, 'Demonstrable', 22, null, 12, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Offline mode demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7053, 6006, 'Code Complete', 23, null, 11, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 10), 11, sp_util.fix_demo_dates(sysdate - 1), 'Conflict handling work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7054, 6006, 'Peer Review', 4, null, 16, sp_util.fix_demo_dates(sysdate - 8), sp_util.fix_demo_dates(sysdate + 4), 4, sp_util.fix_demo_dates(sysdate - 2), 'Synchronization conflict handling peer review in progress.', 'review,peer', 35, 'High', sp_util.fix_demo_dates(sysdate - 10), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7055, 6006, 'Functional Testing Review', 9, null, 16, sp_util.fix_demo_dates(sysdate + 4), sp_util.fix_demo_dates(sysdate + 12), 2, sp_util.fix_demo_dates(sysdate - 4), 'Offline test matrix scheduled.', 'review,functional-testing', 40, 'High', sp_util.fix_demo_dates(sysdate - 7), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7061, 6007, 'Spec Complete', 21, null, 14, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Mobile payments specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'CHLOE.WHITAKER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7062, 6007, 'Demonstrable', 22, null, 14, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Mobile payment flow demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'CHLOE.WHITAKER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7063, 6007, 'Code Complete', 23, null, 13, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 11), 11, sp_util.fix_demo_dates(sysdate - 1), 'Payment confirmation work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'ISAAC.TURNER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7064, 6007, 'Security Review', 5, null, 16, sp_util.fix_demo_dates(sysdate - 10), sp_util.fix_demo_dates(sysdate + 5), 4, sp_util.fix_demo_dates(sysdate - 2), 'Mobile payment security review in progress.', 'review,security', 35, 'High', sp_util.fix_demo_dates(sysdate - 12), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7065, 6007, 'Functional Testing Review', 9, null, 16, sp_util.fix_demo_dates(sysdate + 4), sp_util.fix_demo_dates(sysdate + 12), 2, sp_util.fix_demo_dates(sysdate - 4), 'Payment integration testing scheduled.', 'review,functional-testing', 40, 'High', sp_util.fix_demo_dates(sysdate - 7), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7071, 6008, 'Spec Complete', 21, null, 16, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Mobile assistant specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7072, 6008, 'Demonstrable', 22, null, 16, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Assistant experience demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7073, 6008, 'Code Complete', 23, null, 15, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 8), 11, sp_util.fix_demo_dates(sysdate - 1), 'Knowledge grounding work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'DOMINIC.REYES@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7074, 6008, 'Product Management Review', 7, null, 18, sp_util.fix_demo_dates(sysdate - 56), sp_util.fix_demo_dates(sysdate - 50), 8, sp_util.fix_demo_dates(sysdate - 50), 'Assistant scope and handoff approved.', 'review,product-management', 15, 'High', sp_util.fix_demo_dates(sysdate - 58), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 50), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7075, 6008, 'Implementation Review', 11, null, 16, sp_util.fix_demo_dates(sysdate + 2), sp_util.fix_demo_dates(sysdate + 9), 2, sp_util.fix_demo_dates(sysdate - 4), 'Support-handoff implementation review scheduled.', 'review,implementation', 40, 'High', sp_util.fix_demo_dates(sysdate - 7), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7081, 6009, 'Spec Complete', 21, null, 18, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Accessibility specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7082, 6009, 'Demonstrable', 22, null, 18, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Accessible components demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7083, 6009, 'Code Complete', 23, null, 17, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 6), 11, sp_util.fix_demo_dates(sysdate - 1), 'Accessibility implementation work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'ETHAN.CALDWELL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7084, 6009, 'Accessibility Review', 6, null, 20, sp_util.fix_demo_dates(sysdate - 8), sp_util.fix_demo_dates(sysdate + 3), 4, sp_util.fix_demo_dates(sysdate - 2), 'Mobile accessibility review in progress.', 'review,accessibility', 35, 'High', sp_util.fix_demo_dates(sysdate - 10), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'AIDEN.CLARKE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7085, 6009, 'User Experience Review', 10, null, 18, sp_util.fix_demo_dates(sysdate + 2), sp_util.fix_demo_dates(sysdate + 9), 2, sp_util.fix_demo_dates(sysdate - 4), 'Assistive interaction review scheduled.', 'review,ux', 40, 'High', sp_util.fix_demo_dates(sysdate - 7), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7091, 6010, 'Spec Complete', 21, null, 20, sp_util.fix_demo_dates(sysdate - 52), sp_util.fix_demo_dates(sysdate - 48), 14, sp_util.fix_demo_dates(sysdate - 48), 'Quality automation specification approved.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 56), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 48), 'AIDEN.CLARKE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7092, 6010, 'Demonstrable', 22, null, 20, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 25), 14, sp_util.fix_demo_dates(sysdate - 25), 'Device test dashboard demonstrated.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 34), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 25), 'AIDEN.CLARKE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7093, 6010, 'Code Complete', 23, null, 19, sp_util.fix_demo_dates(sysdate - 5), sp_util.fix_demo_dates(sysdate + 11), 11, sp_util.fix_demo_dates(sysdate - 1), 'Automation and telemetry work in progress.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 8), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 1), 'LUCAS.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7094, 6010, 'Peer Review', 4, null, 21, sp_util.fix_demo_dates(sysdate - 8), sp_util.fix_demo_dates(sysdate + 3), 4, sp_util.fix_demo_dates(sysdate - 2), 'Test automation peer review in progress.', 'review,peer', 35, 'Medium', sp_util.fix_demo_dates(sysdate - 10), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 2), 'ZOE.MATTHEWS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (7095, 6010, 'Functional Testing Review', 9, null, 21, sp_util.fix_demo_dates(sysdate + 4), sp_util.fix_demo_dates(sysdate + 12), 2, sp_util.fix_demo_dates(sysdate - 4), 'Device coverage review scheduled before code freeze.', 'review,functional-testing', 40, 'High', sp_util.fix_demo_dates(sysdate - 7), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 4), 'ZOE.MATTHEWS@ACME.COM')
select 1 from dual;

sp_globals.g_audit_this := TRUE;

exception
    when others then
        sp_globals.g_audit_this := TRUE;
end;