begin

sp_globals.g_audit_this := FALSE;

insert all
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8201,1,'Behavior Dashboard Filter Defects',2,'N',2,8,sp_util.fix_demo_dates(sysdate-27),100,1,'M','A','Fixes inconsistent dashboard filters and incorrect saved-filter restoration.','insightiq,analytics,bug-fix',6,sp_util.fix_demo_dates(sysdate-85),'MARCUS.HALE@ACME.COM',sp_util.fix_demo_dates(sysdate-25),'MARCUS.HALE@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8202,3,'Recommendation API Latency Tuning',4,'N',1,8,sp_util.fix_demo_dates(sysdate-25),100,1,'L','A','Improves existing recommendation API response times and timeout handling.','insightiq,ai,recommendations,performance',30,sp_util.fix_demo_dates(sysdate-85),'TYLER.BROOKS@ACME.COM',sp_util.fix_demo_dates(sysdate-25),'TYLER.BROOKS@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8203,3,'Forecast Confidence Band Correction',6,'N',2,8,sp_util.fix_demo_dates(sysdate-28),100,1,'M','A','Corrects confidence-band calculations in the existing demand forecasting models.','insightiq,ai,forecasting,bug-fix',30,sp_util.fix_demo_dates(sysdate-85),'JORDAN.AVERY@ACME.COM',sp_util.fix_demo_dates(sysdate-25),'JORDAN.AVERY@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8204,1,'Journey Event Deduplication',8,'N',2,8,sp_util.fix_demo_dates(sysdate-26),100,1,'M','A','Removes duplicate customer journey events and corrects conversion totals.','insightiq,customer-systems,data-quality',1,sp_util.fix_demo_dates(sysdate-85),'LILA.MONTGOMERY@ACME.COM',sp_util.fix_demo_dates(sysdate-25),'LILA.MONTGOMERY@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8205,1,'Executive Dashboard Export Fixes',10,'N',3,8,sp_util.fix_demo_dates(sysdate-25),100,1,'S','A','Fixes PDF export formatting and timezone display in executive dashboards.','insightiq,analytics,dashboards,bug-fix',6,sp_util.fix_demo_dates(sysdate-85),'SOPHIE.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-25),'SOPHIE.BENNETT@ACME.COM')
 into sp_projects (id,initiative_id,project,owner_id,active_yn,priority_id,release_id,target_complete,pct_complete,status_id,project_size,status_scale,description,tags,focus_area_id,created,created_by,updated,updated_by) values (8206,1,'Analytics Access Audit Hardening',12,'N',1,8,sp_util.fix_demo_dates(sysdate-25),100,1,'M','A','Strengthens audit-event coverage and resolves access-control edge cases.','insightiq,security,audit,bug-fix',4,sp_util.fix_demo_dates(sysdate-85),'HANNAH.DOYLE@ACME.COM',sp_util.fix_demo_dates(sysdate-25),'HANNAH.DOYLE@ACME.COM')
select 1 from dual;

insert all
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8301,8201,2,3,'Coordinates dashboard defect resolution.','project-management',sp_util.fix_demo_dates(sysdate-82),'MARCUS.HALE@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'MARCUS.HALE@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8302,8201,1,1,'Fixes filtering behavior.','analytics,development',sp_util.fix_demo_dates(sysdate-82),'MARCUS.HALE@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'MARCUS.HALE@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8303,8202,4,3,'Coordinates API performance work.','project-management',sp_util.fix_demo_dates(sysdate-82),'TYLER.BROOKS@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'TYLER.BROOKS@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8304,8202,3,1,'Tunes recommendation service.','ai,development',sp_util.fix_demo_dates(sysdate-82),'TYLER.BROOKS@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'TYLER.BROOKS@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8305,8203,6,3,'Coordinates forecasting correction.','project-management',sp_util.fix_demo_dates(sysdate-82),'JORDAN.AVERY@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'JORDAN.AVERY@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8306,8203,5,7,'Validates forecast calculations.','research,ai',sp_util.fix_demo_dates(sysdate-82),'JORDAN.AVERY@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'JORDAN.AVERY@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8307,8204,8,3,'Coordinates journey data correction.','project-management',sp_util.fix_demo_dates(sysdate-82),'LILA.MONTGOMERY@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'LILA.MONTGOMERY@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8308,8204,7,1,'Fixes event processing.','customer-systems,development',sp_util.fix_demo_dates(sysdate-82),'LILA.MONTGOMERY@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'LILA.MONTGOMERY@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8309,8205,10,3,'Coordinates export fixes.','project-management',sp_util.fix_demo_dates(sysdate-82),'SOPHIE.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'SOPHIE.BENNETT@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8310,8205,9,5,'Validates dashboard exports.','qa,analytics',sp_util.fix_demo_dates(sysdate-82),'SOPHIE.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'SOPHIE.BENNETT@ACME.COM')
 into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8311,8206,12,3,'Coordinates audit hardening.','project-management',sp_util.fix_demo_dates(sysdate-82),'HANNAH.DOYLE@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'HANNAH.DOYLE@ACME.COM') into sp_project_contributors (id,project_id,team_member_id,responsibility_id,responsibility,tags,created,created_by,updated,updated_by) values (8312,8206,11,2,'Reviews access-control architecture.','security,architecture',sp_util.fix_demo_dates(sysdate-82),'HANNAH.DOYLE@ACME.COM',sp_util.fix_demo_dates(sysdate-82),'HANNAH.DOYLE@ACME.COM')
select 1 from dual;

insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9301,8201,2,'Saved-filter restoration now uses the selected dashboard context.','Saved-filter restoration now uses the selected dashboard context.','Saved-filter restoration now uses the selected dashboard context.','N',sp_util.fix_demo_dates(sysdate-60),'MARCUS.HALE@ACME.COM',sp_util.fix_demo_dates(sysdate-60),'MARCUS.HALE@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9302,8202,4,'API timeout handling was tuned without changing recommendation behavior.','API timeout handling was tuned without changing recommendation behavior.','API timeout handling was tuned without changing recommendation behavior.','N',sp_util.fix_demo_dates(sysdate-60),'TYLER.BROOKS@ACME.COM',sp_util.fix_demo_dates(sysdate-60),'TYLER.BROOKS@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9303,8203,6,'Forecast confidence calculations were corrected and regression-tested.','Forecast confidence calculations were corrected and regression-tested.','Forecast confidence calculations were corrected and regression-tested.','N',sp_util.fix_demo_dates(sysdate-60),'JORDAN.AVERY@ACME.COM',sp_util.fix_demo_dates(sysdate-60),'JORDAN.AVERY@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9304,8204,8,'Duplicate journey events are now rejected before aggregation.','Duplicate journey events are now rejected before aggregation.','Duplicate journey events are now rejected before aggregation.','N',sp_util.fix_demo_dates(sysdate-60),'LILA.MONTGOMERY@ACME.COM',sp_util.fix_demo_dates(sysdate-60),'LILA.MONTGOMERY@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9305,8205,10,'Export formatting and timezone handling were verified with Finance.','Export formatting and timezone handling were verified with Finance.','Export formatting and timezone handling were verified with Finance.','N',sp_util.fix_demo_dates(sysdate-60),'SOPHIE.BENNETT@ACME.COM',sp_util.fix_demo_dates(sysdate-60),'SOPHIE.BENNETT@ACME.COM');
insert into sp_project_comments (id,project_id,author_id,body,body_html,body_no_images,private_yn,created,created_by,updated,updated_by) values (9306,8206,12,'Security approved the expanded analytics access audit coverage.','Security approved the expanded analytics access audit coverage.','Security approved the expanded analytics access audit coverage.','N',sp_util.fix_demo_dates(sysdate-60),'HANNAH.DOYLE@ACME.COM',sp_util.fix_demo_dates(sysdate-60),'HANNAH.DOYLE@ACME.COM');


insert into sp_tasks
 (id,project_id,task,task_type_id,task_sub_type_id,owner_id,start_date,target_complete,status_id,status_last_changed_on,description,tags,display_sequence,impact,created,created_by,updated,updated_by)
select 8400+(p.project_id-8200)*10+t.seq,p.project_id,t.task,t.task_type_id,null,p.owner_id,
 sp_util.fix_demo_dates(sysdate+t.start_offset),sp_util.fix_demo_dates(sysdate+t.complete_offset),t.status_id,sp_util.fix_demo_dates(sysdate+t.complete_offset),t.description,t.tags,t.seq*10,t.impact,sp_util.fix_demo_dates(sysdate-85),case p.owner_id when 2 then 'MARCUS.HALE@ACME.COM' when 4 then 'TYLER.BROOKS@ACME.COM' when 6 then 'JORDAN.AVERY@ACME.COM' when 8 then 'LILA.MONTGOMERY@ACME.COM' when 10 then 'SOPHIE.BENNETT@ACME.COM' when 12 then 'HANNAH.DOYLE@ACME.COM' end,sp_util.fix_demo_dates(sysdate+t.complete_offset),case p.owner_id when 2 then 'MARCUS.HALE@ACME.COM' when 4 then 'TYLER.BROOKS@ACME.COM' when 6 then 'JORDAN.AVERY@ACME.COM' when 8 then 'LILA.MONTGOMERY@ACME.COM' when 10 then 'SOPHIE.BENNETT@ACME.COM' when 12 then 'HANNAH.DOYLE@ACME.COM' end
from (select 8201 project_id,2 owner_id from dual union all select 8202,4 from dual union all select 8203,6 from dual union all select 8204,8 from dual union all select 8205,10 from dual union all select 8206,12 from dual) p
cross join (select 1 seq,'Spec Complete' task,21 task_type_id,-80 start_offset,-74 complete_offset,14 status_id,'Patch scope approved.' description,'milestone,spec' tags,cast(null as varchar2(30)) impact from dual union all select 2,'Code Complete',23,-50,-40,14,'Fix implementation complete.','milestone,code',cast(null as varchar2(30)) from dual union all select 3,'Merged',24,-38,-35,14,'Merged before code freeze.','milestone,merge',cast(null as varchar2(30)) from dual union all select 4,'Peer Review',4,-55,-48,8,'Peer review completed.','review,peer','Medium' from dual) t;

sp_globals.g_audit_this := TRUE;

exception
    when others then
        sp_globals.g_audit_this := TRUE;
end;