begin

sp_globals.g_audit_this := FALSE;

insert into sp_projects
  (id, initiative_id, project, owner_id, active_yn, priority_id, release_id,
   target_complete, pct_complete, status_id, project_size, status_scale,
   description, tags, focus_area_id, created, created_by, updated, updated_by)
values
  (1001, 1, 'Customer Hub Account Overview', 1, 'N', 2, 1,
   sp_util.fix_demo_dates(sysdate - 12), 100, 1, 'L', 'A',
   'Delivered a consolidated account dashboard with balances, service alerts, and recent activity.',
   'customer-hub,portal,account-dashboard', 1, sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SCOTT.TIGER@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1002, 1, 'Customer Hub Service Request Intake', 3, 'N', 2, 1,
   sp_util.fix_demo_dates(sysdate - 11), 100, 1, 'L', 'A',
   'Delivered guided service-request intake, attachment validation, and request-status visibility.',
   'customer-hub,service-requests,workflow', 2, sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ELENA.VARGAS@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1003, 1, 'Customer Hub Document Center', 5, 'N', 3, 1,
   sp_util.fix_demo_dates(sysdate - 14), 100, 1, 'M', 'A',
   'Delivered secure customer document access, search, and download auditing.',
   'customer-hub,documents,security', 1, sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'NAOMI.CHEN@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1004, 1, 'Customer Hub Billing and Payments', 7, 'N', 1, 1,
   sp_util.fix_demo_dates(sysdate - 10), 100, 1, 'XL', 'A',
   'Delivered invoice viewing, payment initiation, and payment-history integrations.',
   'customer-hub,billing,payments', 1, sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'CALEB.FOSTER@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1005, 3, 'Customer Hub AI Support Assistant', 9, 'N', 2, 1,
   sp_util.fix_demo_dates(sysdate - 13), 100, 1, 'XL', 'A',
   'Delivered an AI-assisted support experience with knowledge-grounded answers and handoff routing.',
   'customer-hub,ai,support', 30, sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ANDRE.COLLINS@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1006, 1, 'Customer Hub Notification Preferences', 11, 'N', 3, 1,
   sp_util.fix_demo_dates(sysdate - 15), 100, 1, 'M', 'A',
   'Delivered self-service email and SMS notification preference management.',
   'customer-hub,notifications,preferences', 2, sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VICTOR.RAMIREZ@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1007, 1, 'Customer Hub Identity and Access', 13, 'N', 1, 1,
   sp_util.fix_demo_dates(sysdate - 10), 100, 1, 'XL', 'A',
   'Delivered single sign-on, multifactor authentication, and delegated account-access controls.',
   'customer-hub,identity,security,sso', 4, sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ISAAC.TURNER@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1008, 1, 'Customer Hub Accessibility Foundation', 15, 'N', 2, 1,
   sp_util.fix_demo_dates(sysdate - 16), 100, 1, 'L', 'A',
   'Delivered reusable accessible UI components and keyboard-navigation support.',
   'customer-hub,accessibility,design-system', 3, sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'DOMINIC.REYES@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1009, 1, 'Customer Hub Analytics Instrumentation', 17, 'N', 3, 1,
   sp_util.fix_demo_dates(sysdate - 12), 100, 1, 'M', 'A',
   'Delivered privacy-aware product analytics events, dashboards, and operational monitoring.',
   'customer-hub,analytics,observability', 6, sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ETHAN.CALDWELL@ACME.COM');

insert into sp_projects (id, initiative_id, project, owner_id, active_yn, priority_id, release_id, target_complete, pct_complete, status_id, project_size, status_scale, description, tags, focus_area_id, created, created_by, updated, updated_by) values
  (1010, 1, 'Customer Hub Performance and Resilience', 19, 'N', 2, 1,
   sp_util.fix_demo_dates(sysdate - 10), 100, 1, 'L', 'A',
   'Delivered performance improvements, load testing, and resilience safeguards for peak customer traffic.',
   'customer-hub,performance,resilience,load-testing', 1, sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LUCAS.BENNETT@ACME.COM');

-- Contributor assignments: project manager, primary delivery role, and a supporting role.
insert all
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5001, 1001, 1, 3, 'Owns delivery planning and stakeholder communication.', 'project-management', sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'SCOTT.TIGER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5002, 1001, 2, 1, 'Builds account overview UI and supporting services.', 'frontend,backend', sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'SCOTT.TIGER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5003, 1001, 8, 8, 'Designs account summary information architecture.', 'ux,design', sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'SCOTT.TIGER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5004, 1002, 3, 3, 'Owns delivery planning and operations alignment.', 'project-management', sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ELENA.VARGAS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5005, 1002, 4, 1, 'Builds guided request intake and routing integration.', 'workflow,backend', sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ELENA.VARGAS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5006, 1002, 6, 5, 'Validates request flows and regression coverage.', 'qa,functional-testing', sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ELENA.VARGAS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5007, 1003, 5, 3, 'Owns document-center delivery and compliance coordination.', 'project-management', sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'NAOMI.CHEN@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5008, 1003, 6, 1, 'Builds secure document search and download capabilities.', 'search,security', sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'NAOMI.CHEN@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5009, 1003, 8, 8, 'Designs document browsing and search interactions.', 'ux,design', sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'NAOMI.CHEN@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5010, 1004, 7, 3, 'Owns billing and payment release coordination.', 'project-management', sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'CALEB.FOSTER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5011, 1004, 8, 1, 'Builds billing and payment-processor integrations.', 'payments,integration', sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'CALEB.FOSTER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5012, 1004, 10, 5, 'Validates payment and invoice acceptance paths.', 'qa,functional-testing', sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'CALEB.FOSTER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5013, 1005, 9, 3, 'Owns AI assistant delivery and support partnership.', 'project-management,ai', sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ANDRE.COLLINS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5014, 1005, 10, 1, 'Builds assistant orchestration and support handoff.', 'ai,backend', sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ANDRE.COLLINS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5015, 1005, 12, 7, 'Evaluates answer quality and knowledge coverage.', 'research,ai-quality', sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ANDRE.COLLINS@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5016, 1006, 11, 3, 'Owns notification preference delivery.', 'project-management', sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5017, 1006, 12, 1, 'Builds preference center and consent workflows.', 'notifications,backend', sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5018, 1006, 14, 8, 'Designs preference controls and consent interactions.', 'ux,design', sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5019, 1007, 13, 3, 'Owns identity and access release delivery.', 'project-management,security', sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ISAAC.TURNER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5020, 1007, 14, 1, 'Builds SSO, MFA, and delegated access controls.', 'identity,security', sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ISAAC.TURNER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5021, 1007, 16, 2, 'Reviews authentication architecture and threat controls.', 'architecture,security', sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ISAAC.TURNER@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5022, 1008, 15, 3, 'Owns accessibility foundation delivery.', 'project-management,accessibility', sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'DOMINIC.REYES@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5023, 1008, 16, 1, 'Builds reusable accessible component behavior.', 'frontend,accessibility', sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'DOMINIC.REYES@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5024, 1008, 18, 5, 'Validates accessibility and keyboard-navigation coverage.', 'qa,accessibility', sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'DOMINIC.REYES@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5025, 1009, 17, 3, 'Owns analytics instrumentation delivery.', 'project-management,analytics', sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ETHAN.CALDWELL@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5026, 1009, 18, 1, 'Builds event collection and reporting integration.', 'analytics,backend', sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ETHAN.CALDWELL@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5027, 1009, 20, 7, 'Defines analytics taxonomy and reporting questions.', 'research,analytics', sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'ETHAN.CALDWELL@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5028, 1010, 19, 3, 'Owns performance and resilience delivery.', 'project-management,reliability', sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'LUCAS.BENNETT@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5029, 1010, 20, 1, 'Builds performance improvements and resilience controls.', 'performance,backend', sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'LUCAS.BENNETT@ACME.COM')
  into sp_project_contributors (id, project_id, team_member_id, responsibility_id, responsibility, tags, created, created_by, updated, updated_by) values (5030, 1010, 21, 5, 'Validates load testing and recovery scenarios.', 'qa,performance', sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 35), 'LUCAS.BENNETT@ACME.COM')
select 1 from dual;

-- Comments are inserted oldest to newest for each project.
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2001, 1001, 1, 'The dashboard scope was reduced to the three highest-value account summary cards for the 1.0 release.', 'The dashboard scope was reduced to the three highest-value account summary cards for the 1.0 release.', 'The dashboard scope was reduced to the three highest-value account summary cards for the 1.0 release.', 'N', sp_util.fix_demo_dates(sysdate -75), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'SCOTT.TIGER@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2002, 1001, 2, 'Pilot feedback confirmed that recent activity should remain above the fold.', 'Pilot feedback confirmed that recent activity should remain above the fold.', 'Pilot feedback confirmed that recent activity should remain above the fold.', 'N', sp_util.fix_demo_dates(sysdate -32), 'MARCUS.HALE@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'MARCUS.HALE@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2003, 1002, 3, 'We selected guided intake rather than a free-form form to improve data quality and routing.', 'We selected guided intake rather than a free-form form to improve data quality and routing.', 'We selected guided intake rather than a free-form form to improve data quality and routing.', 'N', sp_util.fix_demo_dates(sysdate -75), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'ELENA.VARGAS@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2004, 1002, 4, 'Operations approved the required fields and the new status vocabulary.', 'Operations approved the required fields and the new status vocabulary.', 'Operations approved the required fields and the new status vocabulary.', 'N', sp_util.fix_demo_dates(sysdate -32), 'TYLER.BROOKS@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'TYLER.BROOKS@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2005, 1003, 5, 'Download audit events are retained for compliance reporting; previews remain out of scope for this release.', 'Download audit events are retained for compliance reporting; previews remain out of scope for this release.', 'Download audit events are retained for compliance reporting; previews remain out of scope for this release.', 'N', sp_util.fix_demo_dates(sysdate -75), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'NAOMI.CHEN@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2006, 1003, 6, 'The pilot group reported that document categories make the new search much easier to use.', 'The pilot group reported that document categories make the new search much easier to use.', 'The pilot group reported that document categories make the new search much easier to use.', 'N', sp_util.fix_demo_dates(sysdate -32), 'JORDAN.AVERY@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'JORDAN.AVERY@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2007, 1004, 7, 'Payment initiation will redirect to the existing payment processor to keep PCI scope unchanged.', 'Payment initiation will redirect to the existing payment processor to keep PCI scope unchanged.', 'Payment initiation will redirect to the existing payment processor to keep PCI scope unchanged.', 'N', sp_util.fix_demo_dates(sysdate -75), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'CALEB.FOSTER@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2008, 1004, 8, 'Finance approved the invoice and payment-history reconciliation approach.', 'Finance approved the invoice and payment-history reconciliation approach.', 'Finance approved the invoice and payment-history reconciliation approach.', 'N', sp_util.fix_demo_dates(sysdate -32), 'LILA.MONTGOMERY@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'LILA.MONTGOMERY@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2009, 1005, 9, 'The assistant uses approved support articles only and routes uncertain answers to a human support queue.', 'The assistant uses approved support articles only and routes uncertain answers to a human support queue.', 'The assistant uses approved support articles only and routes uncertain answers to a human support queue.', 'N', sp_util.fix_demo_dates(sysdate -75), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'ANDRE.COLLINS@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2010, 1005, 10, 'Support leadership accepted the confidence threshold and escalation wording.', 'Support leadership accepted the confidence threshold and escalation wording.', 'Support leadership accepted the confidence threshold and escalation wording.', 'N', sp_util.fix_demo_dates(sysdate -32), 'SOPHIE.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'SOPHIE.BENNETT@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2011, 1006, 11, 'The team consolidated notification controls into a single preference center.', 'The team consolidated notification controls into a single preference center.', 'The team consolidated notification controls into a single preference center.', 'N', sp_util.fix_demo_dates(sysdate -75), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'VICTOR.RAMIREZ@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2012, 1006, 12, 'Legal approved the consent language and SMS opt-in flow.', 'Legal approved the consent language and SMS opt-in flow.', 'Legal approved the consent language and SMS opt-in flow.', 'N', sp_util.fix_demo_dates(sysdate -32), 'HANNAH.DOYLE@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'HANNAH.DOYLE@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2013, 1007, 13, 'MFA enrollment was made progressive to avoid disrupting existing customers on first sign-in.', 'MFA enrollment was made progressive to avoid disrupting existing customers on first sign-in.', 'MFA enrollment was made progressive to avoid disrupting existing customers on first sign-in.', 'N', sp_util.fix_demo_dates(sysdate -75), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'ISAAC.TURNER@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2014, 1007, 14, 'Security approved the SSO session-timeout policy and recovery controls.', 'Security approved the SSO session-timeout policy and recovery controls.', 'Security approved the SSO session-timeout policy and recovery controls.', 'N', sp_util.fix_demo_dates(sysdate -32), 'CHLOE.WHITAKER@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'CHLOE.WHITAKER@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2015, 1008, 15, 'Keyboard navigation and focus management were implemented in the shared component library.', 'Keyboard navigation and focus management were implemented in the shared component library.', 'Keyboard navigation and focus management were implemented in the shared component library.', 'N', sp_util.fix_demo_dates(sysdate -75), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'DOMINIC.REYES@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2016, 1008, 16, 'Accessibility review confirmed the portal meets the agreed WCAG AA baseline.', 'Accessibility review confirmed the portal meets the agreed WCAG AA baseline.', 'Accessibility review confirmed the portal meets the agreed WCAG AA baseline.', 'N', sp_util.fix_demo_dates(sysdate -32), 'MAYA.PATEL@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'MAYA.PATEL@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2017, 1009, 17, 'We removed direct identifiers from event payloads and documented the approved analytics taxonomy.', 'We removed direct identifiers from event payloads and documented the approved analytics taxonomy.', 'We removed direct identifiers from event payloads and documented the approved analytics taxonomy.', 'N', sp_util.fix_demo_dates(sysdate -75), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'ETHAN.CALDWELL@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2018, 1009, 18, 'Product managers accepted the adoption dashboard and weekly reporting cadence.', 'Product managers accepted the adoption dashboard and weekly reporting cadence.', 'Product managers accepted the adoption dashboard and weekly reporting cadence.', 'N', sp_util.fix_demo_dates(sysdate -32), 'VANESSA.CRUZ@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'VANESSA.CRUZ@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2019, 1010, 19, 'Load testing validated the target concurrency level after query and cache improvements.', 'Load testing validated the target concurrency level after query and cache improvements.', 'Load testing validated the target concurrency level after query and cache improvements.', 'N', sp_util.fix_demo_dates(sysdate -75), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate -75), 'LUCAS.BENNETT@ACME.COM');
insert into sp_project_comments (id, project_id, author_id, body, body_html, body_no_images, private_yn, created, created_by, updated, updated_by) values (2020, 1010, 20, 'The service-level objectives and release rollback thresholds were approved.', 'The service-level objectives and release rollback thresholds were approved.', 'The service-level objectives and release rollback thresholds were approved.', 'N', sp_util.fix_demo_dates(sysdate -32), 'AIDEN.CLARKE@ACME.COM', sp_util.fix_demo_dates(sysdate -32), 'AIDEN.CLARKE@ACME.COM');


-- Standard release milestones, sequenced against the Customer Hub 1.0 window.
insert all
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (3001, 1001, 'Spec Complete', 21, null, 2, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'MARCUS.HALE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3002, 1001, 'Demonstrable', 22, null, 2, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Account summary demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'MARCUS.HALE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3003, 1001, 'Code Complete', 23, null, 1, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SCOTT.TIGER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3004, 1001, 'Merged', 24, null, 1, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SCOTT.TIGER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3005, 1001, 'Hosted', 25, null, 2, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'MARCUS.HALE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3006, 1001, 'Complete', 26, null, 1, sp_util.fix_demo_dates(sysdate - 12), sp_util.fix_demo_dates(sysdate - 12), 14, sp_util.fix_demo_dates(sysdate - 12), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SCOTT.TIGER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3011, 1002, 'Spec Complete', 21, null, 4, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'TYLER.BROOKS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3012, 1002, 'Demonstrable', 22, null, 4, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Request flow demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'TYLER.BROOKS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3013, 1002, 'Code Complete', 23, null, 3, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ELENA.VARGAS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3014, 1002, 'Merged', 24, null, 3, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ELENA.VARGAS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3015, 1002, 'Hosted', 25, null, 4, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'TYLER.BROOKS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3016, 1002, 'Complete', 26, null, 3, sp_util.fix_demo_dates(sysdate - 11), sp_util.fix_demo_dates(sysdate - 11), 14, sp_util.fix_demo_dates(sysdate - 11), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ELENA.VARGAS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3021, 1003, 'Spec Complete', 21, null, 6, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3022, 1003, 'Demonstrable', 22, null, 6, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Document search demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3023, 1003, 'Code Complete', 23, null, 5, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'NAOMI.CHEN@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3024, 1003, 'Merged', 24, null, 5, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'NAOMI.CHEN@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3025, 1003, 'Hosted', 25, null, 6, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3026, 1003, 'Complete', 26, null, 5, sp_util.fix_demo_dates(sysdate - 14), sp_util.fix_demo_dates(sysdate - 14), 14, sp_util.fix_demo_dates(sysdate - 14), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'NAOMI.CHEN@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3031, 1004, 'Spec Complete', 21, null, 8, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3032, 1004, 'Demonstrable', 22, null, 8, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Billing flow demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3033, 1004, 'Code Complete', 23, null, 7, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'CALEB.FOSTER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3034, 1004, 'Merged', 24, null, 7, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'CALEB.FOSTER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3035, 1004, 'Hosted', 25, null, 8, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3036, 1004, 'Complete', 26, null, 7, sp_util.fix_demo_dates(sysdate - 10), sp_util.fix_demo_dates(sysdate - 10), 14, sp_util.fix_demo_dates(sysdate - 10), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'CALEB.FOSTER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3041, 1005, 'Spec Complete', 21, null, 10, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3042, 1005, 'Demonstrable', 22, null, 10, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Assistant workflow demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3043, 1005, 'Code Complete', 23, null, 9, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ANDRE.COLLINS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3044, 1005, 'Merged', 24, null, 9, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ANDRE.COLLINS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3045, 1005, 'Hosted', 25, null, 10, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3046, 1005, 'Complete', 26, null, 9, sp_util.fix_demo_dates(sysdate - 13), sp_util.fix_demo_dates(sysdate - 13), 14, sp_util.fix_demo_dates(sysdate - 13), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ANDRE.COLLINS@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3051, 1006, 'Spec Complete', 21, null, 12, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3052, 1006, 'Demonstrable', 22, null, 12, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Preference center demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3053, 1006, 'Code Complete', 23, null, 11, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3054, 1006, 'Merged', 24, null, 11, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3055, 1006, 'Hosted', 25, null, 12, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3056, 1006, 'Complete', 26, null, 11, sp_util.fix_demo_dates(sysdate - 15), sp_util.fix_demo_dates(sysdate - 15), 14, sp_util.fix_demo_dates(sysdate - 15), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VICTOR.RAMIREZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3061, 1007, 'Spec Complete', 21, null, 14, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'CHLOE.WHITAKER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3062, 1007, 'Demonstrable', 22, null, 14, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Identity flows demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'CHLOE.WHITAKER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3063, 1007, 'Code Complete', 23, null, 13, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ISAAC.TURNER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3064, 1007, 'Merged', 24, null, 13, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ISAAC.TURNER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3065, 1007, 'Hosted', 25, null, 14, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'CHLOE.WHITAKER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3066, 1007, 'Complete', 26, null, 13, sp_util.fix_demo_dates(sysdate - 10), sp_util.fix_demo_dates(sysdate - 10), 14, sp_util.fix_demo_dates(sysdate - 10), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ISAAC.TURNER@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3071, 1008, 'Spec Complete', 21, null, 16, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3072, 1008, 'Demonstrable', 22, null, 16, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Accessible components demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3073, 1008, 'Code Complete', 23, null, 15, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'DOMINIC.REYES@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3074, 1008, 'Merged', 24, null, 15, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'DOMINIC.REYES@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3075, 1008, 'Hosted', 25, null, 16, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3076, 1008, 'Complete', 26, null, 15, sp_util.fix_demo_dates(sysdate - 16), sp_util.fix_demo_dates(sysdate - 16), 14, sp_util.fix_demo_dates(sysdate - 16), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'DOMINIC.REYES@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3081, 1009, 'Spec Complete', 21, null, 18, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3082, 1009, 'Demonstrable', 22, null, 18, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Analytics dashboards demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3083, 1009, 'Code Complete', 23, null, 17, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ETHAN.CALDWELL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3084, 1009, 'Merged', 24, null, 17, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ETHAN.CALDWELL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3085, 1009, 'Hosted', 25, null, 18, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3086, 1009, 'Complete', 26, null, 17, sp_util.fix_demo_dates(sysdate - 12), sp_util.fix_demo_dates(sysdate - 12), 14, sp_util.fix_demo_dates(sysdate - 12), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'ETHAN.CALDWELL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3091, 1010, 'Spec Complete', 21, null, 20, sp_util.fix_demo_dates(sysdate - 98), sp_util.fix_demo_dates(sysdate - 90), 14, sp_util.fix_demo_dates(sysdate - 90), 'Approved functional and technical design.', 'milestone,spec', 10, null, sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'AIDEN.CLARKE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3092, 1010, 'Demonstrable', 22, null, 20, sp_util.fix_demo_dates(sysdate - 76), sp_util.fix_demo_dates(sysdate - 72), 14, sp_util.fix_demo_dates(sysdate - 72), 'Performance test results demonstrated to stakeholders.', 'milestone,demo', 20, null, sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'AIDEN.CLARKE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3093, 1010, 'Code Complete', 23, null, 19, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 45), 14, sp_util.fix_demo_dates(sysdate - 45), 'Implementation complete and unit tests passing.', 'milestone,code', 30, null, sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LUCAS.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3094, 1010, 'Merged', 24, null, 19, sp_util.fix_demo_dates(sysdate - 39), sp_util.fix_demo_dates(sysdate - 35), 14, sp_util.fix_demo_dates(sysdate - 35), 'Changes merged to the release branch.', 'milestone,merge', 40, null, sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LUCAS.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3095, 1010, 'Hosted', 25, null, 20, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 20), 14, sp_util.fix_demo_dates(sysdate - 20), 'Deployed to the production hosting environment.', 'milestone,hosting', 50, null, sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'AIDEN.CLARKE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by) values (3096, 1010, 'Complete', 26, null, 19, sp_util.fix_demo_dates(sysdate - 10), sp_util.fix_demo_dates(sysdate - 10), 14, sp_util.fix_demo_dates(sysdate - 10), 'Release scope accepted.', 'milestone,complete', 60, null, sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LUCAS.BENNETT@ACME.COM')
select 1 from dual;

-- Completed reviews are also represented as tasks.  Status ID 8 is the supplied
-- review status value for Completed.
insert all
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4001, 1001, 'Account Overview Functional Spec Review', 2, null, 8, sp_util.fix_demo_dates(sysdate - 88), sp_util.fix_demo_dates(sysdate - 84), 8, sp_util.fix_demo_dates(sysdate - 84), 'Functional specification approved with the account-card scope decision.', 'review,functional-spec', 15, 'Medium', sp_util.fix_demo_dates(sysdate - 100), 'SCOTT.TIGER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4002, 1002, 'Service Request Spec Review', 3, null, 6, sp_util.fix_demo_dates(sysdate - 86), sp_util.fix_demo_dates(sysdate - 80), 8, sp_util.fix_demo_dates(sysdate - 80), 'Request data model and routing rules approved.', 'review,spec', 15, 'High', sp_util.fix_demo_dates(sysdate - 100), 'ELENA.VARGAS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4003, 1003, 'Document Center Peer Review', 4, null, 6, sp_util.fix_demo_dates(sysdate - 50), sp_util.fix_demo_dates(sysdate - 44), 8, sp_util.fix_demo_dates(sysdate - 44), 'Peer review completed for secure document retrieval and audit events.', 'review,peer', 35, 'Medium', sp_util.fix_demo_dates(sysdate - 100), 'NAOMI.CHEN@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'JORDAN.AVERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4004, 1004, 'Billing and Payments Security Review', 5, null, 8, sp_util.fix_demo_dates(sysdate - 48), sp_util.fix_demo_dates(sysdate - 42), 8, sp_util.fix_demo_dates(sysdate - 42), 'Security controls accepted with payment processing remaining external.', 'review,security', 35, 'High', sp_util.fix_demo_dates(sysdate - 100), 'CALEB.FOSTER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'LILA.MONTGOMERY@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4005, 1005, 'AI Support Assistant Product Management Review', 7, null, 10, sp_util.fix_demo_dates(sysdate - 55), sp_util.fix_demo_dates(sysdate - 49), 8, sp_util.fix_demo_dates(sysdate - 49), 'Product management approved knowledge grounding and human handoff behavior.', 'review,product-management,ai', 25, 'High', sp_util.fix_demo_dates(sysdate - 100), 'ANDRE.COLLINS@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'SOPHIE.BENNETT@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4006, 1006, 'Notification Preferences Documentation Review', 8, null, 12, sp_util.fix_demo_dates(sysdate - 30), sp_util.fix_demo_dates(sysdate - 24), 8, sp_util.fix_demo_dates(sysdate - 24), 'Consent language and customer help content approved.', 'review,documentation', 45, 'Medium', sp_util.fix_demo_dates(sysdate - 100), 'VICTOR.RAMIREZ@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'HANNAH.DOYLE@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4007, 1007, 'Identity and Access Security Review', 5, null, 16, sp_util.fix_demo_dates(sysdate - 49), sp_util.fix_demo_dates(sysdate - 43), 8, sp_util.fix_demo_dates(sysdate - 43), 'Threat model, MFA, and recovery controls approved.', 'review,security,identity', 35, 'High', sp_util.fix_demo_dates(sysdate - 100), 'ISAAC.TURNER@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'MAYA.PATEL@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4008, 1008, 'Accessibility Foundation Accessibility Review', 6, null, 18, sp_util.fix_demo_dates(sysdate - 47), sp_util.fix_demo_dates(sysdate - 4), 8, sp_util.fix_demo_dates(sysdate - 41), 'Shared components validated against the agreed accessibility baseline.', 'review,accessibility', 35, 'High', sp_util.fix_demo_dates(sysdate - 100), 'DOMINIC.REYES@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4009, 1009, 'Analytics Instrumentation Functional Testing Review', 9, null, 18, sp_util.fix_demo_dates(sysdate - 25), sp_util.fix_demo_dates(sysdate - 19), 8, sp_util.fix_demo_dates(sysdate - 19), 'Event payloads, dashboard totals, and privacy controls validated.', 'review,functional-testing,analytics', 55, 'Medium', sp_util.fix_demo_dates(sysdate - 100), 'ETHAN.CALDWELL@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'VANESSA.CRUZ@ACME.COM')
  into sp_tasks (id, project_id, task, task_type_id, task_sub_type_id, owner_id, start_date, target_complete, status_id, status_last_changed_on, description, tags, display_sequence, impact, created, created_by, updated, updated_by)
    values (4010, 1010, 'Performance and Resilience Implementation Review', 11, null, 20, sp_util.fix_demo_dates(sysdate - 21), sp_util.fix_demo_dates(sysdate - 17), 8, sp_util.fix_demo_dates(sysdate - 17), 'Load test results and rollback procedures approved before code freeze.', 'review,implementation,performance', 55, 'High', sp_util.fix_demo_dates(sysdate - 100), 'LUCAS.BENNETT@ACME.COM', sp_util.fix_demo_dates(sysdate - 10), 'AIDEN.CLARKE@ACME.COM')
select 1 from dual;

sp_globals.g_audit_this := TRUE;

exception
    when others then
        sp_globals.g_audit_this := TRUE;
end;