create or replace package body sp_summary_util as

-- will enhance as necessary, escaping all markdown results in unreadable content
function escape_markdown (
    p_markdown  in  clob
) return clob
IS
    v_output  clob;
BEGIN
    v_output := p_markdown;

    if v_output is null then
        return null;
    end if;

    v_output := REPLACE(v_output, '`', '\`');      -- Code
/*
    -- Escape backslash FIRST to avoid double-escaping
    v_output := REPLACE(v_output, '\', '\\');
    -- Escape markdown special characters
    v_output := REPLACE(v_output, '*', '\*');      -- Bold/Italic
    v_output := REPLACE(v_output, '_', '\_');      -- Italic/Bold
    v_output := REPLACE(v_output, '#', '\#');      -- Headers
    v_output := REPLACE(v_output, '[', '\[');      -- Links/Images
    v_output := REPLACE(v_output, ']', '\]');      -- Links/Images
    v_output := REPLACE(v_output, '(', '\(');      -- Links/Images
    v_output := REPLACE(v_output, ')', '\)');      -- Links/Images
    v_output := REPLACE(v_output, '>', '\>');      -- Blockquotes
    v_output := REPLACE(v_output, '`', '\`');      -- Code
    v_output := REPLACE(v_output, '+', '\+');      -- Lists
    v_output := REPLACE(v_output, '-', '\-');      -- Lists/Horizontal rules
    v_output := REPLACE(v_output, '!', '\!');      -- Images
    v_output := REPLACE(v_output, '|', '\|');      -- Tables
    v_output := REPLACE(v_output, '~', '\~');      -- Strikethrough
    v_output := REPLACE(v_output, '{', '\{');      -- Code blocks
    v_output := REPLACE(v_output, '}', '\}');      -- Code blocks
    v_output := REPLACE(v_output, '.', '\.');      -- Ordered lists
*/
    return v_output;
end escape_markdown;


function ai_summary_info (
    p_type  in  varchar2 )
    return clob
is
    l_info  clob := null;
begin

    if p_type = 'PROJECT' then
        l_info := '**What goes into the AI Summary?**

The AI Summaries are generated by passing &NOMENCLATURE_PROJECT. Details and a Prompt to an AI Service.  There are two types of summaries available, full summary and summary update, each with their own prompt.  The prompts ask for a summary, a risk assessment, and highlights.  The AI Service to use is configured by the Application Administrators.  Administrators also have the ability to modify the prompts.  

The &NOMENCLATURE_PROJECT. Details include all the details about a &NOMENCLATURE_PROJECT. (e.g. name, description, priority, percent complete, status, ...).  The full summary includes comments from the last 90 days, the summary update contains just the data that has changed since the last summary – and the previous summary is included for reference.
';
    elsif p_type = 'RELEASE' then
        l_info := '**What goes into the AI Summary?**

The AI Summary is generated by passing Release and &NOMENCLATURE_PROJECT. Details, grouped by Focus Area, and a Prompt to an AI Service.  The prompt asks for a summary of the release along with highlights.  The AI Service to use is configured by the Application Administrators.  Administrators also have the ability to modify the prompts.  

The Release Details include the Release Train, release type and date range.  The &NOMENCLATURE_PROJECT. Details include &NOMENCLATURE_PROJECT. Name, description, priority, and size.
';
    end if;

    return sp_util.replace_nomenclature(l_info);

end ai_summary_info;


procedure summarize_project (
    p_project_id           in  number,
    p_summary_type         in  varchar2,
    p_summary              out clob,
    p_id_to_replace        out number )
is
    l_last_priority        varchar2(4000);
    l_last_pct_complete    varchar2(4000);
    l_last_status          varchar2(4000);
    l_last_target_date     varchar2(4000);
    l_future_reviewer_cnt  number;
    x                      clob        := null;
    x2                     clob        := null;
    l_id_to_replace        number;
    l_last_summary         date;
    l_first_yn             varchar2(1) := 'Y';
begin

for c1 in (
    select p.id project_id,
           p.project name,
           p.description,
           a.area||' / '||i.initiative area_initiative,
           case when tm.id is null then 'No Owner' else tm.first_name||' '||tm.last_name end owner,
           p.project_size,
           nvl((select 'P'||priority from sp_project_priorities pp where pp.id = p.priority_id),'Not Prioritized') priority,
           (select max(changed_on) 
              from sp_project_history
             where project_id = p.id
               and attribute_column = 'PRIORITY'
               and change_type = 'UPDATE') last_priority_update,
           p.PCT_COMPLETE||'%' percent_complete,
           (select max(changed_on) 
              from sp_project_history
             where project_id = p.id
               and attribute_column = 'PCT_COMPLETE'
               and change_type = 'UPDATE') last_pct_complete_update,
           case when p.pct_complete >= s.min_pc_for_status 
                 and p.pct_complete != 100
                then nvl((select status from sp_project_statuses where id = p.status_id),'Not Set')
                else 'NA'
                end status,
           (select max(changed_on) 
              from sp_project_history
             where project_id = p.id
               and attribute_column = 'STATUS'
               and change_type = 'UPDATE') last_status_update,
           lower(p.tags) tags,
           nvl((select focus_area from sp_initiative_focus_areas where id = p.focus_area_id),'Not Identified') focus_area,
           case when p.target_complete is null then 'Not Set'
                else to_char(p.target_complete,'DD-Mon-YYYY')
                end target_completion_date,
           (select max(changed_on) 
              from sp_project_history
             where project_id = p.id
               and attribute_column = 'TARGET_COMPLETE'
                and change_type = 'UPDATE') last_target_complete_update,
           (select count(distinct app_user)
              from sp_proj_interactions_log
             where project_id = p.id
               and page_rendered >= sysdate-30) views_last_30_days,
           (select count(distinct app_user)
              from sp_proj_interactions_log
             where page_rendered >= sysdate-30) overall_views_last_30_days,
           p.requires_reviews_yn,
           p.initiative_id
      from sp_projects p,
           sp_initiatives i,
           sp_areas a,
           sp_project_scales s,
           sp_team_members tm
     where p.id = p_project_id
       and p.archived_yn = 'N'
       and p.duplicate_of_project_id is null
       and p.initiative_id = i.id
       and i.area_id = a.id
       and i.status_scale = s.scale_letter
       and p.owner_id = tm.id (+)
) loop

    if c1.last_priority_update is not null then
       select old_value
         into l_last_priority
         from sp_project_history
        where project_id = p_project_id
          and attribute_column = 'PRIORITY'
          and change_type = 'UPDATE'
          and changed_on = c1.last_priority_update;
    end if;

    if c1.last_pct_complete_update is not null then
       select old_value
         into l_last_pct_complete
         from sp_project_history
        where project_id = p_project_id
          and attribute_column = 'PCT_COMPLETE'
          and change_type = 'UPDATE'
          and changed_on = c1.last_pct_complete_update;
    end if;

    if c1.last_status_update is not null then
       select old_value
         into l_last_status
         from sp_project_history
        where project_id = p_project_id
          and attribute_column = 'STATUS'
          and change_type = 'UPDATE'
          and changed_on = c1.last_status_update;
    end if;

    if c1.last_target_complete_update is not null then
       select old_value
         into l_last_target_date
         from sp_project_history
        where project_id = p_project_id
          and attribute_column = 'TARGET_COMPLETE'
          and change_type = 'UPDATE'
          and changed_on = c1.last_target_complete_update;
    end if;

    x := '#### Project '||c1.name||chr(10)||
            'description: '||chr(10)||c1.description||chr(10)||
            case when c1.area_initiative is not null then
                'area initiative: '||c1.area_initiative||chr(10) end ||
            'owner: '||c1.owner||chr(10)||
            'size: '||c1.project_size||chr(10)||
            'priority: '||c1.priority||case when c1.last_priority_update is not null 
                                            then ', set '||to_char(c1.last_priority_update,'DD-Mon-YYYY')
                                            end ||
                                       case when l_last_priority is not null
                                            then ', prior value was '||l_last_priority
                                            end ||chr(10)||
            'percent complete: '||c1.percent_complete||case when c1.last_pct_complete_update is not null 
                                                            then ', set '||to_char(c1.last_pct_complete_update,'DD-Mon-YYYY')
                                                            end ||
                                                       case when l_last_pct_complete is not null
                                                            then ', prior value was '||l_last_pct_complete
                                                            end ||chr(10)||
            case when c1.status != 'NA' 
                 then 'status: '||c1.status||case when c1.last_status_update is not null 
                                                  then ', set '||to_char(c1.last_status_update,'DD-Mon-YYYY')
                                                  end ||
                                             case when l_last_status is not null
                                                  then ', prior value was '||l_last_status
                                                  end ||chr(10)
                 end ||
            case when c1.tags is not null then
                'tags: '||c1.tags||chr(10) end ||
            case when c1.focus_area is not null then
                'focus area: '||c1.focus_area||chr(10) end ||
            'target completion date: '||c1.target_completion_date||case when c1.last_target_complete_update is not null 
                                                                        then ', set '||to_char(c1.last_target_complete_update,'DD-Mon-YYYY')
                                                                        end ||
                                                                   case when l_last_target_date is not null
                                                                        then ', prior value was '||l_last_target_date
                                                                        end ||chr(10)||
            'distinct user views: '||c1.views_last_30_days||' users viewed in the last 30 days (out of '||c1.overall_views_last_30_days||' total)'||chr(10);

    -- if last summary is of the same type and within the threshold to replace
    --    set p_id_to_replace so it can be removed and pass the summary before that (only for update) 
    for c2 in (
        select id, created, summary_type, risk, summary,
               case when p_summary_type = 'update'
                    then (select max(created)
                            from sp_project_ai_summaries
                           where project_id = p_project_id
                             and summary is not null
                             and created < s.created)
                    end previous_created
          from sp_project_ai_summaries s
         where project_id = p_project_id
           and summary is not null  -- excludes those ending in error
         order by created desc
    ) loop
        if p_summary_type = c2.summary_type and
           c2.created > sysdate - g_hrs_to_replace/24 
        then
            p_id_to_replace := c2.id;

            for c3 in (
                select created, summary_type, risk, summary
                  from sp_project_ai_summaries s
                 where project_id = p_project_id
                   and created = c2.previous_created
            ) loop
                   l_last_summary := c3.created;
                   x2 := '##### Last Summary'||chr(10);
                   x2 := x2||'risk was '||c3.risk||chr(10)||
                             c3.summary ||chr(10);
            end loop;
        else
            l_last_summary := c2.created;
            x2 := '##### Last Summary'||chr(10);
            x2 := x2||'risk was '||c2.risk||chr(10)||
                      c2.summary ||chr(10);
        end if;

        exit;  -- to get just the latest
    end loop;

    if x2 is not null then
        sys.dbms_lob.append(x, x2);
        x2 := null;
    end if;

    -- CONTRIBUTORS
    for c2 in (
        select t.first_name||' '||t.last_name name,
               (select resource_type from SP_RESOURCE_TYPES r where r.id = c.responsibility_id) responsibility,
               c.responsibility comments,
               c.tags
          from sp_project_contributors c,
               sp_team_members t
         where c.project_id = c1.project_id
           and c.team_member_id = t.id
           and ( (p_summary_type = 'update' and c.updated > nvl(l_last_summary,c.updated-1)) or
                  p_summary_type = 'full')
         order by 2
    ) loop

      if l_first_yn = 'Y' and p_summary_type = 'full' then
         x2 := '##### Contributors'||chr(10);
      elsif l_first_yn = 'Y' and p_summary_type = 'update' then
         x2 := '##### Contributor Changes'||chr(10);
      end if; 

      x2 := x2||'* '||c2.name||', '||c2.responsibility||
                      case when c2.comments is not null
                           then '('||c2.comments||')' end ||
                      case when c2.tags is not null 
                           then '-'||c2.tags end ||chr(10);

      l_first_yn := 'N';
    end loop;

    if x2 is not null then
       x2 := x2||chr(10);
    else
       if p_summary_type = 'full' then
           x2 := '##### Contributors'||chr(10)||'* None'||chr(10);
       elsif p_summary_type = 'update' then
           x2 := '##### Contributor Changes'||chr(10)||'* None'||chr(10);
       end if;
    end if;

    sys.dbms_lob.append(x, x2);
    x2 := null;

    l_first_yn := 'Y';

    -- MILESTONES
    for c2 in (
        select r.id milestone_id,
               t.task_type name,
               nvl((select case when first_name is not null or last_name is not null
                                then first_name||' '||last_name
                                else email
                                end
                      from sp_team_members t where t.id = r.owner_id),'None') owner,
               case when length(r.description) > 500
                    then substr(r.description,1,500)||'...'
                    else r.description
                    end description,
               (select status from sp_task_statuses where id = r.status_id) status,
               to_char(r.start_date,'DD-Mon-YYYY') start_date,
               to_char(r.target_complete,'DD-Mon-YYYY') target_complete
          from sp_tasks r,
               sp_task_types t
         where project_id = c1.project_id
           and nvl(r.task_sub_type_id,r.task_type_id) = t.id
           and t.static_id like 'MILESTONE%'
           and ( (p_summary_type = 'update' and r.updated > nvl(l_last_summary,r.updated-1)) or
                  p_summary_type = 'full')
         order by t.display_seq
    ) loop

      if l_first_yn = 'Y' and p_summary_type = 'full' then
         x2 := '##### Milestones'||chr(10);
      elsif l_first_yn = 'Y' and p_summary_type = 'update' then
         x2 := '##### Milestone Changes'||chr(10);
      end if; 

      x2 := x2||'* **'||c2.name||'**'||', owner: '||c2.owner||', status of '||c2.status||
            case when c2.description is not null
                 then ' ('||c2.description||'), '
                 else ', '
                 end ||
            case when c2.start_date is not null and c2.target_complete is not null
                 then c2.start_date||'-'||c2.target_complete
                 when c2.start_date is not null
                 then 'start of '||c2.start_date||' with no target completion'
                 when c2.target_complete is not null
                 then 'target complete of '||c2.target_complete
                 else 'no target date provided'
                 end ||chr(10);

      -- MILESTONE COMMENTS
      for c3 in (
          select * from
          (
            select tm.first_name || ' ' || tm.last_name user_name,
                   pc.body_no_images comment_text,
                   pc.created,
                   row_number( ) over (partition by pc.task_id order by pc.created desc) last_added
              from sp_task_comments pc, 
                   sp_team_members tm
            where pc.author_id = tm.id (+)
              and pc.task_id = c2.milestone_id
              and nvl(pc.private_yn,'N') = 'N'
              and ( (p_summary_type = 'full' and pc.created > sysdate-90) or
                     pc.created >= nvl(l_last_summary,pc.updated-1) )
          )
          where last_added <= 3
          order by created desc
      ) loop

        x2 := x2||'    * comment added by '||c3.user_name||' on '||to_char(c3.created,'DD-Mon-YYYY')||chr(10)||
                         c3.comment_text||chr(10);

      end loop;

      l_first_yn := 'N';
    end loop;

    if x2 is not null then
       x2 := x2||chr(10);
    else
       if p_summary_type = 'full' then
          x2 := '##### Milestones'||chr(10)||'* None'||chr(10);
       elsif p_summary_type = 'update' then
          x2 := '##### Milestone Changes'||chr(10)||'* None'||chr(10);
       end if;
    end if;

    sys.dbms_lob.append(x, x2);
    x2 := null;

    l_first_yn := 'Y';

    -- REVIEWS
    for c2 in (
        select r.id review_id,
               t.task_type name,
               nvl((select case when first_name is not null or last_name is not null
                                then first_name||' '||last_name
                                else email
                                end
                      from sp_team_members t where t.id = r.owner_id),'None') owner,
               case when length(r.description) > 500
                    then substr(r.description,1,500)||'...'
                    else r.description
                    end description,
               (select status from sp_task_statuses where id = r.status_id) status,
               r.impact,
               r.start_date,
               r.target_complete
          from sp_tasks r,
               sp_task_types t
         where project_id = c1.project_id
           and nvl(r.task_sub_type_id,r.task_type_id) = t.id
           and t.static_id like 'REVIEW%'
           and ( (p_summary_type = 'update' and r.updated > nvl(l_last_summary,r.updated-1)) or
                  p_summary_type = 'full')
         order by t.display_seq
    ) loop

      if l_first_yn = 'Y' and p_summary_type = 'full' then
         x2 := '##### Reviews'||chr(10);
      elsif l_first_yn = 'Y' and p_summary_type = 'update' then
         x2 := '##### Review Changes'||chr(10);
      end if; 

      x2 := x2||'* **'||c2.name||'**'||
            case when c2.impact is not null
                 then ', '|| c2.impact ||' impact'
                 end ||
            ', owner: '||c2.owner||', status of '||c2.status||
            case when c2.description is not null
                 then ' ('||c2.description||'), '
                 else ', '
                 end ||
            case when c2.start_date is not null and c2.target_complete is not null
                 then c2.start_date||'-'||c2.target_complete
                 when c2.start_date is not null
                 then 'start of '||c2.start_date||' with no target completion'
                 when c2.target_complete is not null
                 then 'target complete of '||c2.target_complete
                 else 'no target date provided'
                 end ||chr(10);

      -- REVIEW COMMENTS
      for c3 in (
          select * from
          (
            select tm.first_name || ' ' || tm.last_name user_name,
                   pc.body_no_images comment_text,
                   pc.created,
                   row_number( ) over (partition by pc.task_id order by pc.created desc) last_added
              from sp_task_comments pc, 
                   sp_team_members tm
            where pc.author_id = tm.id (+)
              and pc.task_id = c2.review_id
              and nvl(pc.private_yn,'N') = 'N'
              and ( (p_summary_type = 'full' and pc.created > sysdate-90) or
                     pc.created >= nvl(l_last_summary,pc.created-1) )
          )
          where last_added <= 3
          order by created desc
      ) loop

        x2 := x2||'    * comment added by '||c3.user_name||' on '||to_char(c3.created,'DD-Mon-YYYY')||chr(10)||
                         c3.comment_text||chr(10);
      end loop;

      l_first_yn := 'N';
    end loop;

    if x2 is not null then
       x2 := x2||chr(10);
    elsif nvl(c1.requires_reviews_yn,'Y') = 'Y' then
       if p_summary_type = 'full' then
          x2 := '##### Reviews'||chr(10)||'* None'||chr(10);
       elsif p_summary_type = 'update' then
         x2 := '##### Review Changes'||chr(10)||'* None'||chr(10);
       end if;
    end if;

    if x2 is not null then
       sys.dbms_lob.append(x, x2);
       x2 := null;
    end if;

    l_first_yn := 'Y';

    -- TASKS
    for c2 in (
        select r.id task_id,
               (select task_type from sp_task_types rt where rt.id = r.task_type_id)||
                case when r.task_sub_type_id is not null then ': ' end ||
               (select task_type from sp_task_types rt where rt.id = r.task_sub_type_id) ||
                case when r.task is not null then ' - '||r.task end name,
               nvl((select case when first_name is not null or last_name is not null
                                then first_name||' '||last_name
                                else email
                                end
                      from sp_team_members t where t.id = r.owner_id),'None') owner,
               case when length(r.description) > 500
                    then substr(r.description,1,500)||'...'
                    else r.description
                    end description,
               (select status from sp_task_statuses where id = r.status_id) status,
               r.start_date,
               r.target_complete
          from sp_tasks r,
               sp_task_types t
         where project_id = c1.project_id
           and nvl(r.task_sub_type_id,r.task_type_id) = t.id
           and t.static_id not like 'MILESTONE%'
           and t.static_id not like 'REVIEW%'
           and ( (p_summary_type = 'update' and r.updated > nvl(l_last_summary,r.updated-1)) or
                  p_summary_type = 'full')
         order by t.display_seq
    ) loop

      if l_first_yn = 'Y' and p_summary_type = 'full' then
         x2 := '##### Tasks'||chr(10);
      elsif l_first_yn = 'Y' and p_summary_type = 'update' then
         x2 := '##### Task Changes'||chr(10);
      end if; 

      x2 := x2||'* **'||c2.name||'**'||', owner: '||c2.owner||', status of '||c2.status||
            case when c2.description is not null
                 then ' ('||c2.description||'), '
                 else ', '
                 end ||
            case when c2.start_date is not null and c2.target_complete is not null
                 then c2.start_date||'-'||c2.target_complete
                 when c2.start_date is not null
                 then 'start of '||c2.start_date||' with no target completion'
                 when c2.target_complete is not null
                 then 'target complete of '||c2.target_complete
                 else 'no target date provided'
                 end ||chr(10);

      -- TASK COMMENTS
      for c3 in (
          select * from
          (
            select tm.first_name || ' ' || tm.last_name user_name,
                   pc.body_no_images comment_text,
                   pc.created,
                   row_number( ) over (partition by pc.task_id order by pc.created desc) last_added
              from sp_task_comments pc, 
                   sp_team_members tm
            where pc.author_id = tm.id (+)
              and pc.task_id = c2.task_id
              and nvl(pc.private_yn,'N') = 'N'
              and ( (p_summary_type = 'full' and pc.created > sysdate-90) or
                     pc.created >= nvl(l_last_summary,pc.updated-1) )
          )
          where last_added <= 3
          order by created desc
      ) loop

        x2 := x2||'    * comment added by '||c3.user_name||' on '||to_char(c3.created,'DD-Mon-YYYY')||chr(10)||
                         c3.comment_text||chr(10);

      end loop;

      l_first_yn := 'N';
    end loop;

    if x2 is not null then
       x2 := x2||chr(10);
       sys.dbms_lob.append(x, x2);
       x2 := null;
    end if;

    l_first_yn := 'Y';

    -- APPROVALS
    for c2 in (
        select a.id approval_id,
               t.approval_type,
               m.first_name||' '||m.last_name submitted_by,
               to_char(a.submitted,'DD-Mon-YYYY') submitted_on_display,
               initcap(replace(case when a.status = 'CLARIFICATION-REQUESTED' 
                                    then 'Needs Clarification' 
                                    when a.status = 'PENDING'
                                    then 'Approval Pending'
                                    else a.status 
                                    end,'-',' ')) status_display,
               a.status,
               case when a.status = 'PENDING' then 'Justification: '||a.justification
                    when a.status in ('CLARIFICATION-REQUESTED','REJECTED')
                    then (select comments from 
                                 (select comments, created, max(created) over (partition by project_approval_id) last_created
                                    from sp_project_approval_chain
                                   where a.id = project_approval_id)
                            where last_created = created)
                    end justification,
               to_char(a.updated,'DD-Mon-YYYY') last_update_display,
               case when p_summary_type = 'update' 
                    then nvl((select max(last_status_on) 
                                from sp_project_approval_chain
                               where project_approval_id = a.id),a.submitted)
                    end last_action
          from sp_project_approvals a,
               sp_approval_types t,
               sp_team_members m
         where a.project_id = c1.project_id
           and a.approval_type_id = t.id    
           and a.submitted_by_team_member_id = m.id
         order by a.submitted desc
    ) loop

      if p_summary_type = 'full' or
         (p_summary_type = 'update' and c2.last_action > nvl(l_last_summary,c2.last_action-1))
      then

         if l_first_yn = 'Y' and p_summary_type = 'full' then
            x2 := '##### Approvals'||chr(10);
         elsif l_first_yn = 'Y' and p_summary_type = 'update' then
            x2 := '##### Approval Changes'||chr(10);
         end if; 

         x2 := x2||'* **'||c2.approval_type||'**'||', submitted by '||c2.submitted_by||' on '||c2.submitted_on_display;
         if c2.status = 'APPROVED' then
             x2 := x2||', Received Final Approval on '||c2.last_update_display||chr(10);
         elsif c2.status = 'WITHDRAWN' then
             x2 := x2||', Withdrawn on '||c2.last_update_display||chr(10);
         elsif c2.status = 'REJECTED' then
             x2 := x2||', Rejected on '||c2.last_update_display||chr(10);
         else
             x2 := x2||', status is '||c2.status_display||chr(10);
             x2 := x2||'    * '||c2.justification||chr(10);

             -- current and past approvers
             for c3 in (
                 select to_char(c.last_status_on,'DD-Mon-YYYY') comment_date,
                        t.first_name ||' '|| t.last_name user_name,
                        initcap(replace(decode(c.status,'PENDING','Pending Approval'),'-',' ')) status,
                        c.comments,
                        case when c.response_by_team_member_id is not null
                             then c.response||chr(10)||'By: '||(select first_name ||' '|| last_name from sp_team_members
                                                                 where id = c.response_by_team_member_id) ||
                                  ', '|| to_char(c.responded_on,'DD-Mon-YYYY')
                             end response,
                        c.last_status_on ob_date
                   from sp_project_approval_chain c,
                        sp_team_members t
                  where c.project_approval_id = c2.approval_id
                    and c.team_member_id = t.id
                 order by ob_date asc
             ) loop
                 x2 := x2||'    * '|| c3.user_name ||' '|| c3.status ||', '|| c3.comment_date ||chr(10);
                 if c3.comments is not null then
                    x2 := x2||'      Comments: '||c3.comments||chr(10);
                 end if;
                 if c3.response is not null then
                    x2 := x2||'      Response: '||c3.response||chr(10);
                 end if;
             end loop;

             -- future approvers
             select count(*)
               into l_future_reviewer_cnt
               from sp_initiative_approval_chain c,
                    sp_project_approvals a
              where a.id = c2.approval_id
                and a.initiative_approval_id = c.initiative_approval_id
                and c.id not in (select initiative_approval_chain_id
                                   from sp_project_approval_chain
                                  where project_approval_id = c2.approval_id);

             for c3 in (
                 select rownum, reviewer
                   from (
                 select case when c.alternate_team_member_id is not null and   
                                  (c.alternate_start_date <= sysdate or c.alternate_start_date is null) and 
                                  (c.alternate_end_date+1 > sysdate or c.alternate_end_date is null)
                             then 'Alternate - '||
                                  (select last_name||', '||first_name
                                     from sp_team_members
                                    where id = c.alternate_team_member_id)
                             else t.last_name||', '||t.first_name 
                             end reviewer
                   from sp_initiative_approval_chain c,
                        sp_project_approvals a,
                        sp_team_members t
                  where a.id = c2.approval_id
                    and a.initiative_approval_id = c.initiative_approval_id
                    and c.team_member_id = t.id
                    and c.id not in (select initiative_approval_chain_id
                                       from sp_project_approval_chain
                                      where project_approval_id = c2.approval_id)
                  order by c.approval_seq
                  )
             ) loop
                 x2 := x2||'    * '|| c3.reviewer;
                 if c3.rownum = l_future_reviewer_cnt then
                    x2 := x2||', final reviewer'||chr(10);
                 elsif c3.rownum = 1 then
                    x2 := x2||', next reviewer'||chr(10);
                 else
                    x2 := x2||chr(10);
                 end if;
              
             end loop;

         end if;
      
         l_first_yn := 'N';

       end if;

    end loop;

    -- APPROVALS NOT YET REQUESTED
    for c2 in (
        select t.approval_type
          from SP_INITIATIVE_APPROVALS a,
               sp_approval_types t
         where a.initiative_id = c1.initiative_id
           and a.approval_type_id = t.id
           and a.active_yn = 'Y'
           and t.active_yn = 'Y'
           and a.id not in (select initiative_approval_id
                              from sp_project_approvals
                             where project_id = c1.project_id)
        order by t.display_seq
    ) loop
        -- if no approvals yet, need to include the heading
        if l_first_yn = 'Y' then
            x2 := x2||'##### Approvals'||chr(10);
            l_first_yn := 'N';
        end if;
        x2 := x2||'* **'||c2.approval_type||'**'||', not yet requested'||chr(10);
    end loop;

    if x2 is not null then
       x2 := x2||chr(10);
       sys.dbms_lob.append(x, x2);
       x2 := null;
    end if;


    l_first_yn := 'Y';

    -- COMMENTS
    for c2 in (
        select * from
        (
        select tm.first_name || ' ' || tm.last_name user_name,
               pc.body_no_images comment_text,
               pc.created,
               row_number( ) over (partition by pc.project_id order by pc.created desc) last_added
          from sp_project_comments pc, 
               sp_team_members tm
        where pc.author_id = tm.id (+)
          and pc.project_id = c1.project_id
          and nvl(pc.private_yn,'N') = 'N'
          and ( (p_summary_type = 'full' and pc.created > sysdate-90) or
                 pc.created >=  nvl(l_last_summary,pc.updated-1) )
        )
        where last_added <= 10
        order by created desc
    ) loop

      if l_first_yn = 'Y' then
         x2 := '##### Most Recent Comments'||chr(10);
      end if; 

      x2 := x2||'* comment added by '||c2.user_name||' on '||to_char(c2.created,'DD-Mon-YYYY')||chr(10)||
                   c2.comment_text||chr(10);

      l_first_yn := 'N';
    end loop;

    if x2 is not null then
       x2 := x2||chr(10);
       sys.dbms_lob.append(x, x2);
       x2 := null;
    end if;

    l_first_yn := 'Y';

end loop;

p_summary := x;

exception
    when others then
        sp_util.add_error_log (
            p_package_name   => 'sp_summary_util',
            p_procedure_name => 'summarize_project', 
            p_error          => sqlerrm, 
            p_arg1_name      => 'p_project_id',   p_arg1_val => p_project_id, 
            p_arg2_name      => 'p_summary_type', p_arg2_val => p_summary_type );
end summarize_project;


-- can be run from APEX App UI (not SQL Commands) or from within a job (if session context is set)
procedure generate_project_summary (
    p_project_id    in   number,
    p_summary_type  in   varchar2,
    p_ai_id         out  number,
    p_error_yn      out  varchar2 )
as
    l_system_prompt    clob;
    l_project_details  clob;
    l_id_to_replace    number;
    l_ai_service       varchar2(60);
    l_ai_sum           clob;
    l_json_values      apex_json.t_values;
    l_summary          clob;
    l_highlights       varchar2(4000);
    l_risk             varchar2(100);
begin

    p_error_yn := 'N';

    -- add in today's date
    l_system_prompt := 'Today is '|| to_char(sysdate,'DD-Mon-YYYY')||chr(10);

    if p_summary_type = 'full' then
       l_system_prompt := l_system_prompt||chr(10)||sp_util.get_ai_prompt (p_static_id => 'PROJECT_FULL_SUMMARY');
    elsif p_summary_type = 'update' then
       l_system_prompt := l_system_prompt||chr(10)||sp_util.get_ai_prompt (p_static_id => 'PROJECT_UPDATE_SUMMARY');
    end if;

    summarize_project (
        p_project_id    => p_project_id,
        p_summary_type  => p_summary_type,
        p_summary       => l_project_details,
        p_id_to_replace => l_id_to_replace );

    if l_project_details is not null then

        insert into sp_project_ai_summaries
            (project_id, summary_type, prompt_sent, details_sent)
        values 
            (p_project_id, p_summary_type, l_system_prompt, l_project_details)
        returning id into p_ai_id;
        commit;

        l_ai_service := sp_util.get_setting (p_static_id => 'SUMMARY_AI_SERVICE');

        if l_ai_service is not null and
           apex_application_admin.get_build_option_status (
               p_application_id    => sp_util.get_setting (p_static_id => 'APP_ID'),
               p_build_option_name => 'AI Project Summaries' ) = 'INCLUDE'
        then

            -- wrapping to continue if ai error
            begin
                l_ai_sum := apex_ai.generate (
                                p_prompt            => 'Summarize the following project updates: ' || escape_markdown(l_project_details),
                                p_system_prompt     => l_system_prompt,
                                p_service_static_id => l_ai_service ); 

                -- store date_received in case the json parse fails
                update sp_project_ai_summaries
                   set data_received = l_ai_sum
                 where id = p_ai_id;
                 commit;

                apex_json.parse(p_values => l_json_values, p_source => l_ai_sum);
                l_summary    := apex_json.get_clob(p_values => l_json_values, p_path => 'summary');
                l_risk       := apex_json.get_varchar2(p_values => l_json_values, p_path => 'risk');

                -- extract the highlights as a list
                for c2 in (
                    select highlights.*
                      from dual, 
                           json_table (l_ai_sum, '$.highlights[*]' 
                                       columns (highlight varchar2(1000) path '$')) highlights
                ) loop
                    l_highlights := l_highlights || '<li>' || c2.highlight || '</li>';
                end loop;
    
                update sp_project_ai_summaries
                   set summary = l_summary,
                       risk = l_risk,
                       highlights = '<ul>'||l_highlights||'</ul>'
                 where id = p_ai_id;
                 commit;

                -- remove previous summary as it is being replaced (generated within the g_hrs_to_replace window)
                if l_id_to_replace is not null then
                   delete from sp_project_ai_summaries
                    where id = l_id_to_replace;
                end if;

            exception 
                when others then 
                    p_error_yn := 'Y';
                    sp_util.add_error_log (
                        p_package_name   => 'sp_summary_util',
                        p_procedure_name => 'generate_project_summary', 
                        p_error          => sqlerrm, 
                        p_arg1_name      => 'p_project_id',   p_arg1_val => p_project_id, 
                        p_arg2_name      => 'p_summary_type', p_arg2_val => p_summary_type, 
                        p_arg3_name      => 'p_ai_id', p_arg3_val => p_ai_id );
            end;
        end if;
    else
        sp_util.add_error_log (
            p_package_name   => 'sp_summary_util',
            p_procedure_name => 'generate_project_summary', 
            p_error          => 'summarize_project_project returned without summary', 
            p_arg1_name      => 'p_project_id',   p_arg1_val => p_project_id, 
            p_arg2_name      => 'p_summary_type', p_arg2_val => p_summary_type );
    end if;

end generate_project_summary;



-- run as a job, once a week
procedure generate_project_summaries as
    l_app_id           number;
    l_summary_type     varchar2(30);
    l_ai_id            number;
    l_error_yn         varchar2(1);
    l_ai_error_cnt     number := 0;
    l_summary_cnt      number := 0;
    l_max_errors       number := 3;  -- exit when this many errors 
begin

    l_app_id := sp_util.get_setting (p_static_id => 'APP_ID');

    -- when run from a job, need a session
    for c1 in (
        select workspace, workspace_id
          from apex_applications
         where application_id = l_app_id
    ) loop
        apex_util.set_workspace (p_workspace => c1.workspace );
        apex_util.set_security_group_id(p_security_group_id => c1.workspace_id );
    end loop;

    -- if build not not enabled, nothing will be run (careful to not update build option names)
    if apex_util.get_build_option_status (
           p_application_id    => l_app_id, 
           p_build_option_name => 'AI Project Summaries') = 'INCLUDE'
    then
        apex_session.create_session (
           p_app_id   => l_app_id,
           p_page_id  => 1,
           p_username => 'AI' );

        -- get count of projects that should be summarized
        for c1 in (
            select count(*) cnt
              from
            (
            select updated,
                   (select max(created) from sp_project_ai_summaries
                     where project_id = p.id) last_summary
              from sp_projects p
             where pct_complete > 10
               and updated > sysdate-90
               and archived_yn = 'N'
               and duplicate_of_project_id is null
            )
             where last_summary is null or updated > last_summary
        ) loop
            sp_util.add_app_log (
                p_activity => 'sp_summary_util.generate_project_summaries', 
                p_details  => 'Should create '||c1.cnt||' project summaries');
        end loop;

        -- only check projects updated in the last 90 days that are more than 10% complete
        for c1 in (
            select id, updated, pct_complete,
                   (select max(created) from sp_project_ai_summaries
                     where project_id = p.id) last_summary
              from sp_projects p
             where pct_complete > 10
               and updated > sysdate-90
               and archived_yn = 'N'
               and duplicate_of_project_id is null
             order by updated desc
        ) loop

            -- only summarize if no summary yet or there has been an update since the last summary
            if c1.last_summary is null or c1.updated > c1.last_summary then

                l_summary_type := case when c1.pct_complete = 100
                                       then 'full'
                                       when c1.last_summary is null
                                       then 'full'
                                       else 'update'
                                       end;

                generate_project_summary (
                    p_project_id   => c1.id,
                    p_summary_type => l_summary_type,
                    p_ai_id        => l_ai_id,
                    p_error_yn     => l_error_yn );

                if l_error_yn = 'Y' then
                   l_ai_error_cnt := l_ai_error_cnt + 1;
                else
                   l_summary_cnt := l_summary_cnt + 1;
                end if;

                exit when l_ai_error_cnt = l_max_errors;

            end if;

        end loop;

        sp_util.add_app_log (
            p_activity => 'sp_summary_util.generate_project_summaries', 
            p_details  => 'Created '||l_summary_cnt||' project summaries');

        apex_session.delete_session;
    end if;

exception
    when others then
        sp_util.add_error_log (
            p_package_name   => 'sp_summary_util',
            p_procedure_name => 'generate_project_summaries', 
            p_error          => sqlerrm );
end generate_project_summaries;



procedure summarize_release (
    p_release_id  in   number,
    p_summary     out  clob )
is
    x             clob        := null;
    x2            clob        := null;
    l_focus_area  varchar2(60);
begin

for c1 in (
    select r.id release_id,
           r.release_train||' - '||r.release release,
           r.release_type,
           r.release_open_date, 
           r.release_target_date
      from sp_release_trains r
     where r.id = p_release_id
) loop

    x := '### Release '||c1.release||chr(10)||
            'type: '||initcap(c1.release_type)||chr(10)||
            'date range: '||to_char(c1.release_open_date,'DD-Mon-YYYY')||' to '||to_char(c1.release_target_date,'DD-Mon-YYYY')||chr(10)||
            '#### Features Included'||chr(10);

    for c2 in (
        select a.focus_area, 
               p.project, 
               p.project_size, 
               pp.description project_priority,
               dbms_lob.substr(p.description,400,1) project_desc,
               dbms_lob.getlength(p.description) desc_length
          from sp_projects p,
               sp_project_priorities pp,
               sp_initiative_focus_areas a
         where p.release_id = c1.release_id
           and p.archived_yn = 'N'
           and p.duplicate_of_project_id is null
           and p.focus_area_id = a.id (+)
           and p.priority_id = pp.id (+)
         order by a.display_sequence nulls last, a.focus_area nulls last, pp.description, p.project
    ) loop
        if nvl(c2.focus_area,'~') != nvl(l_focus_area,'~') then
           if c2.focus_area is not null then
              x2 := '##### Focus Area: '||c2.focus_area||chr(10);
           else
              x2 := '##### No Focus Area'||chr(10);
           end if;
           l_focus_area := c2.focus_area;
        end if;

        x2 := x2||'######  '||c2.project||chr(10)||
                        '  Size: '||c2.project_size||chr(10)||
                        case when c2.project_priority is not null 
                             then '  Priority: '||c2.project_priority||chr(10)
                             end ||
                        case when c2.desc_length > 0
                             then '  '||c2.project_desc||
                                  case when c2.desc_length > 400 then ' ...' end ||
                                  chr(10)
                             end;

        sys.dbms_lob.append(x, x2);
        x2 := null;
    end loop;

end loop;

p_summary := x;

exception
    when others then
        sp_util.add_error_log (
            p_package_name   => 'sp_summary_util',
            p_procedure_name => 'summarize_release', 
            p_error          => sqlerrm, 
            p_arg1_name      => 'p_release_id', p_arg1_val => p_release_id );
end summarize_release;


-- can be run from APEX App UI (not SQL Commands) or from within a job (if session context is set)
procedure generate_release_summary (
    p_release_id    in   number,
    p_error_yn      out  varchar2 )
as
    l_system_prompt    clob;
    l_release_details  clob;
    l_id_to_remove     number;
    l_ai_service       varchar2(60);
    l_ai_id            number;
    l_ai_sum           clob;
    l_json_values      apex_json.t_values;
    l_summary          clob;
    l_highlights       varchar2(4000);
begin

    p_error_yn := 'N';

    -- add in today's date
    l_system_prompt := 'Today is '|| to_char(sysdate,'DD-Mon-YYYY')||chr(10)||
                        sp_util.get_ai_prompt (p_static_id => 'RELEASE_SUMMARY');

    summarize_release (
        p_release_id    => p_release_id,
        p_summary       => l_release_details);

    if l_release_details is not null then

        for c1 in (
            select id
              from sp_release_ai_summaries
             where release_id = p_release_id
               and created > sysdate - g_hrs_to_replace/24
             order by created desc
        ) loop
            l_id_to_remove := c1.id;
            exit;  -- exit to just get the last one, in case more than one in the delete range
        end loop;

        insert into sp_release_ai_summaries
            (release_id, prompt_sent, details_sent)
        values 
            (p_release_id, l_system_prompt, l_release_details)
        returning id into l_ai_id;
        commit;

        l_ai_service := sp_util.get_setting (p_static_id => 'SUMMARY_AI_SERVICE');

        if l_ai_service is not null and
           apex_application_admin.get_build_option_status (
               p_application_id    => sp_util.get_setting (p_static_id => 'APP_ID'),
               p_build_option_name => 'AI Release Summaries' ) = 'INCLUDE'
        then

            -- wrapping to continue if ai error
            begin
                l_ai_sum := apex_ai.generate (
                                p_prompt            => 'Summarize the following product release: ' || escape_markdown(l_release_details),
                                p_system_prompt     => l_system_prompt,
                                p_service_static_id => l_ai_service ); 

                -- save data_received, in case the json parse fails
                update sp_release_ai_summaries
                   set data_received = l_ai_sum
                 where id = l_ai_id;
                 commit;

                apex_json.parse(p_values => l_json_values, p_source => l_ai_sum);
                l_summary    := apex_json.get_clob(p_values => l_json_values, p_path => 'summary');

                -- extract the highlights as a list
                for c2 in (
                    select highlights.*
                      from dual, 
                           json_table (l_ai_sum, '$.highlights[*]' 
                                       columns (highlight varchar2(1000) path '$')) highlights
                ) loop
                    l_highlights := l_highlights || '<li>' || c2.highlight || '</li>';
                end loop;
    
                update sp_release_ai_summaries
                   set summary = l_summary,
                       highlights = '<ul>'||l_highlights||'</ul>'
                 where id = l_ai_id;
                 commit;
/*
                -- remove previous summary as it is being replaced (generated within the g_hrs_to_replace window)
                if l_id_to_remove is not null then
                   delete from sp_project_ai_summaries
                    where id = l_id_to_remove;
                end if;
*/
            exception 
                when others then 
                    p_error_yn := 'Y';
                    sp_util.add_error_log (
                        p_package_name   => 'sp_summary_util',
                        p_procedure_name => 'generate_release_summary', 
                        p_error          => sqlerrm, 
                        p_arg1_name      => 'p_release_id', p_arg1_val => p_release_id, 
                        p_arg2_name      => 'l_ai_id',      p_arg2_val => l_ai_id );
            end;
        end if;

    else
        sp_util.add_error_log (
            p_package_name   => 'sp_summary_util',
            p_procedure_name => 'generate_release_summary', 
            p_error          => 'summarize_release_project returned without summary', 
            p_arg1_name      => 'p_release_id', p_arg1_val => p_release_id );
    end if;

end generate_release_summary;


end sp_summary_util;
/