create table "SAMPLE_RESTAURANT"
   ("ID" number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 12 cache 20 noorder  nocycle  nokeep  noscale  not null enable,
    "NAME" varchar2(100 char),
    "ADDRESS" varchar2(255 char),
    "RATING" varchar2(10),
    "LOGO_URL" varchar2(255 char),
    "HERO_URL" varchar2(255 char),
    "CATEGORY_ID" number,
    "CREATED" date,
    "CREATED_BY" varchar2(255 char),
    "UPDATED" date,
    "UPDATED_BY" varchar2(255 char),
    "DELIVERY_FEE" number,
    "DELIVERY_TIME" number,
     constraint "SAMPLE_RESTAURANT_PK" primary key ("ID")
  using index  enable
  );

create table "SAMPLE_RESTAURANT_CATEGORIES"
   ("ID" number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 11 cache 20 noorder  nocycle  nokeep  noscale  not null enable,
    "NAME" varchar2(100 char),
    "IMAGE_URL" varchar2(255 char),
    "CREATED" date,
    "CREATED_BY" varchar2(255 char),
    "UPDATED" date,
    "UPDATED_BY" varchar2(255 char),
     constraint "SAMPLE_RESTAURANT_CATEGORIES_PK" primary key ("ID")
  using index  enable
  );

create table "SAMPLE_RESTAURANT_ITEMS"
   ("ID" number,
    "RESTAURANT_ID" number,
    "NAME" varchar2(255 char),
    "DESCRIPTION" varchar2(4000 char),
    "RATING" varchar2(12),
    "PRICE" number, 
    "IMAGE_URL" varchar2(255 char),
    "CREATED" date,
    "CREATED_BY" varchar2(255 char),
    "UPDATED" date,
    "UPDATED_BY" varchar2(255 char),
     constraint "SAMPLE_RESTAURANT_ITEMS_PK" primary key ("ID")
  using index  enable
  );

create table "SAMPLE_RESTAURANT_ORDERS"
   ("ORDER_ID" number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 65 cache 20 noorder  nocycle  nokeep  noscale  not null enable,
    "ORDER_DATETIME" timestamp (6),
    "ORDER_STATUS" varchar2(20 char),
    "SESSION_ID" varchar2(100 CHAR),
     constraint "SAMPLE_RESTAURANT_ORDERS_PK" primary key ("ORDER_ID")
  using index  enable
  );

create table "SAMPLE_RESTAURANT_ORDER_ITEMS" 
   ("ORDER_ID" number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 65 cache 20 noorder  nocycle  nokeep  noscale  not null enable,
    "ITEM_ID" number not null enable,
    "UNIT_PRICE" number,
    "QUANTITY" number,
    "LINE_ITEM_ID" number,
    "UTENSILS" varchar2(2),
    "NOTE" varchar2(4000),
     constraint "SAMPLE_RESTAURANT_ORDER_ITEMS_PK" primary key ("ORDER_ID", "LINE_ITEM_ID")
  using index  enable
  );

create or replace editionable trigger "SAMPLE_RESTAURANT_BIU"
    before insert or update
    on "SAMPLE_RESTAURANT"
    for each row
begin
    if inserting then
        :new.created := sysdate;  
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end SAMPLE_RESTAURANT_BIU;
/
alter trigger "SAMPLE_RESTAURANT_BIU" enable;

alter table "SAMPLE_RESTAURANT_ITEMS" add constraint "SAMPLE_RESTAURANT_ITEMS_FR" foreign key ("RESTAURANT_ID")
  references "SAMPLE_RESTAURANT" ("ID") enable;

create or replace editionable trigger "SAMPLE_RESTAURANT_ITEMS_BIU"
    before insert or update
    on "SAMPLE_RESTAURANT_ITEMS"
    for each row
begin
    if inserting then
        :new.CREATED := sysdate;
        :new.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.UPDATED := sysdate;
    :new.UPDATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end "SAMPLE_RESTAURANT_ITEMS_BIU";
/
alter trigger "SAMPLE_RESTAURANT_ITEMS_BIU" enable;

alter table "SAMPLE_RESTAURANT_ORDER_ITEMS" add constraint "SAMPLE_RESTAURANT_ORDER_ITEMS_ORDER_ID_FK" foreign key ("ORDER_ID")
  references "SAMPLE_RESTAURANT_ORDERS" ("ORDER_ID") enable;
alter table "SAMPLE_RESTAURANT_ORDER_ITEMS" add constraint "SAMPLE_RESTAURANT_ORDER_ITEMS_ITEM_ID_FK" foreign key ("ITEM_ID")
  references "SAMPLE_RESTAURANT_ITEMS" ("ID") enable;