
  CREATE TABLE "EBA_DEMO_APPR_APPRAISALS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EMPNO" NUMBER NOT NULL ENABLE, 
	"PERIOD_START" DATE, 
	"PERIOD_END" DATE, 
	"APPRAISAL_DATE" DATE, 
	"ORIGINATOR" VARCHAR2(80), 
	"STATUS" VARCHAR2(15) DEFAULT 'ORIGINATED', 
	"EMP_ACHIEVEMENTS" VARCHAR2(4000), 
	"EMP_DEVELOPMENT_GOALS" VARCHAR2(4000), 
	"MGR_APPRAISAL" VARCHAR2(4000), 
	"MGR_OBJECTIVES" VARCHAR2(4000), 
	"DATE_ORIGINATED" DATE, 
	"INPUT_COMPLETED" DATE, 
	"MANAGER_COMPLETED" DATE, 
	"VP_REVIEW_DATE" DATE, 
	 CONSTRAINT "EMP_APPRAISAL_STATUS_CK" CHECK ( status in ('ORIGINATED', 'SUBMITTED','MGR_SUBMITTED', 'VP_REVIEWED','COMPLETED')) ENABLE
   ) ;

  CREATE TABLE "EBA_DEMO_APPR_APPROVERS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR), 
	"TASK_DEF_STATIC_ID" VARCHAR2(50 CHAR), 
	"JOB_CODES" VARCHAR2(50 CHAR), 
	"PARTICIPANT_ROLE" VARCHAR2(8 CHAR), 
	"MIN_SALARY" NUMBER, 
	 CONSTRAINT "APPROVERS_PARTICPANT_ROLE_CK" CHECK (participant_role='APPROVER' or participant_role='ADMIN') ENABLE, 
	 CONSTRAINT "APPROVERS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_DEMO_APPR_DEPT" 
   (	"DEPTNO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DNAME" VARCHAR2(14), 
	"LOC" VARCHAR2(13), 
	 CONSTRAINT "EBA_DEMO_APPR_DEPT_PK" PRIMARY KEY ("DEPTNO")
  USING INDEX  ENABLE
   )  ROWDEPENDENCIES ;

  CREATE TABLE "EBA_DEMO_APPR_EMP" 
   (	"EMPNO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8000 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ENAME" VARCHAR2(10), 
	"JOB" VARCHAR2(9), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER, 
	"BANK_ACCOUNT" VARCHAR2(40), 
	 CONSTRAINT "EBA_DEMO_APPR_EMP_PK" PRIMARY KEY ("EMPNO")
  USING INDEX  ENABLE
   )  ROWDEPENDENCIES ;

  CREATE TABLE "EBA_DEMO_APPR_LAPTOP_STOCK" 
   (	"LAPTOP_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"AMOUNT" NUMBER, 
	 CONSTRAINT "EBA_DEMO_APPR_LAPTOP_STOCK_LAPTOP_TYPE_PK" PRIMARY KEY ("LAPTOP_TYPE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_DEMO_APPR_SAL_HISTORY" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EMPNO" NUMBER, 
	"NEW_SAL" NUMBER, 
	"APPROVAL_DATE" DATE, 
	"OLD_SAL" NUMBER, 
	"TASK_ID" NUMBER, 
	 CONSTRAINT "EBA_DEMO_APPR_SAL_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EBA_DEMO_APPR_VACATION" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ORIGINAL_USER" VARCHAR2(30 CHAR), 
	"SUBSTITUTE_USER" VARCHAR2(30 CHAR), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"REASON" VARCHAR2(80), 
	"TASK_DEF_IDS" VARCHAR2(80) NOT NULL ENABLE, 
	 CONSTRAINT "EBA_DEMO_APPR_VACATION_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "EBA_DEMO_APPR_EMP" ADD CONSTRAINT "EBA_DEMO_APPR_WORKS_IN_DEPT" FOREIGN KEY ("DEPTNO")
	  REFERENCES "EBA_DEMO_APPR_DEPT" ("DEPTNO") ON DELETE SET NULL ENABLE;

  ALTER TABLE "EBA_DEMO_APPR_SAL_HISTORY" ADD CONSTRAINT "EBA_DEMO_APPR_SAL_EMPNO_FK" FOREIGN KEY ("EMPNO")
	  REFERENCES "EBA_DEMO_APPR_EMP" ("EMPNO") ON DELETE CASCADE ENABLE;
create or replace PACKAGE "EBA_DEMO_APPR" as
    --
    -- Return the approver username for Job Change task
    --
    function get_approver_for(
        p_task_def_static_id in varchar2,
        p_empno              in number,
        p_job                in varchar2,
        p_proposed_sal       in number)
        return                  varchar2;

    --
    -- Return the business admin username for Job Change task
    --
    function get_admin_for(
        p_task_def_static_id in varchar2,
        p_empno              in number,
        p_job                in varchar2,
        p_proposed_sal       in number)
        return                  varchar2;

    --
    -- Return the participant username of a self-appraisal
    --
    function get_appraisal_participant(
        p_appraisal_id in number)
        return            varchar2;

    --
    -- Return the manager username for employee being appraised
    --
    function get_appraisal_manager(
        p_appraisal_id in number)
        return            varchar2;

    --
    -- Return the VP username for employee being appraised
    --
    procedure determine_appraisal_vp(
        p_appraisal_id in number,
        p_vp_username  in out varchar2);

    --
    -- Return true if the current user has any open approvals
    --
    function user_has_open_approvals
                return boolean;

    --
    -- Return true if the current user has any open admin tasks
    --
    function user_has_open_admin_tasks
                return boolean;

    --
    -- Validate whether the combination of admin and approver is legal
    --
    procedure validate_admin_and_approver(
        p_task_def_static_id in varchar2,
        p_empno              in number,
        p_proposed_sal       in number,
        p_admin             out varchar2,
        p_approver          out varchar2);

    --
    -- Return the details task URL
    --
    function details_task_url(
        p_app_id  in number,
        p_task_id in number,
        p_url     in varchar2)
        return       varchar2;

    --
    -- Return the approvers for a task
    --
    function approvers_for_task(
        p_task_id in number)
        return       varchar2;

    --
    -- Return the admins for a task
    --
    function admins_for_task(
        p_task_id in number)
        return       varchar2;

    --
    -- Return the approver for laptop based on the renewal count
    --
    function get_laptop_approver(
        p_renewal_count in number)
        return             varchar2;

    --
    -- Update a laptop request with the provided information
    --
    procedure update_laptop_request(
        p_id                      in number,
        p_status                  in varchar2 default null,
        p_workflow_id             in number   default null,
        p_approval_task_id        in number   default null,
        p_delivery_action_task_id in number   default null,
        p_approver                in varchar2 default null,
        p_decision_date           in date default null);

    --
    -- Return the appraisal period in words
    --
    function appraisal_period(
        p_start_date in date,
        p_end_date   in date)
        return          varchar2;

    --
    -- Update the status of an appraisal
    --
    procedure update_appraisal_status(
        p_id     in number,
        p_status in varchar2);

    --
    -- Return the DATE value of the named page item
    --
    function dv(
        p_item_name in varchar2)
        return         date;

    --
    -- Return the formatted value of a date using the page item's mask
    --
    function df(
        p_item_name in varchar2,
        p_date      in date)
    return varchar2;

    --
    -- Return a date that is one minute later than the current time
    --
    function rejection_delay_until_time
    return date;

    --
    -- Complete the Laptop Delivered task whose ID is passed in
    --
    procedure laptop_delivered(
        p_laptop_request_id in number);

    --
    -- Returns a comma-separated list of usernames in the given department name
    --
    function userlist_for_department(
        p_dname in varchar2)
        return     varchar2;

    --
    -- Handles vacation reassignments.
    -- Configured as the Task Vacation Rule Procedure at application level
    --
    procedure approval_vacation_handler(
        p_param    in apex_approval.t_vacation_rule_input,
        p_result  out apex_approval.t_vacation_rule_result);

    --
    -- Handles additional VP Review assignments
    -- Configured as the Task Vacation Rule Procedure at TaskDef level
    -- on the "VP Review" action task.
    --
    procedure appraisal_vp_review_handler(
        p_param    in apex_approval.t_vacation_rule_input,
        p_result  out apex_approval.t_vacation_rule_result);

    --
    -- Return true if laptop type is in stock
    --
    function laptop_in_stock(
        p_laptop_type in varchar2)
        return           boolean;

    --
    -- Deliver a laptop from stock and decrement amount on hand
    --
    procedure deliver_laptop_from_stock(
        p_laptop_type       in varchar2,
        p_laptop_request_id in number);

    --
    -- Order a laptop
    --
    procedure order_laptop_from_supplier(
        p_laptop_type       in varchar2,
        p_laptop_request_id in number);
end;
/
create or replace PACKAGE "EBA_DEMO_APPR_DATA" as
    --
    -- Install or reinstall the demo data for the sample
    procedure install_sample_data; 
end;
/







create or replace PACKAGE BODY "EBA_DEMO_APPR" as
    c_app_date_fmt constant varchar2(20) := 'APP_DATE_TIME_FORMAT';
    c_app_id       constant varchar2(6) := 'APP_ID';

    procedure update_laptop_request(
                p_id                      in number,
                p_status                  in varchar2 default null,
                p_workflow_id             in number   default null,
                p_approval_task_id        in number   default null,
                p_delivery_action_task_id in number   default null,
                p_approver                in varchar2 default null,
                p_decision_date           in date default null)
    is
    begin
       update EBA_DEMO_APPR_LAPTOP_REQUESTS
          set status                  = coalesce(p_status, status),
              workflow_id             = coalesce(p_workflow_id, workflow_id),
              approval_task_id        = coalesce(p_approval_task_id, approval_task_id),
              delivery_action_task_id = coalesce(p_delivery_action_task_id, delivery_action_task_id),
              approver                = coalesce(p_approver, approver),
              decision_date           = coalesce(p_decision_date, decision_date)
        where id                      = p_id;
       commit;
    end update_laptop_request;

    function get_participant_for_role(
                p_task_def_static_id in varchar2,
                p_job                in varchar2,
                p_proposed_sal       in number,
                p_role               in varchar2)
                return                  varchar2
    is
        l_ret varchar2(4000);
        l_include_fallback_entries boolean := false;
        l_current_user varchar2(200) := apex_application.g_user;
    begin
        for j in (select username,job_codes
                    from eba_demo_appr_approvers
                    where task_def_static_id = upper(p_task_def_static_id)
                    and (job_codes is null
                         or p_job is null
                         or (':'||job_codes||':' like '%:'||upper(p_job)||':%')
                        )
                    and (min_salary <= p_proposed_sal or min_salary is null)
                    and participant_role = p_role
                    and (participant_role = 'ADMIN' or username != l_current_user)
                    order by job_codes nulls last
                   ) loop
            -- Only include the fallback entries with null JOB_CODES
            -- if no more specific ones found
            if j.job_codes is null
               and not l_include_fallback_entries
               and l_ret is null then
                l_include_fallback_entries := true;
            end if;
            if j.job_codes is not null or l_include_fallback_entries then
                if l_ret is not null then
                    l_ret := l_ret ||',';
                end if;
                l_ret := l_ret || j.username;
            end if;
        end loop;
        return l_ret;
    end get_participant_for_role;

    function get_approver_for(
                p_task_def_static_id in varchar2,
                p_empno              in number,
                p_job                in varchar2,
                p_proposed_sal       in number)
                return                  varchar2
    is
    begin
        return get_participant_for_role(p_task_def_static_id,
                                        p_job,
                                        p_proposed_sal,
                                        'APPROVER');
    end get_approver_for;

    function get_admin_for(
                p_task_def_static_id in varchar2,
                p_job                in varchar2,
                p_proposed_sal       in number)
                return                  varchar2
    is
    begin
        return get_participant_for_role(p_task_def_static_id,
                                        p_job,
                                        p_proposed_sal,
                                        'ADMIN');
    end get_admin_for;

    function get_admin_for(
                p_task_def_static_id in varchar2,
                p_empno              in number,
                p_job                in varchar2,
                p_proposed_sal       in number)
                return                  varchar2
    is
    begin
        return get_participant_for_role(p_task_def_static_id,
                                        p_job,
                                        p_proposed_sal,
                                        'ADMIN');
    end get_admin_for;

    function user_has_open_approvals
                return boolean is
        l_app_user varchar2(30) := apex_application.g_user;
    begin
        for j in (select null
                   from apex_task_participants tp
                   left join apex_tasks t on t.task_id = tp.task_id
                   where tp.participant = l_app_user
                   and t.state_code in ('UNASSIGNED','ASSIGNED')
                   and tp.participant_type = 'POTENTIAL_OWNER'
                   and (t.initiator is null or t.initiator != l_app_user)
                   fetch first row only) loop
            apex_debug.info('### Returning true for user %s '||
                            'having open approvals tasks',l_app_user);
            return true;
        end loop;
        return false;
    end user_has_open_approvals;

    function user_has_open_admin_tasks
                return boolean is
        l_app_user varchar2(30) := apex_application.g_user;
    begin
        for j in (select null
                   from apex_task_participants tp
                   left join apex_tasks t on t.task_id = tp.task_id
                   where tp.participant = l_app_user
                   and t.state_code in ('UNASSIGNED','ASSIGNED')
                   and tp.participant_type = 'BUSINESS_ADMIN'
                   fetch first row only) loop
            apex_debug.info('### Returning true for user %s '||
                            'having open admin tasks',l_app_user);
            return true;
        end loop;
        return false;
    end user_has_open_admin_tasks;

    function details_task_url(
                p_app_id  in number,
                p_task_id in number,
                p_url     in varchar2)
                return       varchar2
    is
    begin
        return apex_plugin_util.replace_substitutions (
                    p_value => replace(replace(p_url, '&APP_ID.', p_app_id), '&TASK_ID.', p_task_id),
                    p_escape => false);
    end details_task_url;

    procedure validate_admin_and_approver(
                p_task_def_static_id in varchar2,
                p_empno              in number,
                p_proposed_sal       in number,
                p_admin             out varchar2,
                p_approver          out varchar2)
    is
        l_job eba_demo_appr_emp.job%type;
    begin
        select job
        into l_job
        from eba_demo_appr_emp
        where empno = p_empno;
        p_admin := get_admin_for(p_task_def_static_id,
                                 p_empno,
                                 l_job,
                                 p_proposed_sal);
        p_approver := get_approver_for(p_task_def_static_id,
                                       p_empno,
                                       l_job,
                                       p_proposed_sal);
    end validate_admin_and_approver;

    /*
     * Workaround for RDBMS 21c issue directly using listagg() against view w/ json_table()
     */
    function admins_for_task(
                p_task_id in number)
                return       varchar2
    is
        l_ret varchar2(2000);
    begin
        -- Return admins as CSV
        select listagg(participant,', ')
               within group (order by participant)
        into l_ret
        from apex_task_participants
        where task_id = p_task_id
        and participant_type = 'BUSINESS_ADMIN';
        return l_ret;
    end admins_for_task;

    function approvers_for_task(
                p_task_id in number)
                return       varchar2
    is
        l_ret varchar2(2000);
    begin
        -- Return approvers as CSV leaving out initiator
        select listagg(participant,', ')
               within group (order by participant)
        into l_ret
        from apex_task_participants tp, apex_tasks t
        where tp.task_id = p_task_id
        and t.task_id = tp.task_id
        and participant_type = 'POTENTIAL_OWNER'
        and (   t.initiator is null
             or t.initiator_can_complete = 'Y'
             or (t.initiator_can_complete = 'N' and t.initiator != tp.participant));
        return l_ret;
    end approvers_for_task;

    function get_laptop_approver(
                p_renewal_count number)
                return          varchar2
    is
    begin
        return
          case p_renewal_count
            when 0 then 'JANE'
            when 1 then 'STEVE'
            else 'BO'
          end;
    end get_laptop_approver;

    function get_appraisal_participant(
            p_appraisal_id in number)
            return            varchar2
    is
        l_ret varchar2(4000);
    begin
        select e.ename
        into   l_ret
        from eba_demo_appr_appraisals a
        left join eba_demo_appr_emp e on e.empno = a.empno
        where id = p_appraisal_id;
        return l_ret;
    exception
        when no_data_found then
            return null;
    end get_appraisal_participant;

    function get_appraisal_manager(
                p_appraisal_id in number)
                return            varchar2
    is
        l_ret varchar2(4000);
    begin
        select m.ename
          into l_ret
          from eba_demo_appr_appraisals a
          left join eba_demo_appr_emp e on e.empno = a.empno
          left outer join eba_demo_appr_emp m on m.empno = e.mgr
         where a.id = p_appraisal_id;
          return l_ret;
    exception
        when no_data_found then
            return null;
    end get_appraisal_manager;

    procedure determine_appraisal_vp(
                p_appraisal_id in number,
                p_vp_username  in out varchar2)
    is
    begin
        if p_vp_username is null then
            select m2.ename
              into p_vp_username
              from eba_demo_appr_appraisals a
              left join eba_demo_appr_emp e on e.empno = a.empno
              left outer join eba_demo_appr_emp m on m.empno = e.mgr
              left outer join eba_demo_appr_emp m2 on m2.empno = m.mgr
             where a.id = p_appraisal_id;
            if p_vp_username is null then
                raise_application_error(-20001,'No second-level VP available for review.');
            end if;
        else
            if p_vp_username != 'NONE' then
                for emp_check in (select null
                                    from eba_demo_appr_emp
                                   where ename = p_vp_username) loop
                    return;
                end loop;
                raise_application_error(-20001,apex_string.format('%s is not a valid employee name.',p_vp_username));
            end if;
        end if;
    exception
        when no_data_found then
            null;
    end determine_appraisal_vp;

    function mask_for_date_page_item(p_item_name varchar2) return varchar2 is
        l_mask varchar2(200);
    begin
        select coalesce(format_mask,v(c_app_date_fmt))
        into l_mask
        from apex_application_page_items
        where application_id = v(c_app_id)
        and item_name = upper(p_item_name);
        return l_mask;
    end mask_for_date_page_item;
    --
    function dv(p_item_name varchar2) return date is
        l_mask varchar2(200) := mask_for_date_page_item(p_item_name);
    begin
        return to_date(v(p_item_name),l_mask);
    end dv;
    --
    function df(p_item_name varchar2, p_date date) return varchar2 is
        l_mask varchar2(200) := mask_for_date_page_item(p_item_name);
    begin
        return to_char(p_date,l_mask);
    end df;
    --
    function appraisal_period(
        p_start_date in date,
        p_end_date   in date)
        return          varchar2
    is
    begin
        return to_char(p_start_date,'FMMon YYYY')||
               ' → '||
               to_char(p_end_date,'FMMon YYYY');
    end appraisal_period;
    --
    procedure update_appraisal_status(
                p_id     in number,
                p_status in varchar2)
    is
    begin
        update eba_demo_appr_appraisals
        set status = upper(p_status)
        where id = p_id;
        case upper(p_status)
            when 'ORIGINATED' then
                update eba_demo_appr_appraisals
                set date_originated = sysdate
                where id = p_id;
            when 'SUBMITTED' then
                update eba_demo_appr_appraisals
                set input_completed = sysdate
                where id = p_id;
            when 'MGR_SUBMITTED' then
                update eba_demo_appr_appraisals
                set manager_completed = sysdate
                where id = p_id;
            when 'VP_REVIEWED' then
                update eba_demo_appr_appraisals
                set vp_review_date = sysdate
                where id = p_id;
            else
                null;
        end case;
    end update_appraisal_status;
    --
    function rejection_delay_until_time
    return date
    is
    begin
        return sysdate + 1/24/60;
    end;
    --
    procedure laptop_delivered(
                p_laptop_request_id in number)
    is
        pragma autonomous_transaction;
    begin
        --
        -- If the laptop request has a non-null order_id
        -- then it was not in stock and we had to order it
        -- 
        for j in (select workflow_id as laptop_request_workflow_id
                    from eba_demo_appr_laptop_requests
                   where id = p_laptop_request_id
                     and order_id is not null) loop
            --
            -- Lookup the task id of the action task used to
            -- confirm the receipt of the laptop order.
            -- It's stored in the V_ version variable of
            -- the LAPTOP_PROCUREMENT workflow invoked from
            -- the LAPTOP_REQUEST workflow
            -- 
            for k in (select workflow_id as procurement_workflow_id
                        from apex_workflows
                       where workflow_def_static_id = 'LAPTOP_PROCUREMENT'
                         and parent_workflow_id = j.laptop_request_workflow_id) loop
                apex_approval.complete_task(
                    p_task_id   => apex_workflow.get_variable_value(
                                    p_instance_id        => k.procurement_workflow_id,
                                    p_variable_static_id => 'V_DELIVERY_ACTION_TASK_ID'),
                    p_autoclaim => true);
            end loop;
        end loop;
    end;
    --
    function userlist_for_department(
                p_dname in varchar2)
                return     varchar2
    is
        l_ret varchar2(4000);
    begin
        select listagg(e.ename,',')
        into l_ret
        from eba_demo_appr_emp e
        left outer join eba_demo_appr_dept d
                     on d.deptno = e.deptno
        where d.dname = p_dname;
        return l_ret;
    end;
    --
    procedure add_business_admin(
        p_additional_participants in out nocopy apex_approval.t_task_participant_changes,
        p_taskdef_name            in varchar2,
        p_old                     in varchar2,
        p_new                     in varchar2,
        p_reason                  in varchar2 default null)
    is
        l_idx pls_integer := p_additional_participants.count + 1;
    begin
        p_additional_participants(l_idx) :=
            apex_approval.t_task_participant_change(
                apex_approval.t_task_participant(apex_approval.c_task_business_admin,
                                                 apex_approval.c_task_identity_type_user,
                                                 p_old),
                apex_approval.t_task_participant(apex_approval.c_task_business_admin,
                                                 apex_approval.c_task_identity_type_user,
                                                 p_new),
                coalesce(p_reason,
                         apex_string.format(
                            '%s temporarily covering %s business admin dutites',
                            p_new,
                            p_taskdef_name)));
    end add_business_admin;
    --
    procedure add_participant(
        p_additional_participants in out nocopy apex_approval.t_task_participant_changes,
        p_taskdef_name            in varchar2,
        p_old                     in varchar2,
        p_new                     in varchar2,
        p_reason                  in varchar2,
        p_wildcard                in boolean default false)
    is
        l_idx pls_integer := p_additional_participants.count + 1;
    begin
        p_additional_participants(l_idx) :=
            apex_approval.t_task_participant_change(
                apex_approval.t_task_participant(apex_approval.c_task_potential_owner,
                                                 apex_approval.c_task_identity_type_user,
                                                 p_old),
                apex_approval.t_task_participant(apex_approval.c_task_potential_owner,
                                                 apex_approval.c_task_identity_type_user,
                                                 p_new),
                coalesce(p_reason,
                         apex_string.format(
                            case
                                when p_wildcard then '%s helping to cover %s'
                                else      '%s covering %s for vacationing %s'
                            end,
                            p_new,
                            p_taskdef_name,
                            p_old)));
    end add_participant;
    --
    procedure handle_temp_business_admin(
        p_participants            in apex_approval.t_task_participants,
        p_taskdef_name            in varchar2,
        p_additional_participants in out nocopy apex_approval.t_task_participant_changes)
    is
        l_temp_business_admin varchar2(200) := apex_app_setting.get_value('TEMPORARY_BUSINESS_ADMIN');
    begin
        if l_temp_business_admin is not null then
            for j in 1..p_participants.count loop
                if     p_participants(j).type = apex_approval.c_task_business_admin
                   and p_participants(j).identity = apex_approval.c_task_identity_type_user then
                    add_business_admin(
                        p_additional_participants => p_additional_participants,
                        p_taskdef_name            => p_taskdef_name,
                        p_old                     => p_participants(j).value,
                        p_new                     => l_temp_business_admin);
                end if;
            end loop;
        end if;
    end handle_temp_business_admin;
        --
    function involved_participants(
        p_participants in apex_approval.t_task_participants)
        return            apex_t_varchar2
    is
        l_ret apex_t_varchar2;
    begin
        for j in 1..p_participants.count loop
            if     p_participants(j).type = apex_approval.c_task_potential_owner
               and p_participants(j).identity = apex_approval.c_task_identity_type_user then
                apex_string.push(l_ret,p_participants(j).value);
            end if;
        end loop;
        return l_ret;
    end;
    --
    function taskdef_name(
        p_task_def_static_id in varchar2)
        return                  varchar2
    is
        l_ret apex_appl_taskdefs.name%type;
    begin
        select name
        into l_ret
        from apex_appl_taskdefs
       where static_id = p_task_def_static_id
         and application_id = v('APP_ID');
       return l_ret;
    exception
        when no_data_found then
            return null;
    end taskdef_name;

    procedure approval_vacation_handler(
                p_param    in apex_approval.t_vacation_rule_input,
                p_result  out apex_approval.t_vacation_rule_result)
    is
        l_participants     apex_t_varchar2;
        l_taskdef_name     apex_tasks.task_def_name%type;
    begin
        l_taskdef_name := taskdef_name(p_param.task_def_static_id);
        handle_temp_business_admin(
            p_participants            => p_param.original_participants,
            p_taskdef_name            => l_taskdef_name,
            p_additional_participants => p_result.participant_changes);
        l_participants := involved_participants(p_param.original_participants);
        if l_participants.count > 0 then
            --
            -- Loop over vacation rows where the current date falls between the
            -- optional start/end dates and the "For Which Approval?" (task_def_ids)
            -- column includes the current taskdef id
            --
            for j in (select original_user,substitute_user,reason
                        from eba_demo_appr_vacation
                       where    (original_user is null
                             or original_user in (select column_value
                                                    from table(l_participants)))
                         and instr(':'||task_def_ids||':',':'||p_param.task_def_static_id||':') > 0
                         and nvl(start_date,sysdate) <= sysdate and nvl(end_date,sysdate) >= sysdate ) loop
                if j.original_user is null then
                    -- Treat a null original_user as a wildcard, so create a vacation
                    -- assignment for each of the original participants to be substituted
                    -- by the substitute_user
                    for k in 1..l_participants.count loop
                        add_participant(
                            p_additional_participants => p_result.participant_changes,
                            p_taskdef_name            => l_taskdef_name,
                            p_old                     => l_participants(k),
                            p_new                     => j.substitute_user,
                            p_reason                  => j.reason,
                            p_wildcard                => true);
                    end loop;
                else
                    add_participant(
                        p_additional_participants => p_result.participant_changes,
                        p_taskdef_name            => l_taskdef_name,
                        p_old                     => j.original_user,
                        p_new                     => j.substitute_user,
                        p_reason                  => j.reason);
                end if;
            end loop;
            p_result.has_participant_changes := p_result.participant_changes.count > 0;
        end if;
    end;

    procedure appraisal_vp_review_handler(
                p_param    in apex_approval.t_vacation_rule_input,
                p_result  out apex_approval.t_vacation_rule_result)
    is
        l_participants     apex_t_varchar2;
        l_taskdef_name     apex_tasks.task_def_name%type;
    begin
        l_taskdef_name := taskdef_name(p_param.task_def_static_id);
        handle_temp_business_admin(
            p_participants            => p_param.original_participants,
            p_taskdef_name            => l_taskdef_name,
            p_additional_participants => p_result.participant_changes);
        l_participants := involved_participants(p_param.original_participants);
        if l_participants.count > 0 then
            --
            -- Loop over usernames in the EMP_APPRAISAL_EXTRA_VP_REVIEWERS setting value
            --
            for j in (select column_value as substitute_user
                        from apex_string.split(apex_app_setting.get_value('EMP_APPRAISAL_EXTRA_VP_REVIEWERS'),':')) loop
                        add_participant(
                            p_additional_participants => p_result.participant_changes,
                            p_taskdef_name            => l_taskdef_name,
                            p_old                     => l_participants(1),
                            p_new                     => j.substitute_user,
                            p_reason                  => apex_string.format('Additional appraisal signoff %s',j.substitute_user));
            end loop;
            p_result.has_participant_changes := p_result.participant_changes.count > 0;
        end if;
    end appraisal_vp_review_handler;

    function laptop_in_stock(
        p_laptop_type in varchar2)
        return           boolean
    is
    begin
        for j in (select amount
                    from eba_demo_appr_laptop_stock
                   where laptop_type = upper(p_laptop_type)
                     and amount > 0) loop
            return true;
        end loop;
        return false;
    end laptop_in_stock;

    procedure deliver_laptop_from_stock(
        p_laptop_type       in varchar2,
        p_laptop_request_id in number)
    is
    begin
        update eba_demo_appr_laptop_stock
           set amount = amount - 1
         where laptop_type = upper(p_laptop_type);
         update eba_demo_appr_laptop_requests
            set status = 'DELIVERED',
                delivered_date = trunc(sysdate)
          where id = p_laptop_request_id;
    end deliver_laptop_from_stock;

    procedure order_laptop_from_supplier(
        p_laptop_type       in varchar2,
        p_laptop_request_id in number)
    is
    begin
        -- In this demo, we're simulating getting the order id
        -- to be a random number betwen 111111 and 999999, but in a real application
        -- this would place the order for a laptop of type p_laptop_type
        -- with the appropriate supplier and get back the order id number
        update eba_demo_appr_laptop_requests
           set order_id = trunc(dbms_random.value(1111111, 9999999)),
               order_date = trunc(sysdate)
        where id = p_laptop_request_id;
    end order_laptop_from_supplier;
end;
/
create or replace PACKAGE BODY "EBA_DEMO_APPR_DATA" is 
    procedure delete_sample_data is 
      l_app_id number := v('APP_ID'); 
    begin 
        delete from eba_demo_appr_sal_history; 
        delete from eba_demo_appr_emp; 
        delete from eba_demo_appr_dept; 
        delete from eba_demo_appr_approvers;
        apex_workflow.remove_development_instances(p_application_id => l_app_id);    
        delete from eba_demo_appr_appraisals;
        delete from eba_demo_appr_laptop_requests; 
        delete from eba_demo_appr_laptop_stock; 
        delete from eba_demo_appr_vacation;
    end delete_sample_data; 
    -- 
    procedure insert_sample_data is 
    begin 
        insert into eba_demo_appr_approvers (username,task_def_static_id,job_codes,participant_role,min_salary) 
        values ('STEVE','SALARY_CHANGE','MANAGER','APPROVER',3000); 
        insert into eba_demo_appr_approvers (username,task_def_static_id,job_codes,participant_role,min_salary) 
        values ('JANE','SALARY_CHANGE','SALESMAN:ANALYST:MANAGER','APPROVER',null); 
        insert into eba_demo_appr_approvers (username,task_def_static_id,job_codes,participant_role,min_salary) 
        values ('BO','SALARY_CHANGE','CLERK:MANAGER:PRESIDENT','APPROVER',null); 
        insert into eba_demo_appr_approvers (username,task_def_static_id,job_codes,participant_role,min_salary) 
        values ('PAT','SALARY_CHANGE',null,'ADMIN',null); 
        insert into eba_demo_appr_approvers (username,task_def_static_id,job_codes,participant_role,min_salary) 
        values ('PAT','SALARY_CHANGE',null,'APPROVER',null); 
        insert into eba_demo_appr_dept (deptno,dname,loc) 
        values (10,'ACCOUNTING','NEW YORK'); 
        insert into eba_demo_appr_dept (deptno,dname,loc) 
        values (20,'RESEARCH','DALLAS'); 
        insert into eba_demo_appr_dept (deptno,dname,loc) 
        values (30,'SALES','CHICAGO'); 
        insert into eba_demo_appr_dept (deptno,dname,loc) 
        values (40,'OPERATIONS','BOSTON'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7369,'SMITH','CLERK',7902,date'1980-12-17',800,null,20,'L59 2676749090'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7499,'ALLEN','SALESMAN',7698,date'1981-02-20',1600,300,30,'NL11 2792059852'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7521,'WARD','SALESMAN',7698,date'1981-02-22',1250,500,30,'DE93 5765445093'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7566,'JONES','MANAGER',7839,date'1981-04-02',2975,null,20,'FR17 2643471186'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7654,'MARTIN','SALESMAN',7698,date'1981-09-28',1250,1400,30,'ES15 2387378313'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7698,'BLAKE','MANAGER',7839,date'1981-05-01',2850,null,30,'DE37 1114828059'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7782,'CLARK','MANAGER',7839,date'1981-06-09',2450,null,10,'NL43 7896495402'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7788,'SCOTT','ANALYST',7566,date'1982-12-09',3000,null,20,'ES22 3307779590'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7839,'KING','PRESIDENT',null,date'1981-11-17',5000,null,10,'ES56 3325856285'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7844,'TURNER','SALESMAN',7698,date'1981-09-08',1500,0,30,'FR61 7629317593'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7876,'ADAMS','CLERK',7788,date'1983-01-12',1100,null,20,'IT45 2343833140'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7900,'JAMES','CLERK',7698,date'1981-12-03',950,null,30,'ES29 8075401565'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7902,'FORD','ANALYST',7566,date'1981-12-03',3000,null,20,'DE67 0549659906'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (7934,'MILLER','CLERK',7782,date'1982-01-23',1300,null,10,'ES94 8295486525'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (8876,'PAT','CLERK',8900,date'1983-03-17',1100,null,40,'IT18 8496036712'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (8900,'BO','MANAGER',7839,date'1981-06-12',2950,null,40,'B13 9855830234'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (8902,'STEVE','CLERK',8900,date'1981-09-15',2000,null,40,'CH02 5018944284'); 
        insert into eba_demo_appr_emp (empno,ename,job,mgr,hiredate,sal,comm,deptno,bank_account) 
        values (8934,'JANE','CLERK',8900,date'1983-05-23',1300,null,40,'GB55 6220604619');
        insert into eba_demo_appr_laptop_stock(laptop_type,amount)
        values ('MAC',1);
        insert into eba_demo_appr_laptop_stock(laptop_type,amount)
        values ('WIN',0);
        declare 
            l_num_adjustments number; 
            l_pct_adjustment number; 
            l_inc_sal number; 
            l_cur_sal number; 
            l_prev_sal number; 
            l_period number; 
            l_today date := trunc(sysdate); 
        begin 
        for e in (select empno, sal, hiredate,  
                  extract(year from sysdate) -  
                  extract(year from hiredate) as years  
                    from eba_demo_appr_emp) loop 
            if e.years < 3 then 
                insert into eba_demo_appr_sal_history(empno,new_sal,approval_date) 
                values (e.empno,e.sal,e.hiredate); 
            end if; 
            -- random number of salary adjustments between sysdate and hiredate 
            select round(dbms_random.value(1.5, e.years/2+0.5), 0) 
            into l_num_adjustments 
            from dual; 
            l_cur_sal := e.sal; 
            l_inc_sal := l_cur_sal; 
            l_period := round(e.years / l_num_adjustments,0) * 12; 
            for j in 1..l_num_adjustments loop 
                -- random percent of adjustment   
                insert into eba_demo_appr_sal_history(empno,new_sal,approval_date) 
                        values (e.empno,l_inc_sal,add_months(l_today,(-1)*l_period*j)); 
                select round((1 - round(dbms_random.value(2.5, 25), 0)/100)*l_cur_sal,-1) 
                into l_inc_sal 
                from dual;                 
                l_cur_sal := l_inc_sal; 
            end loop; 
        end loop; 
        end;         
    end insert_sample_data;   
    --
    procedure reset_settings
    is
    begin
        apex_app_setting.set_value('EMP_APPRAISAL_EXTRA_VP_REVIEWERS',null);
        apex_app_setting.set_value('TEMPORARY_BUSINESS_ADMIN',null);
    end reset_settings;
    -- 
    procedure install_sample_data is 
    begin 
        delete_sample_data; 
        insert_sample_data; 
        commit; 
        reset_settings;
    end install_sample_data; 
    -- 
    function user_exists(p_username varchar2) return boolean is 
    begin 
        return not apex_util.is_username_unique(p_username); 
    end user_exists;          
end;
/






