drop table if exists dv_customers cascade constraints;
drop table if exists dv_purchase_orders cascade constraints;
drop table if exists dv_products cascade constraints;
drop table if exists dv_po_line_items cascade constraints;
drop trigger if exists trg_dv_po_number;
drop trigger if exists trg_dv_po_line_items;
drop sequence if exists dv_po_number_seq;
drop view if exists dv_purchase_order_dv;

  CREATE TABLE "DV_CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"COMPANY_NAME" VARCHAR2(100), 
	"PHONE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(200), 
	"CITY" VARCHAR2(50), 
	"STATE" VARCHAR2(2), 
	"ZIP_CODE" VARCHAR2(10), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE
   ) ;
  
  CREATE TABLE "DV_PURCHASE_ORDERS" 
   (	"PO_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PO_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	"PO_DATE" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"DELIVERY_INSTRUCTIONS" VARCHAR2(500), 
    "STATUS" VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL ENABLE,
	 PRIMARY KEY ("PO_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("PO_NUMBER")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DV_PURCHASE_ORDERS" ADD CONSTRAINT "FK_PO_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "DV_CUSTOMERS" ("CUSTOMER_ID") ENABLE;

 ALTER TABLE "DV_PURCHASE_ORDERS" ADD CONSTRAINT "DV_PURCHASE_ORDERS_STATUS_CHK" 
    CHECK ("STATUS" IN ('DRAFT', 'COMPLETED', 'REJECTED'));

  CREATE SEQUENCE DV_PO_NUMBER_SEQ START WITH 3000 INCREMENT BY 1 NOCACHE NOCYCLE;

  CREATE OR REPLACE TRIGGER trg_dv_po_number
    BEFORE INSERT ON DV_PURCHASE_ORDERS
    FOR EACH ROW
    BEGIN
      IF :NEW.PO_NUMBER IS NULL THEN
        -- Use the PO_ID that is about to be inserted (from the same sequence)
        -- IF :NEW.PO_NUMBER IS NULL THEN
          SELECT DV_PO_NUMBER_SEQ.NEXTVAL INTO :NEW.PO_NUMBER FROM DUAL;
        -- END IF;
      END IF;
    END;
    /

  CREATE TABLE "DV_PRODUCTS" 
   (	"PRODUCT_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PRODUCT_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200) NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("PRODUCT_CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DV_PO_LINE_ITEMS" 
   (	"LINE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"PO_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	"UNIT_PRICE" NUMBER(10,2), 
	"CREATED_ON" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"UPDATED_ON" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	 PRIMARY KEY ("LINE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DV_PO_LINE_ITEMS" ADD CONSTRAINT "FK_LINE_PO" FOREIGN KEY ("PO_ID")
	  REFERENCES "DV_PURCHASE_ORDERS" ("PO_ID") ENABLE;
  ALTER TABLE "DV_PO_LINE_ITEMS" ADD CONSTRAINT "FK_LINE_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "DV_PRODUCTS" ("PRODUCT_ID") ENABLE;

  create or replace trigger TRG_DV_PO_LINE_ITEMS
    before insert or update
    on DV_PO_LINE_ITEMS
    for each row
begin
    if inserting and :new.UPDATED_ON is null then
        :new.UPDATED_ON := sysdate;
    elsif updating then
        :new.UPDATED_ON := sysdate;
    end if;
end TRG_DV_PO_LINE_ITEMS;
/

CREATE OR REPLACE FORCE EDITIONABLE JSON RELATIONAL DUALITY VIEW "DV_PURCHASE_ORDER_DV"  AS 
dv_purchase_orders @alias(as: po) @insert @update @delete
{
  _id: po_id
  po_number: po_number
  status: status
  date: po_date
  customer: dv_customers @insert @update @nodelete
  {
    customer_id: customer_id
    name: name
    company_name: company_name
    phone: phone
    email: email
    address: address
    city: city
    state: state
    zip_code: zip_code
  }
  delivery_instructions: delivery_instructions
  line_items: dv_po_line_items @insert @update @delete
  [{
    line_item_id: line_id
    product: dv_products @noinsert @noupdate @nodelete
    {
      product_id: product_id
      product_code: product_code
      desc: description
      unit_price: unit_price
    }
    quantity: quantity
    unit_price: unit_price
    updated_on: updated_on
  }]
  total_amount @generated(sql: "select nvl(sum(i.unit_price * i.quantity), 0) from dv_po_line_items i where i.po_id = po.po_id")
  last_updated @generated(sql: "select greatest(nvl(max(i.updated_on), po.po_date), po.po_date) from dv_po_line_items i where i.po_id = po.po_id")
};

-- Standard syntax below kept for comparison with the GraphQL/simple syntax above.

--   CREATE OR REPLACE FORCE EDITIONABLE JSON RELATIONAL DUALITY VIEW "DV_PURCHASE_ORDER_DV"  AS 
--   SELECT JSON {
--     '_id' : po.po_id,
--     'po_number' : po.po_number,
--     'date' : po.po_date,
--     'customer' : (
--         SELECT JSON {
--             'customer_id': c.customer_id,
--             'name' : c.name,
--             'company_name' : c.company_name,
--             'phone' : c.phone,
--             'email' : c.email,
--             'address' : c.address,
--             'city' : c.city,
--             'state' : c.state,
--             'zip_code' : c.zip_code
--         }
--         FROM dv_customers c WITH INSERT UPDATE NODELETE
--         WHERE c.customer_id = po.customer_id
--     ),
--     'delivery_instructions' : po.delivery_instructions,
--     'line_items' : [
--         SELECT JSON {
--             'line_item_id' : li.line_id,
--             'product' : (SELECT JSON {
--                           'product_id' : p.product_id,
--                           'product_code' : p.product_code,
--                           'desc' : p.description,
--                           'unit_price' : p.unit_price
--             }
--             FROM dv_products p WITH INSERT UPDATE NODELETE
--             WHERE p.product_id = li.product_id),
--             'quantity' : li.quantity,
--             'unit_price' : li.unit_price,
--             'updated_on' : li.updated_on
--         }
--         FROM dv_po_line_items li WITH INSERT UPDATE DELETE
--         WHERE li.po_id = po.po_id
--     ],
--     'total_amount' : generated using ( select nvl(sum(i.unit_price * i.quantity), 0) from dv_po_line_items i where i.po_id = po.po_id )
--     'last_updated'  generated using ( select greatest(nvl(max(i.updated_on), po.po_date), po.po_date) from dv_po_line_items i where i.po_id = po.po_id )
-- }
-- FROM dv_purchase_orders po
-- WITH INSERT UPDATE DELETE;
