Rem Copyright (c) 2026, Oracle and/or its affiliates.

SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- ============================================================
-- BP_ORDER_ENTRY_SCHEMA_26AI.SQL
-- Re-runnable Oracle 26ai schema for a demo order entry app.
-- Supports:
-- - product images stored in-table
-- - stores with geolocation for APEX map regions
-- - online and in-person orders
-- - dashboard queries for sales and product performance
-- ============================================================

DROP VIEW IF EXISTS OREN_ORDERS_DV CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS OREN_ORDER_ITEMS CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS OREN_ORDERS CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS OREN_PRODUCTS CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS OREN_STORES CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS OREN_CUSTOMERS CASCADE CONSTRAINTS PURGE;

CREATE TABLE OREN_CUSTOMERS (
    CUSTOMER_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    FULL_NAME       VARCHAR2(255) NOT NULL,
    EMAIL_ADDRESS   VARCHAR2(255) NOT NULL,
    CONSTRAINT OREN_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT OREN_CUST_EMAIL_UK UNIQUE (EMAIL_ADDRESS)
);

CREATE TABLE OREN_STORES (
    STORE_ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    STORE_NAME          VARCHAR2(255) NOT NULL,
    WEB_ADDRESS         VARCHAR2(512),
    PHYSICAL_ADDRESS    VARCHAR2(512),
    LATITUDE            NUMBER(9,6),
    LONGITUDE           NUMBER(9,6),
    CONSTRAINT OREN_STORES_PK PRIMARY KEY (STORE_ID),
    CONSTRAINT OREN_STORES_NAME_UK UNIQUE (STORE_NAME),
    CONSTRAINT OREN_STORES_ADDR_CK CHECK (
        WEB_ADDRESS IS NOT NULL OR PHYSICAL_ADDRESS IS NOT NULL
    ),
    CONSTRAINT OREN_STORES_LAT_CK CHECK (
        LATITUDE IS NULL OR (LATITUDE BETWEEN -90 AND 90)
    ),
    CONSTRAINT OREN_STORES_LON_CK CHECK (
        LONGITUDE IS NULL OR (LONGITUDE BETWEEN -180 AND 180)
    )
);

CREATE TABLE OREN_PRODUCTS (
    PRODUCT_ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    PRODUCT_NAME         VARCHAR2(255) NOT NULL,
    UNIT_PRICE           NUMBER(10,2) NOT NULL,
    PRODUCT_IMAGE        BLOB,
    IMAGE_MIME_TYPE      VARCHAR2(255),
    IMAGE_FILENAME       VARCHAR2(255),
    IMAGE_CHARSET        VARCHAR2(128),
    IMAGE_LAST_UPDATED   TIMESTAMP,
    CONSTRAINT OREN_PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT OREN_PRODUCTS_NAME_UK UNIQUE (PRODUCT_NAME),
    CONSTRAINT OREN_PRODUCTS_PRICE_CK CHECK (UNIT_PRICE >= 0)
);

CREATE TABLE OREN_ORDERS (
    ORDER_ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_DATETIME    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ORDER_CHANNEL     VARCHAR2(10) NOT NULL,
    ORDER_STATUS      VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
    STORE_ID          NUMBER NOT NULL,
    CUSTOMER_ID       NUMBER,
    CONSTRAINT OREN_ORDERS_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT OREN_ORDERS_CHAN_CK CHECK (
        ORDER_CHANNEL IN ('ONLINE', 'IN_PERSON')
    ),
    CONSTRAINT OREN_ORDERS_STATUS_CK CHECK (
        ORDER_STATUS IN ('OPEN', 'PAID', 'COMPLETE', 'CANCELLED')
    ),
    CONSTRAINT OREN_ORDERS_CUST_REQ_CK CHECK (
        (ORDER_CHANNEL = 'ONLINE' AND CUSTOMER_ID IS NOT NULL)
        OR ORDER_CHANNEL = 'IN_PERSON'
    ),
    CONSTRAINT OREN_ORDERS_STORE_FK FOREIGN KEY (STORE_ID)
        REFERENCES OREN_STORES (STORE_ID),
    CONSTRAINT OREN_ORDERS_CUST_FK FOREIGN KEY (CUSTOMER_ID)
        REFERENCES OREN_CUSTOMERS (CUSTOMER_ID)
);

CREATE INDEX OREN_ORDERS_CUSTOMER_IX
    ON OREN_ORDERS (CUSTOMER_ID);

CREATE TABLE OREN_ORDER_ITEMS (
    ORDER_ITEM_ID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_ID        NUMBER NOT NULL,
    PRODUCT_ID      NUMBER NOT NULL,
    QUANTITY        NUMBER(10) NOT NULL,
    UNIT_PRICE      NUMBER(10,2) NOT NULL,
    CONSTRAINT OREN_ORDER_ITEMS_PK PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT OREN_OI_ORDER_FK FOREIGN KEY (ORDER_ID)
        REFERENCES OREN_ORDERS (ORDER_ID)
        ON DELETE CASCADE,
    CONSTRAINT OREN_OI_PRODUCT_FK FOREIGN KEY (PRODUCT_ID)
        REFERENCES OREN_PRODUCTS (PRODUCT_ID),
    CONSTRAINT OREN_OI_QTY_CK CHECK (QUANTITY > 0),
    CONSTRAINT OREN_OI_PRICE_CK CHECK (UNIT_PRICE >= 0)
);

CREATE INDEX OREN_ORDERS_STORE_DT_IX
    ON OREN_ORDERS (STORE_ID, ORDER_DATETIME);

CREATE INDEX OREN_ORDERS_CHAN_ST_IX
    ON OREN_ORDERS (ORDER_CHANNEL, ORDER_STATUS);

CREATE INDEX OREN_OI_PRODUCT_IX
    ON OREN_ORDER_ITEMS (PRODUCT_ID);

CREATE INDEX OREN_OI_ORDER_IX
    ON OREN_ORDER_ITEMS (ORDER_ID);


-- ============================================================
-- Order-centric JSON Relational Duality View for the OREN demo
-- order entry schema.
--
-- Run after:
--   - oren_order_entry_schema_26ai.sql
--   - optional seed/sample data scripts
--
-- Notes:
-- - Root aggregate: OREN_ORDERS
-- - Writable through the duality view: order header and order items
-- - Read-only reference objects: store, customer, product
-- - Product image/blob columns are intentionally excluded
-- - Master-data detail fields use NOCHECK so changes to names, URLs,
--   and catalog prices do not create ETAG churn for order documents
-- ============================================================

CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW OREN_ORDERS_DV AS
SELECT JSON {
    '_id'           : o.order_id,
    'orderDatetime' : o.order_datetime WITH NOUPDATE,
    'orderChannel'  : o.order_channel WITH NOUPDATE,
    'orderStatus'   : o.order_status,
    'store'         :
        (SELECT JSON {
            'storeId'         : s.store_id WITH NOCHECK,
            'storeName'       : s.store_name WITH NOCHECK,
            'webAddress'      : s.web_address WITH NOCHECK,
            'physicalAddress' : s.physical_address WITH NOCHECK,
            'latitude'        : s.latitude WITH NOCHECK,
            'longitude'       : s.longitude WITH NOCHECK
        }
         FROM OREN_STORES s
         WHERE s.store_id = o.store_id),
    'customer'      :
        (SELECT JSON {
            'customerId'   : c.customer_id WITH NOCHECK,
            'fullName'     : c.full_name WITH NOCHECK,
            'emailAddress' : c.email_address WITH NOCHECK
        }
         FROM OREN_CUSTOMERS c
         WHERE c.customer_id = o.customer_id),
    'items'         :
        (SELECT JSON_ARRAYAGG(
            JSON {
                'orderItemId' : oi.order_item_id,
                'quantity'    : oi.quantity,
                'unitPrice'   : oi.unit_price,
                'product'     :
                    (SELECT JSON {
                        'productId'        : p.product_id WITH NOCHECK,
                        'productName'      : p.product_name WITH NOCHECK,
                        'catalogUnitPrice' : p.unit_price WITH NOCHECK
                    }
                     FROM OREN_PRODUCTS p
                     WHERE p.product_id = oi.product_id)
            }
            ORDER BY oi.order_item_id
        )
         FROM OREN_ORDER_ITEMS oi WITH INSERT UPDATE DELETE
         WHERE oi.order_id = o.order_id)
}
FROM OREN_ORDERS o WITH INSERT UPDATE DELETE;

-- Example query:
-- SELECT JSON_SERIALIZE(data PRETTY) FROM OREN_ORDERS_DV FETCH FIRST 1 ROW ONLY;

-- ============================================================
-- Table and column comments for the OREN_ demo order entry schema.
-- Convention: apex_db_dictionary / wwv_db_dictionary attributes
-- ============================================================

-- ============================================================
-- TABLE COMMENTS
-- ============================================================

COMMENT ON TABLE OREN_STORES IS 'Physical and online storefronts.';


-- ============================================================
-- OREN_CUSTOMERS
-- ============================================================

COMMENT ON COLUMN OREN_CUSTOMERS.FULL_NAME IS 'display-label: Customer Name, primary-display-column: true';


-- ============================================================
-- OREN_STORES
-- ============================================================

COMMENT ON COLUMN OREN_STORES.STORE_NAME IS 'primary-display-column: true';


-- ============================================================
-- OREN_PRODUCTS
-- ============================================================

COMMENT ON COLUMN OREN_PRODUCTS.PRODUCT_NAME IS 'primary-display-column: true';
COMMENT ON COLUMN OREN_PRODUCTS.UNIT_PRICE IS 'format-mask: FM999G999G990D00';
COMMENT ON COLUMN OREN_PRODUCTS.PRODUCT_IMAGE IS 'display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_MIME_TYPE IS 'display-in-form: false, display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_FILENAME IS 'display-in-form: false, display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_CHARSET IS 'display-in-form: false, display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_LAST_UPDATED IS 'display-in-form: false, display-in-report: false';


-- ============================================================
-- OREN_ORDERS
-- ============================================================

COMMENT ON COLUMN OREN_ORDERS.ORDER_ID IS 'primary-display-column: true';
COMMENT ON COLUMN OREN_ORDERS.ORDER_DATETIME IS 'format-mask: DD-MON-YYYY HH24:MI';
COMMENT ON COLUMN OREN_ORDERS.ORDER_CHANNEL IS 'ONLINE or IN_PERSON.';
COMMENT ON COLUMN OREN_ORDERS.STORE_ID IS 'display-label: Store';
COMMENT ON COLUMN OREN_ORDERS.CUSTOMER_ID IS 'Required for online orders only. display-label: Customer';


-- ============================================================
-- OREN_ORDER_ITEMS
-- ============================================================

COMMENT ON COLUMN OREN_ORDER_ITEMS.ORDER_ID IS 'display-label: Order';
COMMENT ON COLUMN OREN_ORDER_ITEMS.PRODUCT_ID IS 'display-label: Product';
COMMENT ON COLUMN OREN_ORDER_ITEMS.UNIT_PRICE IS 'display-label: Selling Unit Price, format-mask: FM999G999G990D00';


-- ============================================================
-- Oracle AI Database 26ai annotations for the OREN_ order entry schema.
-- Re-runnable: uses ADD OR REPLACE so annotation values can be updated
-- without separate DROP clauses in the same ANNOTATIONS block.
-- ============================================================

ALTER TABLE OREN_CUSTOMERS ANNOTATIONS (
    ADD OR REPLACE display_label 'Customers',
    ADD OR REPLACE description 'Customers.'
);

ALTER TABLE OREN_CUSTOMERS MODIFY CUSTOMER_ID ANNOTATIONS (
    ADD OR REPLACE description 'Customer key.'
);

ALTER TABLE OREN_CUSTOMERS MODIFY FULL_NAME ANNOTATIONS (
    ADD OR REPLACE description 'Customer full name.',
    ADD OR REPLACE display_label 'Customer Name',
    ADD OR REPLACE primary_display_column 'true'
);

ALTER TABLE OREN_CUSTOMERS MODIFY EMAIL_ADDRESS ANNOTATIONS (
    ADD OR REPLACE description 'Customer email address.',
    ADD OR REPLACE semantic_type 'email_address'
);

ALTER TABLE OREN_STORES ANNOTATIONS (
    ADD OR REPLACE display_label 'Stores',
    ADD OR REPLACE description 'Physical and online storefronts.'
);

ALTER TABLE OREN_STORES MODIFY STORE_ID ANNOTATIONS (
    ADD OR REPLACE description 'Store key.'
);

ALTER TABLE OREN_STORES MODIFY STORE_NAME ANNOTATIONS (
    ADD OR REPLACE description 'Store name.',
    ADD OR REPLACE primary_display_column 'true'
);

ALTER TABLE OREN_STORES MODIFY WEB_ADDRESS ANNOTATIONS (
    ADD OR REPLACE description 'Store website.',
    ADD OR REPLACE semantic_type 'url'
);

ALTER TABLE OREN_STORES MODIFY PHYSICAL_ADDRESS ANNOTATIONS (
    ADD OR REPLACE description 'Store address.',
    ADD OR REPLACE semantic_type 'postal_address'
);

ALTER TABLE OREN_STORES MODIFY LATITUDE ANNOTATIONS (
    ADD OR REPLACE description 'Store latitude.',
    ADD OR REPLACE semantic_type 'latitude'
);

ALTER TABLE OREN_STORES MODIFY LONGITUDE ANNOTATIONS (
    ADD OR REPLACE description 'Store longitude.',
    ADD OR REPLACE semantic_type 'longitude'
);

ALTER TABLE OREN_PRODUCTS ANNOTATIONS (
    ADD OR REPLACE display_label 'Products',
    ADD OR REPLACE description 'Products for sale.'
);

ALTER TABLE OREN_PRODUCTS MODIFY PRODUCT_ID ANNOTATIONS (
    ADD OR REPLACE description 'Product key.'
);

ALTER TABLE OREN_PRODUCTS MODIFY PRODUCT_NAME ANNOTATIONS (
    ADD OR REPLACE description 'Product name.',
    ADD OR REPLACE primary_display_column 'true'
);

ALTER TABLE OREN_PRODUCTS MODIFY UNIT_PRICE ANNOTATIONS (
    ADD OR REPLACE description 'Unit price.',
    ADD OR REPLACE format_mask 'FM999G999G990D00',
    ADD OR REPLACE semantic_type 'currency_amount'
);

ALTER TABLE OREN_PRODUCTS MODIFY PRODUCT_IMAGE ANNOTATIONS (
    ADD OR REPLACE description 'Product image.',
    ADD OR REPLACE display_in_report 'false',
    ADD OR REPLACE semantic_type 'binary_image'
);

ALTER TABLE OREN_PRODUCTS MODIFY IMAGE_MIME_TYPE ANNOTATIONS (
    ADD OR REPLACE description 'Image MIME type.',
    ADD OR REPLACE display_in_form 'false',
    ADD OR REPLACE display_in_report 'false',
    ADD OR REPLACE semantic_type 'mime_type'
);

ALTER TABLE OREN_PRODUCTS MODIFY IMAGE_FILENAME ANNOTATIONS (
    ADD OR REPLACE description 'Image filename.',
    ADD OR REPLACE display_in_form 'false',
    ADD OR REPLACE display_in_report 'false',
    ADD OR REPLACE semantic_type 'file_name'
);

ALTER TABLE OREN_PRODUCTS MODIFY IMAGE_CHARSET ANNOTATIONS (
    ADD OR REPLACE description 'Image character set.',
    ADD OR REPLACE display_in_form 'false',
    ADD OR REPLACE display_in_report 'false',
    ADD OR REPLACE semantic_type 'character_set'
);

ALTER TABLE OREN_PRODUCTS MODIFY IMAGE_LAST_UPDATED ANNOTATIONS (
    ADD OR REPLACE description 'Image updated timestamp.',
    ADD OR REPLACE display_in_form 'false',
    ADD OR REPLACE display_in_report 'false',
    ADD OR REPLACE semantic_type 'date_time'
);

ALTER TABLE OREN_ORDERS ANNOTATIONS (
    ADD OR REPLACE display_label 'Orders',
    ADD OR REPLACE description 'Order headers.'
);

ALTER TABLE OREN_ORDERS MODIFY ORDER_ID ANNOTATIONS (
    ADD OR REPLACE description 'Order key.',
    ADD OR REPLACE primary_display_column 'true'
);

ALTER TABLE OREN_ORDERS MODIFY ORDER_DATETIME ANNOTATIONS (
    ADD OR REPLACE description 'Order timestamp.',
    ADD OR REPLACE format_mask 'DD-MON-YYYY HH24:MI',
    ADD OR REPLACE semantic_type 'date_time'
);

ALTER TABLE OREN_ORDERS MODIFY ORDER_CHANNEL ANNOTATIONS (
    ADD OR REPLACE description 'Order channel.',
    ADD OR REPLACE semantic_type 'enumeration',
    ADD OR REPLACE ai_context 'Valid values are ONLINE and IN_PERSON.'
);

ALTER TABLE OREN_ORDERS MODIFY ORDER_STATUS ANNOTATIONS (
    ADD OR REPLACE description 'Order status.',
    ADD OR REPLACE semantic_type 'enumeration',
    ADD OR REPLACE ai_context 'Valid values are OPEN, PAID, COMPLETE, and CANCELLED.'
);

ALTER TABLE OREN_ORDERS MODIFY STORE_ID ANNOTATIONS (
    ADD OR REPLACE description 'Store for the order.',
    ADD OR REPLACE display_label 'Store',
    ADD OR REPLACE display_as_lov 'select-list'
);

ALTER TABLE OREN_ORDERS MODIFY CUSTOMER_ID ANNOTATIONS (
    ADD OR REPLACE description 'Customer for online orders.',
    ADD OR REPLACE display_label 'Customer',
    ADD OR REPLACE display_as_lov 'select-list',
    ADD OR REPLACE ai_context 'Required for ONLINE orders and optional for IN_PERSON orders.'
);

ALTER TABLE OREN_ORDER_ITEMS ANNOTATIONS (
    ADD OR REPLACE display_label 'Order Items',
    ADD OR REPLACE description 'Order line items.'
);

ALTER TABLE OREN_ORDER_ITEMS MODIFY ORDER_ITEM_ID ANNOTATIONS (
    ADD OR REPLACE description 'Order item key.'
);

ALTER TABLE OREN_ORDER_ITEMS MODIFY ORDER_ID ANNOTATIONS (
    ADD OR REPLACE description 'Parent order.',
    ADD OR REPLACE display_label 'Order',
    ADD OR REPLACE display_as_lov 'select-list'
);

ALTER TABLE OREN_ORDER_ITEMS MODIFY PRODUCT_ID ANNOTATIONS (
    ADD OR REPLACE description 'Ordered product.',
    ADD OR REPLACE display_label 'Product',
    ADD OR REPLACE display_as_lov 'select-list'
);

ALTER TABLE OREN_ORDER_ITEMS MODIFY QUANTITY ANNOTATIONS (
    ADD OR REPLACE description 'Ordered quantity.',
    ADD OR REPLACE semantic_type 'quantity'
);

ALTER TABLE OREN_ORDER_ITEMS MODIFY UNIT_PRICE ANNOTATIONS (
    ADD OR REPLACE description 'Captured unit price.',
    ADD OR REPLACE display_label 'Selling Unit Price',
    ADD OR REPLACE format_mask 'FM999G999G990D00',
    ADD OR REPLACE semantic_type 'currency_amount'
);
