Rem Copyright (c) 2026, Oracle and/or its affiliates.

SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- ============================================================
-- BP_ORDER_ENTRY_SCHEMA_19C.SQL
-- Re-runnable Oracle 19c schema for a demo order entry app.
-- Supports:
-- - product images stored in-table
-- - stores with geolocation for APEX map regions
-- - online and in-person orders
-- - dashboard queries for sales and product performance
-- ============================================================

-- Drop child tables first so the script can be rerun without
-- requiring manual cleanup between executions.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE OREN_ORDER_ITEMS CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE OREN_ORDERS CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE OREN_PRODUCTS CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE OREN_STORES CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE OREN_CUSTOMERS CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE OREN_CUSTOMERS (
    CUSTOMER_ID     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    FULL_NAME       VARCHAR2(255) NOT NULL,
    EMAIL_ADDRESS   VARCHAR2(255) NOT NULL,
    CONSTRAINT OREN_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT OREN_CUST_EMAIL_UK UNIQUE (EMAIL_ADDRESS)
);

CREATE TABLE OREN_STORES (
    STORE_ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    STORE_NAME          VARCHAR2(255) NOT NULL,
    WEB_ADDRESS         VARCHAR2(512),
    PHYSICAL_ADDRESS    VARCHAR2(512),
    LATITUDE            NUMBER(9,6),
    LONGITUDE           NUMBER(9,6),
    CONSTRAINT OREN_STORES_PK PRIMARY KEY (STORE_ID),
    CONSTRAINT OREN_STORES_NAME_UK UNIQUE (STORE_NAME),
    CONSTRAINT OREN_STORES_ADDR_CK CHECK (
        WEB_ADDRESS IS NOT NULL OR PHYSICAL_ADDRESS IS NOT NULL
    ),
    CONSTRAINT OREN_STORES_LAT_CK CHECK (
        LATITUDE IS NULL OR (LATITUDE BETWEEN -90 AND 90)
    ),
    CONSTRAINT OREN_STORES_LON_CK CHECK (
        LONGITUDE IS NULL OR (LONGITUDE BETWEEN -180 AND 180)
    )
);

CREATE TABLE OREN_PRODUCTS (
    PRODUCT_ID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    PRODUCT_NAME         VARCHAR2(255) NOT NULL,
    UNIT_PRICE           NUMBER(10,2) NOT NULL,
    PRODUCT_IMAGE        BLOB,
    IMAGE_MIME_TYPE      VARCHAR2(255),
    IMAGE_FILENAME       VARCHAR2(255),
    IMAGE_CHARSET        VARCHAR2(128),
    IMAGE_LAST_UPDATED   TIMESTAMP,
    CONSTRAINT OREN_PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT OREN_PRODUCTS_NAME_UK UNIQUE (PRODUCT_NAME),
    CONSTRAINT OREN_PRODUCTS_PRICE_CK CHECK (UNIT_PRICE >= 0)
);

CREATE TABLE OREN_ORDERS (
    ORDER_ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_DATETIME    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ORDER_CHANNEL     VARCHAR2(10) NOT NULL,
    ORDER_STATUS      VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
    STORE_ID          NUMBER NOT NULL,
    CUSTOMER_ID       NUMBER,
    CONSTRAINT OREN_ORDERS_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT OREN_ORDERS_CHAN_CK CHECK (
        ORDER_CHANNEL IN ('ONLINE', 'IN_PERSON')
    ),
    CONSTRAINT OREN_ORDERS_STATUS_CK CHECK (
        ORDER_STATUS IN ('OPEN', 'PAID', 'COMPLETE', 'CANCELLED')
    ),
    CONSTRAINT OREN_ORDERS_CUST_REQ_CK CHECK (
        (ORDER_CHANNEL = 'ONLINE' AND CUSTOMER_ID IS NOT NULL)
        OR ORDER_CHANNEL = 'IN_PERSON'
    ),
    CONSTRAINT OREN_ORDERS_STORE_FK FOREIGN KEY (STORE_ID)
        REFERENCES OREN_STORES (STORE_ID),
    CONSTRAINT OREN_ORDERS_CUST_FK FOREIGN KEY (CUSTOMER_ID)
        REFERENCES OREN_CUSTOMERS (CUSTOMER_ID)
);

CREATE INDEX OREN_ORDERS_CUSTOMER_IX
    ON OREN_ORDERS (CUSTOMER_ID);

CREATE TABLE OREN_ORDER_ITEMS (
    ORDER_ITEM_ID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ORDER_ID        NUMBER NOT NULL,
    PRODUCT_ID      NUMBER NOT NULL,
    QUANTITY        NUMBER(10) NOT NULL,
    UNIT_PRICE      NUMBER(10,2) NOT NULL,
    CONSTRAINT OREN_ORDER_ITEMS_PK PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT OREN_OI_ORDER_FK FOREIGN KEY (ORDER_ID)
        REFERENCES OREN_ORDERS (ORDER_ID)
        ON DELETE CASCADE,
    CONSTRAINT OREN_OI_PRODUCT_FK FOREIGN KEY (PRODUCT_ID)
        REFERENCES OREN_PRODUCTS (PRODUCT_ID),
    CONSTRAINT OREN_OI_QTY_CK CHECK (QUANTITY > 0),
    CONSTRAINT OREN_OI_PRICE_CK CHECK (UNIT_PRICE >= 0)
);

CREATE INDEX OREN_ORDERS_STORE_DT_IX
    ON OREN_ORDERS (STORE_ID, ORDER_DATETIME);

CREATE INDEX OREN_ORDERS_CHAN_ST_IX
    ON OREN_ORDERS (ORDER_CHANNEL, ORDER_STATUS);

CREATE INDEX OREN_OI_PRODUCT_IX
    ON OREN_ORDER_ITEMS (PRODUCT_ID);

CREATE INDEX OREN_OI_ORDER_IX
    ON OREN_ORDER_ITEMS (ORDER_ID);


-- ============================================================
-- Table and column comments for the OREN_ demo order entry schema.
-- Convention: apex_db_dictionary / wwv_db_dictionary attributes
-- ============================================================

-- ============================================================
-- TABLE COMMENTS
-- ============================================================

COMMENT ON TABLE OREN_STORES IS 'Physical and online storefronts.';


-- ============================================================
-- OREN_CUSTOMERS
-- ============================================================

COMMENT ON COLUMN OREN_CUSTOMERS.FULL_NAME IS 'display-label: Customer Name, primary-display-column: true';


-- ============================================================
-- OREN_STORES
-- ============================================================

COMMENT ON COLUMN OREN_STORES.STORE_NAME IS 'primary-display-column: true';


-- ============================================================
-- OREN_PRODUCTS
-- ============================================================

COMMENT ON COLUMN OREN_PRODUCTS.PRODUCT_NAME IS 'primary-display-column: true';
COMMENT ON COLUMN OREN_PRODUCTS.UNIT_PRICE IS 'format-mask: FM999G999G990D00';
COMMENT ON COLUMN OREN_PRODUCTS.PRODUCT_IMAGE IS 'display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_MIME_TYPE IS 'display-in-form: false, display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_FILENAME IS 'display-in-form: false, display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_CHARSET IS 'display-in-form: false, display-in-report: false';
COMMENT ON COLUMN OREN_PRODUCTS.IMAGE_LAST_UPDATED IS 'display-in-form: false, display-in-report: false';


-- ============================================================
-- OREN_ORDERS
-- ============================================================

COMMENT ON COLUMN OREN_ORDERS.ORDER_ID IS 'primary-display-column: true';
COMMENT ON COLUMN OREN_ORDERS.ORDER_DATETIME IS 'format-mask: DD-MON-YYYY HH24:MI';
COMMENT ON COLUMN OREN_ORDERS.ORDER_CHANNEL IS 'ONLINE or IN_PERSON.';
COMMENT ON COLUMN OREN_ORDERS.STORE_ID IS 'display-label: Store';
COMMENT ON COLUMN OREN_ORDERS.CUSTOMER_ID IS 'Required for online orders only. display-label: Customer';


-- ============================================================
-- OREN_ORDER_ITEMS
-- ============================================================

COMMENT ON COLUMN OREN_ORDER_ITEMS.ORDER_ID IS 'display-label: Order';
COMMENT ON COLUMN OREN_ORDER_ITEMS.PRODUCT_ID IS 'display-label: Product';
COMMENT ON COLUMN OREN_ORDER_ITEMS.UNIT_PRICE IS 'display-label: Selling Unit Price, format-mask: FM999G999G990D00';
