-------------------------------------------------------------------------------------------------------
-- Create Sample Dataset
-------------------------------------------------------------------------------------------------------

create table eba_vector_datatable (
    id               number generated by default as identity primary key,
    col1             varchar(255),
    col2             varchar(255),
    col3             varchar(255),
    col4             varchar(255),
    col5             varchar(255),
    col6             varchar(255),
    col7             varchar(255),
    col8             varchar(255),
    col9             varchar(255),
    col10            varchar(255),
    embedding_vector vector )
/

create table eba_vector_moviedata (
    id               number generated by default as identity primary key,
    title            varchar2(255),
    moviedescription varchar2(4000),
    actors           varchar2(1000),
    genre            varchar2(255),
    release_date     date,
    rating           number,
    embedding_vector vector )
/

create table eba_vector_ai_helper (
    execution_id     number primary key,
    output           clob )
/


-------------------------------------------------------------------------------------------------------
-- Create Oracle Text Index for the movie data (AI generated data) table.
-------------------------------------------------------------------------------------------------------
begin
    execute immediate 'drop index if exists eba_vector_moviedata_desc_ftx force';

    execute immediate 'begin ctxsys.ctx_ddl.drop_preference( ''eba_vector_ds'' ); exception when others then null; end;';

    execute immediate    'begin '
                      || 'ctxsys.ctx_ddl.create_preference( ''eba_vector_ds'', ''MULTI_COLUMN_DATASTORE'');'
                      || 'ctxsys.ctx_ddl.set_attribute( ''eba_vector_ds'', ''COLUMNS'', ''TITLE,MOVIEDESCRIPTION,ACTORS'' );'
                      || 'end;';

    execute immediate    'create index eba_vector_moviedata_desc_ftx on eba_vector_moviedata (moviedescription)'
                      || 'indextype is ctxsys.context '
                      || 'parameters (''datastore eba_vector_ds sync (on commit) memory 500M'')';
exception
    when others then
        -- Oracle TEXT is not available. Ignore the error.
        null;
end;
/

-------------------------------------------------------------------------------------------------------
-- Create Oracle Text Index for the "data" (manually uploaded data) table.
-------------------------------------------------------------------------------------------------------
begin
    execute immediate 'drop index if exists eba_vector_datatable_desc_ftx force';

    execute immediate 'begin ctx_ddl.drop_preference( ''eba_vector_2_ds'' ); exception when others then null; end;';

    execute immediate    'begin '
                      || 'ctxsys.ctx_ddl.create_preference( ''eba_vector_2_ds'', ''MULTI_COLUMN_DATASTORE'');'
                      || 'ctxsys.ctx_ddl.set_attribute( ''eba_vector_2_ds'', ''COLUMNS'', ''col1,col2,col3,col4,col5,col6,col7,col8,col9,col10'' );'
                      || 'end;';

    execute immediate    'create index eba_vector_datatable_desc_ftx on eba_vector_datatable (col1)'
                      || 'indextype is ctxsys.context '
                      || 'parameters (''datastore eba_vector_2_ds sync (on commit) memory 500M'')';

exception
    when others then
        -- Oracle TEXT is not available. Ignore the error.
        null;
end;
/

-------------------------------------------------------------------------------------------------------
-- Add Sample Data
-------------------------------------------------------------------------------------------------------
begin
    -- Star Wars movie data
    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'Star Wars: A New Hope',
        'A farm boy joins a rebellion against a tyrannical empire and discovers the power of the Force',
        'Mark Hamill Carrie Fisher Harrison Ford',
        'Sci-Fi',
        to_date('1977-05-25', 'YYYY-MM-DD'),
        4.7 );

    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'Star Wars: The Empire Strikes Back',
        'The Rebel Alliance battles the Empire as Darth Vader pursues Luke Skywalker',
        'Mark Hamill Carrie Fisher Harrison Ford',
        'Sci-Fi',
        to_date('1980-05-21', 'YYYY-MM-DD'),
        4.8 );

    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'Star Wars: Return of the Jedi',
        'Luke Skywalker leads a mission to rescue Han Solo while preparing for a final confrontation with Darth Vader',
        'Mark Hamill Carrie Fisher Harrison Ford',
        'Sci-Fi', 
        to_date('1983-05-25', 'YYYY-MM-DD'), 
        4.6 );
    
    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'Star Wars: The Force Awakens',
        'A new threat emerges as a scavenger discovers her connection to the Force',
        'Daisy Ridley Adam Driver John Boyega', 
        'Sci-Fi', 
        to_date('2015-12-18', 'YYYY-MM-DD'), 
        4.5 );
    
    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'Star Wars: The Last Jedi', 
        'The Resistance struggles against the First Order while Rey seeks guidance from Luke Skywalker', 
        'Daisy Ridley Adam Driver Mark Hamill', 
        'Sci-Fi', 
        to_date('2017-12-15', 'YYYY-MM-DD'), 
        4.3 );



   -- Other movie data
    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'Interstellar',
        'A team of explorers travels through a wormhole in space to ensure humanity''s survival',
        'Matthew McConaughey Anne Hathaway Jessica Chastain', 
        'Sci-Fi', 
        to_date('2014-11-07', 'YYYY-MM-DD'), 
        4.8 );

    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'Inception',
        'A skilled thief who steals secrets through dream-sharing technology is given a chance to have his criminal history erased',
        'Leonardo DiCaprio Joseph Gordon-Levitt Ellen Page',
        'Sci-Fi', 
        to_date('2010-07-16', 'YYYY-MM-DD'), 
        4.7 );
       
    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values ('
        The Matrix',
        'A computer hacker discovers the true nature of his reality and his role in the war against its controllers',
        'Keanu Reeves Laurence Fishburne Carrie-Anne Moss', 
        'Sci-Fi', 
        to_date('1999-03-31', 'YYYY-MM-DD'), 
        4.9 );
    
    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        '2001: A Space Odyssey', 
        'A voyage to Jupiter with a sentient computer turns deadly after it begins to malfunction', 
        'Keir Dullea Gary Lockwood William Sylvester', 
        'Sci-Fi', 
        to_date('1968-04-03', 'YYYY-MM-DD'), 
        4.6 );
           
    insert into eba_vector_moviedata (
        title,
        moviedescription,
        actors,
        genre,
        release_date,
        rating )
    values (
        'The Cave',
        'A team of divers becomes trapped in an underwater cave system with predatory creatures', 
        'Cole Hauser Morris Chestnut Eddie Cibrian', 
        'Horror', 
        to_date('2005-08-26', 'YYYY-MM-DD'), 
        3.2 );
end;
/
